//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class ContCheckTableEntity
    {
        
        private int _idx;
        
        private string _ea001;
        
        private string _ea002;
        
        private DateTime? _ea003;
        
        private bool _ea004;
        
        private bool _ea005;
        
        private string _ea006;
        
        private string _ea007;
        
        private string _ea008;
        
        private string _ea009;
        
        private string _ea010;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string EA001
        {
            get
            {
                return this._ea001;
            }
            set
            {
                this._ea001 = value;
            }
        }

        /// <summary>
        /// 流水
        /// </summary>

        public string EA002
        {
            get
            {
                return this._ea002;
            }
            set
            {
                this._ea002 = value;
            }
        }

        /// <summary>
        /// 执行日期
        /// </summary>

        public DateTime? EA003
        {
            get
            {
                return this._ea003;
            }
            set
            {
                this._ea003 = value;
            }
        }

        /// <summary>
        /// 是否结账
        /// </summary>

        public bool EA004
        {
            get
            {
                return this._ea004;
            }
            set
            {
                this._ea004 = value;
            }
        }

        /// <summary>
        /// 是否有合同
        /// </summary>

        public bool EA005
        {
            get
            {
                return this._ea005;
            }
            set
            {
                this._ea005 = value;
            }
        }
        
        // 
        public string EA006
        {
            get
            {
                return this._ea006;
            }
            set
            {
                this._ea006 = value;
            }
        }
        
        // 
        public string EA007
        {
            get
            {
                return this._ea007;
            }
            set
            {
                this._ea007 = value;
            }
        }
        
        // 
        public string EA008
        {
            get
            {
                return this._ea008;
            }
            set
            {
                this._ea008 = value;
            }
        }
        
        // 
        public string EA009
        {
            get
            {
                return this._ea009;
            }
            set
            {
                this._ea009 = value;
            }
        }
        
        // 
        public string EA010
        {
            get
            {
                return this._ea010;
            }
            set
            {
                this._ea010 = value;
            }
        }
    }
}
