//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class ContractreviewEntity
    {
        
        private long _idx;
        
        private string _ht64;
        
        private string _ht01;
        
        private string _ht02;
        
        private string _ht03;
        
        private DateTime _ht04;
        
        private string _ht05;
        
        private DateTime _ht06;
        
        private string _ht07;
        
        private byte[] _ht08;
        
        private string _ht09;
        
        private string _ht10;
        
        private string _ht11;
        
        private DateTime _ht12;
        
        private string _ht13;
        
        private string _ht14;
        
        private string _ht15;
        
        private string _ht16;
        
        private string _ht17;
        
        private string _ht18;
        
        private string _ht19;
        
        private string _ht20;
        
        private string _ht21;
        
        private string _ht22;
        
        private string _ht23;
        
        private string _ht24;
        
        private string _ht25;
        
        private string _ht26;
        
        private string _ht27;
        
        private string _ht28;
        
        private string _ht29;
        
        private string _ht30;
        
        private string _ht31;
        
        private string _ht32;
        
        private string _ht33;
        
        private string _ht34;
        
        private string _ht35;
        
        private string _ht36;
        
        private string _ht37;
        
        private string _ht38;
        
        private string _ht39;
        
        private string _ht40;
        
        private string _ht41;
        
        private string _ht42;
        
        private string _ht43;
        
        private string _ht44;
        
        private string _ht45;
        
        private string _ht46;
        
        private string _ht47;
        
        private string _ht48;
        
        private string _ht49;
        
        private string _ht50;
        
        private string _ht51;
        
        private string _ht52;
        
        private string _ht53;
        
        private DateTime _ht54;
        
        private string _ht55;
        
        private DateTime _ht56;
        
        private string _ht57;
        
        private byte[] _ht58;
        
        private byte[] _ht59;
        
        private byte[] _ht60;
        
        private byte[] _ht61;
        
        private byte[] _ht62;
        
        private string _ht63;
        
        private string _ht65;
        
        private string _ht66;
        
        private string _ht67;
        
        private string _ht68;
        
        private string _ht69;
        
        private string _ht70;
        
        private string _ht71;
        
        private string _ht72;
        
        private string _ht73;
        
        private string _ht74;
        
        private string _ht75;
        
        // 
        public long idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string HT64
        {
            get
            {
                return this._ht64;
            }
            set
            {
                this._ht64 = value;
            }
        }

        /// <summary>
        /// 流水号
        /// </summary>

        public string HT01
        {
            get
            {
                return this._ht01;
            }
            set
            {
                this._ht01 = value;
            }
        }

        /// <summary>
        /// 合同编号
        /// </summary>

        public string HT02
        {
            get
            {
                return this._ht02;
            }
            set
            {
                this._ht02 = value;
            }
        }

        /// <summary>
        /// 合同分类
        /// </summary>

        public string HT03
        {
            get
            {
                return this._ht03;
            }
            set
            {
                this._ht03 = value;
            }
        }

        /// <summary>
        /// 合同评审日期
        /// </summary>

        public DateTime HT04
        {
            get
            {
                return this._ht04;
            }
            set
            {
                this._ht04 = value;
            }
        }

        /// <summary>
        /// 顾客编号
        /// </summary>

        public string HT05
        {
            get
            {
                return this._ht05;
            }
            set
            {
                this._ht05 = value;
            }
        }

        /// <summary>
        /// 合同交货日期时间
        /// </summary>

        public DateTime HT06
        {
            get
            {
                return this._ht06;
            }
            set
            {
                this._ht06 = value;
            }
        }

        /// <summary>
        /// 首检测号
        /// </summary>

        public string HT07
        {
            get
            {
                return this._ht07;
            }
            set
            {
                this._ht07 = value;
            }
        }

        /// <summary>
        /// 初审搞图片
        /// </summary>

        public byte[] HT08
        {
            get
            {
                return this._ht08;
            }
            set
            {
                this._ht08 = value;
            }
        }

        /// <summary>
        /// 业务员确认
        /// </summary>

        public string HT09
        {
            get
            {
                return this._ht09;
            }
            set
            {
                this._ht09 = value;
            }
        }

        /// <summary>
        /// 业务部经理
        /// </summary>

        public string HT10
        {
            get
            {
                return this._ht10;
            }
            set
            {
                this._ht10 = value;
            }
        }

        /// <summary>
        /// 总经理
        /// </summary>

        public string HT11
        {
            get
            {
                return this._ht11;
            }
            set
            {
                this._ht11 = value;
            }
        }

        /// <summary>
        /// 日期
        /// </summary>

        public DateTime HT12
        {
            get
            {
                return this._ht12;
            }
            set
            {
                this._ht12 = value;
            }
        }

        /// <summary>
        /// 送审状态
        /// </summary>

        public string HT13
        {
            get
            {
                return this._ht13;
            }
            set
            {
                this._ht13 = value;
            }
        }

        /// <summary>
        /// 送审意见
        /// </summary>

        public string HT14
        {
            get
            {
                return this._ht14;
            }
            set
            {
                this._ht14 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string HT15
        {
            get
            {
                return this._ht15;
            }
            set
            {
                this._ht15 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string HT16
        {
            get
            {
                return this._ht16;
            }
            set
            {
                this._ht16 = value;
            }
        }

        /// <summary>
        /// 行政评审项目1
        /// </summary>

        public string HT17
        {
            get
            {
                return this._ht17;
            }
            set
            {
                this._ht17 = value;
            }
        }

        /// <summary>
        /// 确认意见1
        /// </summary>

        public string HT18
        {
            get
            {
                return this._ht18;
            }
            set
            {
                this._ht18 = value;
            }
        }

        // 
        /// <summary>
        /// 行政评审项目2
        /// </summary>
        public string HT19
        {
            get
            {
                return this._ht19;
            }
            set
            {
                this._ht19 = value;
            }
        }

        // 
        /// <summary>
        /// 
        /// 确认意见2
        /// </summary>
        public string HT20
        {
            get
            {
                return this._ht20;
            }
            set
            {
                this._ht20 = value;
            }
        }

        // 
        /// <summary>
        /// 责任部门签字
        /// 
        /// </summary>
        public string HT21
        {
            get
            {
                return this._ht21;
            }
            set
            {
                this._ht21 = value;
            }
        }

        // 
        /// <summary>
        /// 
        /// 质检评审项目1
        /// </summary>
        public string HT22
        {
            get
            {
                return this._ht22;
            }
            set
            {
                this._ht22 = value;
            }
        }

        // 
        /// <summary>
        /// 
        /// 确认意见1
        /// </summary>
        public string HT23
        {
            get
            {
                return this._ht23;
            }
            set
            {
                this._ht23 = value;
            }
        }

        // 
        /// <summary>
        /// 质检评审项目2
        /// </summary>
        public string HT24
        {
            get
            {
                return this._ht24;
            }
            set
            {
                this._ht24 = value;
            }
        }

        // 
        /// <summary>
        /// 确认意见2
        /// </summary>
        public string HT25
        {
            get
            {
                return this._ht25;
            }
            set
            {
                this._ht25 = value;
            }
        }

        // 
        /// <summary>
        /// 责任部门签字
        /// </summary>
        public string HT26
        {
            get
            {
                return this._ht26;
            }
            set
            {
                this._ht26 = value;
            }
        }

        // 
        /// <summary>
        /// 业务评审项目1
        /// </summary>
        public string HT27
        {
            get
            {
                return this._ht27;
            }
            set
            {
                this._ht27 = value;
            }
        }

        // 
        /// <summary>
        /// 确认意见1
        /// </summary>
        public string HT28
        {
            get
            {
                return this._ht28;
            }
            set
            {
                this._ht28 = value;
            }
        }

        // 
        /// <summary>
        /// 业务评审项目2
        /// </summary>
        public string HT29
        {
            get
            {
                return this._ht29;
            }
            set
            {
                this._ht29 = value;
            }
        }

        // 
        /// <summary>
        /// 确认意见2
        /// </summary>
        public string HT30
        {
            get
            {
                return this._ht30;
            }
            set
            {
                this._ht30 = value;
            }
        }

        // 
        /// <summary>
        /// 业务评审项目3
        /// </summary>
        public string HT31
        {
            get
            {
                return this._ht31;
            }
            set
            {
                this._ht31 = value;
            }
        }

        // 
        /// <summary>
        /// 确认意见3
        /// </summary>
        public string HT32
        {
            get
            {
                return this._ht32;
            }
            set
            {
                this._ht32 = value;
            }
        }

        // 
        /// <summary>
        /// 业务评审项目4
        /// </summary>
        public string HT33
        {
            get
            {
                return this._ht33;
            }
            set
            {
                this._ht33 = value;
            }
        }

        // 
        /// <summary>
        /// 确认意见4
        /// </summary>
        public string HT34
        {
            get
            {
                return this._ht34;
            }
            set
            {
                this._ht34 = value;
            }
        }

        // 
        /// <summary>
        /// 责任部门签字
        /// </summary>
        public string HT35
        {
            get
            {
                return this._ht35;
            }
            set
            {
                this._ht35 = value;
            }
        }

        // 
        /// <summary>
        /// 木材评审项目1
        /// </summary>
        public string HT36
        {
            get
            {
                return this._ht36;
            }
            set
            {
                this._ht36 = value;
            }
        }

        // 
        /// <summary>
        /// 确认意见1
        /// </summary>
        public string HT37
        {
            get
            {
                return this._ht37;
            }
            set
            {
                this._ht37 = value;
            }
        }

        /// <summary>
        /// 木材评审项目2
        /// </summary>

        public string HT38
        {
            get
            {
                return this._ht38;
            }
            set
            {
                this._ht38 = value;
            }
        }

        // 
        /// <summary>
        /// 确认意见2
        /// </summary>
        public string HT39
        {
            get
            {
                return this._ht39;
            }
            set
            {
                this._ht39 = value;
            }
        }

        // 
        /// <summary>
        /// 责任部门签字
        /// </summary>
        public string HT40
        {
            get
            {
                return this._ht40;
            }
            set
            {
                this._ht40 = value;
            }
        }

        // 
        /// <summary>
        /// 物资评审项目1
        /// </summary>
        public string HT41
        {
            get
            {
                return this._ht41;
            }
            set
            {
                this._ht41 = value;
            }
        }

        // 
        /// <summary>
        /// 确认意见1
        /// </summary>
        public string HT42
        {
            get
            {
                return this._ht42;
            }
            set
            {
                this._ht42 = value;
            }
        }

        // 
        /// <summary>
        /// 物资评审项目2
        /// </summary>
        public string HT43
        {
            get
            {
                return this._ht43;
            }
            set
            {
                this._ht43 = value;
            }
        }

        // 
        /// <summary>
        /// 
        /// 确认意见2
        /// </summary>
        public string HT44
        {
            get
            {
                return this._ht44;
            }
            set
            {
                this._ht44 = value;
            }
        }

        // 
        /// <summary>
        /// 责任部门签字
        /// </summary>
        public string HT45
        {
            get
            {
                return this._ht45;
            }
            set
            {
                this._ht45 = value;
            }
        }

        /// <summary>
        /// 生产评审项目1
        /// </summary>

        public string HT46
        {
            get
            {
                return this._ht46;
            }
            set
            {
                this._ht46 = value;
            }
        }

        // 
        /// <summary>
        /// 确认意见1
        /// </summary>
        public string HT47
        {
            get
            {
                return this._ht47;
            }
            set
            {
                this._ht47 = value;
            }
        }

        // 
        /// <summary>
        /// 
        /// 生产评审项目2
        /// </summary>
        public string HT48
        {
            get
            {
                return this._ht48;
            }
            set
            {
                this._ht48 = value;
            }
        }

        // 
        /// <summary>
        /// 确认意见2
        /// </summary>
        public string HT49
        {
            get
            {
                return this._ht49;
            }
            set
            {
                this._ht49 = value;
            }
        }

        // 
        /// <summary>
        /// 生产评审项目3
        /// </summary>
        public string HT50
        {
            get
            {
                return this._ht50;
            }
            set
            {
                this._ht50 = value;
            }
        }

        /// <summary>
        /// 确认意见3
        /// </summary>
        public string HT51
        {
            get
            {
                return this._ht51;
            }
            set
            {
                this._ht51 = value;
            }
        }

        // 
        /// <summary>
        /// 
        /// 责任部门签字
        /// </summary>
        public string HT52
        {
            get
            {
                return this._ht52;
            }
            set
            {
                this._ht52 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string HT53
        {
            get
            {
                return this._ht53;
            }
            set
            {
                this._ht53 = value;
            }
        }

        /// <summary>
        /// 预留
        /// </summary>

        public DateTime HT54
        {
            get
            {
                return this._ht54;
            }
            set
            {
                this._ht54 = value;
            }
        }

        /// <summary>
        /// 维护意见
        /// </summary>

        public string HT55
        {
            get
            {
                return this._ht55;
            }
            set
            {
                this._ht55 = value;
            }
        }

        /// <summary>
        /// 二次变更日期
        /// </summary>

        public DateTime HT56
        {
            get
            {
                return this._ht56;
            }
            set
            {
                this._ht56 = value;
            }
        }

        /// <summary>
        /// 二次变更部门签字
        /// </summary>

        public string HT57
        {
            get
            {
                return this._ht57;
            }
            set
            {
                this._ht57 = value;
            }
        }

        /// <summary>
        /// 评审初稿
        /// </summary>

        public byte[] HT58
        {
            get
            {
                return this._ht58;
            }
            set
            {
                this._ht58 = value;
            }
        }

        /// <summary>
        /// 评审初稿
        /// </summary>

        public byte[] HT59
        {
            get
            {
                return this._ht59;
            }
            set
            {
                this._ht59 = value;
            }
        }

        /// <summary>
        /// 评审初稿
        /// </summary>

        public byte[] HT60
        {
            get
            {
                return this._ht60;
            }
            set
            {
                this._ht60 = value;
            }
        }

        /// <summary>
        /// 评审初稿
        /// </summary>

        public byte[] HT61
        {
            get
            {
                return this._ht61;
            }
            set
            {
                this._ht61 = value;
            }
        }

        /// <summary>
        /// 评审初稿
        /// </summary>

        public byte[] HT62
        {
            get
            {
                return this._ht62;
            }
            set
            {
                this._ht62 = value;
            }
        }

        /// <summary>
        /// weihujilu
        /// </summary>

        public string HT63
        {
            get
            {
                return this._ht63;
            }
            set
            {
                this._ht63 = value;
            }
        }

        /// <summary>
        /// 生产车间编号
        /// </summary>

        public string HT65
        {
            get
            {
                return this._ht65;
            }
            set
            {
                this._ht65 = value;
            }
        }

        /// <summary>
        /// 生产车间
        /// </summary>

        public string HT66
        {
            get
            {
                return this._ht66;
            }
            set
            {
                this._ht66 = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>

        public string HT67
        {
            get
            {
                return this._ht67;
            }
            set
            {
                this._ht67 = value;
            }
        }
        
        // 
        public string HT68
        {
            get
            {
                return this._ht68;
            }
            set
            {
                this._ht68 = value;
            }
        }
        
        // 
        public string HT69
        {
            get
            {
                return this._ht69;
            }
            set
            {
                this._ht69 = value;
            }
        }
        
        // 
        public string HT70
        {
            get
            {
                return this._ht70;
            }
            set
            {
                this._ht70 = value;
            }
        }
        
        // 
        public string HT71
        {
            get
            {
                return this._ht71;
            }
            set
            {
                this._ht71 = value;
            }
        }
        
        // 
        public string HT72
        {
            get
            {
                return this._ht72;
            }
            set
            {
                this._ht72 = value;
            }
        }
        
        // 
        public string HT73
        {
            get
            {
                return this._ht73;
            }
            set
            {
                this._ht73 = value;
            }
        }
        
        // 
        public string HT74
        {
            get
            {
                return this._ht74;
            }
            set
            {
                this._ht74 = value;
            }
        }
        
        // 
        public string HT75
        {
            get
            {
                return this._ht75;
            }
            set
            {
                this._ht75 = value;
            }
        }
    }
}
