//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class CustomerrecordNAEntity
    {
        
        private int _idx;
        
        private string _na001;
        
        private string _na002;
        
        private string _na003;
        
        private string _na004;
        
        private string _na005;
        
        private string _na006;
        
        private string _na007;
        
        private string _na008;
        
        private string _na009;
        
        private string _na010;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string NA001
        {
            get
            {
                return this._na001;
            }
            set
            {
                this._na001 = value;
            }
        }

        /// <summary>
        /// 原客供(更改后)
        /// </summary>

        public string NA002
        {
            get
            {
                return this._na002;
            }
            set
            {
                this._na002 = value;
            }
        }

        /// <summary>
        /// 代号
        /// </summary>

        public string NA003
        {
            get
            {
                return this._na003;
            }
            set
            {
                this._na003 = value;
            }
        }

        /// <summary>
        /// 部件名称
        /// </summary>

        public string NA004
        {
            get
            {
                return this._na004;
            }
            set
            {
                this._na004 = value;
            }
        }

        /// <summary>
        /// 材料名称
        /// </summary>

        public string NA005
        {
            get
            {
                return this._na005;
            }
            set
            {
                this._na005 = value;
            }
        }

        /// <summary>
        /// 规格尺寸
        /// </summary>

        public string NA006
        {
            get
            {
                return this._na006;
            }
            set
            {
                this._na006 = value;
            }
        }

        /// <summary>
        /// 
        ///  色号(色名)
        /// </summary>
        public string NA007
        {
            get
            {
                return this._na007;
            }
            set
            {
                this._na007 = value;
            }
        }

        /// <summary>
        /// 要点说明
        /// </summary>

        public string NA008
        {
            get
            {
                return this._na008;
            }
            set
            {
                this._na008 = value;
            }
        }

        /// <summary>
        /// 客人要求状态
        /// </summary>

        public string NA009
        {
            get
            {
                return this._na009;
            }
            set
            {
                this._na009 = value;
            }
        }
        
        // 
        public string NA010
        {
            get
            {
                return this._na010;
            }
            set
            {
                this._na010 = value;
            }
        }
    }
}
