//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class CustomerInspectionTableDMEntity
    {
        
        private int _idx;
        
        private int _dm001;
        
        private string _dm002;
        
        private string _dm003;
        
        private int _dm004;
        
        private int _dm005;
        
        private int _dm006;
        
        private int _dm007;
        
        private int _dm008;
        
        private int _dm009;
        
        private string _dm010;
        
        private string _dm011;
        
        private string _dm012;
        
        private string _dm013;
        
        private string _dm014;
        
        private string _dm015;
        
        private string _dm016;
        
        private string _dm017;
        
        private string _dm018;
        
        private string _dm019;
        
        private string _dm020;
        
        private string _dm021;
        
        private string _dm022;
        
        private string _dm023;
        
        private string _dm024;
        
        private string _dm025;
        
        private string _dm026;
        
        private string _dm027;
        
        private string _dm028;
        
        private string _dm029;
        
        private string _dm030;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 年
        /// </summary>

        public int DM001
        {
            get
            {
                return this._dm001;
            }
            set
            {
                this._dm001 = value;
            }
        }

        /// <summary>
        /// 客户
        /// </summary>

        public string DM002
        {
            get
            {
                return this._dm002;
            }
            set
            {
                this._dm002 = value;
            }
        }

        /// <summary>
        /// 班组长
        /// </summary>

        public string DM003
        {
            get
            {
                return this._dm003;
            }
            set
            {
                this._dm003 = value;
            }
        }

        /// <summary>
        /// 月份
        /// </summary>

        public int DM004
        {
            get
            {
                return this._dm004;
            }
            set
            {
                this._dm004 = value;
            }
        }

        /// <summary>
        /// 出货批次
        /// </summary>

        public int DM005
        {
            get
            {
                return this._dm005;
            }
            set
            {
                this._dm005 = value;
            }
        }

        /// <summary>
        /// 直通批次
        /// </summary>

        public int DM006
        {
            get
            {
                return this._dm006;
            }
            set
            {
                this._dm006 = value;
            }
        }

        /// <summary>
        /// 二次过批
        /// </summary>

        public int DM007
        {
            get
            {
                return this._dm007;
            }
            set
            {
                this._dm007 = value;
            }
        }
        
        /// <summary>
        /// 退货
        /// </summary>
                 
        public int DM008
        {
            get
            {
                return this._dm008;
            }
            set
            {
                this._dm008 = value;
            }
        }
        
        /// <summary>
        /// 条件接收
        /// </summary>
                 
        public int DM009
        {
            get
            {
                return this._dm009;
            }
            set
            {
                this._dm009 = value;
            }
        }
        
        // 
        public string DM010
        {
            get
            {
                return this._dm010;
            }
            set
            {
                this._dm010 = value;
            }
        }
        
        // 
        public string DM011
        {
            get
            {
                return this._dm011;
            }
            set
            {
                this._dm011 = value;
            }
        }
        
        // 
        public string DM012
        {
            get
            {
                return this._dm012;
            }
            set
            {
                this._dm012 = value;
            }
        }
        
        // 
        public string DM013
        {
            get
            {
                return this._dm013;
            }
            set
            {
                this._dm013 = value;
            }
        }
        
        // 
        public string DM014
        {
            get
            {
                return this._dm014;
            }
            set
            {
                this._dm014 = value;
            }
        }
        
        // 
        public string DM015
        {
            get
            {
                return this._dm015;
            }
            set
            {
                this._dm015 = value;
            }
        }
        
        // 
        public string DM016
        {
            get
            {
                return this._dm016;
            }
            set
            {
                this._dm016 = value;
            }
        }
        
        // 
        public string DM017
        {
            get
            {
                return this._dm017;
            }
            set
            {
                this._dm017 = value;
            }
        }
        
        // 
        public string DM018
        {
            get
            {
                return this._dm018;
            }
            set
            {
                this._dm018 = value;
            }
        }
        
        // 
        public string DM019
        {
            get
            {
                return this._dm019;
            }
            set
            {
                this._dm019 = value;
            }
        }
        
        // 
        public string DM020
        {
            get
            {
                return this._dm020;
            }
            set
            {
                this._dm020 = value;
            }
        }
        
        // 
        public string DM021
        {
            get
            {
                return this._dm021;
            }
            set
            {
                this._dm021 = value;
            }
        }
        
        // 
        public string DM022
        {
            get
            {
                return this._dm022;
            }
            set
            {
                this._dm022 = value;
            }
        }
        
        // 
        public string DM023
        {
            get
            {
                return this._dm023;
            }
            set
            {
                this._dm023 = value;
            }
        }
        
        // 
        public string DM024
        {
            get
            {
                return this._dm024;
            }
            set
            {
                this._dm024 = value;
            }
        }
        
        // 
        public string DM025
        {
            get
            {
                return this._dm025;
            }
            set
            {
                this._dm025 = value;
            }
        }
        
        // 
        public string DM026
        {
            get
            {
                return this._dm026;
            }
            set
            {
                this._dm026 = value;
            }
        }
        
        // 
        public string DM027
        {
            get
            {
                return this._dm027;
            }
            set
            {
                this._dm027 = value;
            }
        }
        
        // 
        public string DM028
        {
            get
            {
                return this._dm028;
            }
            set
            {
                this._dm028 = value;
            }
        }
        
        // 
        public string DM029
        {
            get
            {
                return this._dm029;
            }
            set
            {
                this._dm029 = value;
            }
        }
        
        // 
        public string DM030
        {
            get
            {
                return this._dm030;
            }
            set
            {
                this._dm030 = value;
            }
        }
    }
}
