//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class DetailedDeductionWYLibrary
    {
        
        private int _idx;
        
        private int _wy001;
        
        private decimal _wy002;
        
        private DateTime? _wy003;
        
        private string _wy004;
        
        private string _wy005;
        
        private string _wy006;
        
        private string _wy007;
        
        private string _wy008;
        
        private string _wy009;
        
        private string _wy010;
        
        private string _wy011;
        
        private string _wy012;
        
        private string _wy013;
        
        private string _wy014;
        
        private string _wy015;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 244idx
        /// </summary>

        public int WY001
        {
            get
            {
                return this._wy001;
            }
            set
            {
                this._wy001 = value;
            }
        }

        /// <summary>
        /// 本次扣款金额
        /// </summary>

        public decimal WY002
        {
            get
            {
                return this._wy002;
            }
            set
            {
                this._wy002 = value;
            }
        }

        /// <summary>
        /// 本次扣款日期
        /// </summary>

        public DateTime? WY003
        {
            get
            {
                return this._wy003;
            }
            set
            {
                this._wy003 = value;
            }
        }

        /// <summary>
        /// 执行状态
        /// </summary>

        public string WY004
        {
            get
            {
                return this._wy004;
            }
            set
            {
                this._wy004 = value;
            }
        }
        
        // 
        public string WY005
        {
            get
            {
                return this._wy005;
            }
            set
            {
                this._wy005 = value;
            }
        }
        
        // 
        public string WY006
        {
            get
            {
                return this._wy006;
            }
            set
            {
                this._wy006 = value;
            }
        }
        
        // 
        public string WY007
        {
            get
            {
                return this._wy007;
            }
            set
            {
                this._wy007 = value;
            }
        }
        
        // 
        public string WY008
        {
            get
            {
                return this._wy008;
            }
            set
            {
                this._wy008 = value;
            }
        }
        
        // 
        public string WY009
        {
            get
            {
                return this._wy009;
            }
            set
            {
                this._wy009 = value;
            }
        }
        
        // 
        public string WY010
        {
            get
            {
                return this._wy010;
            }
            set
            {
                this._wy010 = value;
            }
        }
        
        // 
        public string WY011
        {
            get
            {
                return this._wy011;
            }
            set
            {
                this._wy011 = value;
            }
        }
        
        // 
        public string WY012
        {
            get
            {
                return this._wy012;
            }
            set
            {
                this._wy012 = value;
            }
        }
        
        // 
        public string WY013
        {
            get
            {
                return this._wy013;
            }
            set
            {
                this._wy013 = value;
            }
        }
        
        // 
        public string WY014
        {
            get
            {
                return this._wy014;
            }
            set
            {
                this._wy014 = value;
            }
        }
        
        // 
        public string WY015
        {
            get
            {
                return this._wy015;
            }
            set
            {
                this._wy015 = value;
            }
        }
    }
}
