//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class FeedTestCOEntity
    {
        
        private int _idx;
        
        private string _co001;
        
        private string _co002;
        
        private int _co003;
        
        private int _co004;
        
        private string _co005;
        
        private string _co006;
        
        private int _co007;
        
        private int _co008;
        
        private int _co009;
        
        private int _co010;
        
        private string _co011;
        
        private string _co012;
        
        private string _co013;
        
        private string _co014;
        
        private string _co015;
        
        private string _co016;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string CO001
        {
            get
            {
                return this._co001;
            }
            set
            {
                this._co001 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string CO002
        {
            get
            {
                return this._co002;
            }
            set
            {
                this._co002 = value;
            }
        }

        /// <summary>
        /// 进货数量
        /// </summary>

        public int CO003
        {
            get
            {
                return this._co003;
            }
            set
            {
                this._co003 = value;
            }
        }

        /// <summary>
        /// 抽检数量
        /// </summary>

        public int CO004
        {
            get
            {
                return this._co004;
            }
            set
            {
                this._co004 = value;
            }
        }

        /// <summary>
        /// 批次号
        /// </summary>

        public string CO005
        {
            get
            {
                return this._co005;
            }
            set
            {
                this._co005 = value;
            }
        }

        /// <summary>
        /// 检验记录
        /// </summary>

        public string CO006
        {
            get
            {
                return this._co006;
            }
            set
            {
                this._co006 = value;
            }
        }

        /// <summary>
        /// 极严重
        /// </summary>

        public int CO007
        {
            get
            {
                return this._co007;
            }
            set
            {
                this._co007 = value;
            }
        }

        /// <summary>
        /// 严重
        /// </summary>

        public int CO008
        {
            get
            {
                return this._co008;
            }
            set
            {
                this._co008 = value;
            }
        }

        /// <summary>
        /// 轻微
        /// </summary>

        public int CO009
        {
            get
            {
                return this._co009;
            }
            set
            {
                this._co009 = value;
            }
        }
        
        /// <summary>
        /// 序号
        /// </summary>
                 
        public int CO010
        {
            get
            {
                return this._co010;
            }
            set
            {
                this._co010 = value;
            }
        }
        
        /// <summary>
        /// 物料名称
        /// </summary>
                 
        public string CO011
        {
            get
            {
                return this._co011;
            }
            set
            {
                this._co011 = value;
            }
        }
        
        // 
        public string CO012
        {
            get
            {
                return this._co012;
            }
            set
            {
                this._co012 = value;
            }
        }
        
        // 
        public string CO013
        {
            get
            {
                return this._co013;
            }
            set
            {
                this._co013 = value;
            }
        }
        
        // 
        public string CO014
        {
            get
            {
                return this._co014;
            }
            set
            {
                this._co014 = value;
            }
        }
        
        // 
        public string CO015
        {
            get
            {
                return this._co015;
            }
            set
            {
                this._co015 = value;
            }
        }
        
        // 
        public string CO016
        {
            get
            {
                return this._co016;
            }
            set
            {
                this._co016 = value;
            }
        }
    }
}
