//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class FrmpenyouqichenEntity
    {
        
        private long _idx;
        
        private string _py33;
        
        private string _py01;
        
        private string _py30;
        
        private string _py31;
        
        private string _py38;
        
        private long _py27;
        
        private string _py02;
        
        private DateTime _py03;
        
        private string _py04;
        
        private DateTime _py05;
        
        private string _py06;
        
        private string _py07;
        
        private DateTime _py08;
        
        private DateTime _py09;
        
        private string _py32;
        
        private DateTime _py34;
        
        private long _py10;
        
        private int _py11;
        
        private int _py12;
        
        private int _py13;
        
        private int _py14;
        
        private int _py15;
        
        private decimal _py16;
        
        private decimal _py17;
        
        private decimal _py18;
        
        private int _py19;
        
        private int _py20;
        
        private int _py21;
        
        private string _py22;
        
        private decimal _py23;
        
        private string _py24;
        
        private string _py25;
        
        private string _py36;
        
        private string _py26;
        
        private string _py28;
        
        private string _py29;
        
        private decimal _py35;
        
        private string _py37;
        
        private string _py39;
        
        private DateTime _py40;
        
        private string _py41;
        
        private string _py42;
        
        private string _py43;
        
        private DateTime? _py44;
        
        private string _py45;
        private string _py46;
        private bool? _py47;

        private int _u12;
        
        private int _u14;
        
        private decimal _u24;
        
        private decimal _u26;
        
        // 
        public long idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>
        public string PY33
        {
            get
            {
                return this._py33;
            }
            set
            {
                this._py33 = value;
            }
        }

        /// <summary>
        /// 流水号
        /// </summary>
        public string PY01
        {
            get
            {
                return this._py01;
            }
            set
            {
                this._py01 = value;
            }
        }

        /// <summary>
        /// 产品名称
        /// </summary>
        public string PY30
        {
            get
            {
                return this._py30;
            }
            set
            {
                this._py30 = value;
            }
        }

        /// <summary>
        /// 货号
        /// </summary>
        public string PY31
        {
            get
            {
                return this._py31;
            }
            set
            {
                this._py31 = value;
            }
        }

        /// <summary>
        /// 合同号
        /// </summary>
        public string PY38
        {
            get
            {
                return this._py38;
            }
            set
            {
                this._py38 = value;
            }
        }

        /// <summary>
        /// 产品数量
        /// </summary>
        public long PY27
        {
            get
            {
                return this._py27;
            }
            set
            {
                this._py27 = value;
            }
        }

        /// <summary>
        /// 大小板
        /// </summary>
        public string PY02
        {
            get
            {
                return this._py02;
            }
            set
            {
                this._py02 = value;
            }
        }

        /// <summary>
        /// 交货日期
        /// </summary>
       public DateTime PY03
        {
            get
            {
                return this._py03;
            }
            set
            {
                this._py03 = value;
            }
        }

        /// <summary>
        /// 填表策划人
        /// </summary>

        public string PY04
        {
            get
            {
                return this._py04;
            }
            set
            {
                this._py04 = value;
            }
        }

        /// <summary>
        /// 填表日期
        /// </summary>

        public DateTime PY05
        {
            get
            {
                return this._py05;
            }
            set
            {
                this._py05 = value;
            }
        }

        /// <summary>
        /// 开合同人
        /// </summary>

        public string PY06
        {
            get
            {
                return this._py06;
            }
            set
            {
                this._py06 = value;
            }
        }

        /// <summary>
        /// 承揽方
        /// </summary>

        public string PY07
        {
            get
            {
                return this._py07;
            }
            set
            {
                this._py07 = value;
            }
        }

        /// <summary>
        /// 约定日期
        /// </summary>

        public DateTime PY08
        {
            get
            {
                return this._py08;
            }
            set
            {
                this._py08 = value;
            }
        }

        /// <summary>
        /// 接单日期
        /// </summary>

        public DateTime PY09
        {
            get
            {
                return this._py09;
            }
            set
            {
                this._py09 = value;
            }
        }

        /// <summary>
        /// 审批人
        /// </summary>

        public string PY32
        {
            get
            {
                return this._py32;
            }
            set
            {
                this._py32 = value;
            }
        }

        /// <summary>
        /// 审批日期
        /// </summary>

        public DateTime PY34
        {
            get
            {
                return this._py34;
            }
            set
            {
                this._py34 = value;
            }
        }

        /// <summary>
        /// 产品出货套数
        /// </summary>

        public long PY10
        {
            get
            {
                return this._py10;
            }
            set
            {
                this._py10 = value;
            }
        }

        /// <summary>
        /// 每套部件数量
        /// </summary>

        public int PY11
        {
            get
            {
                return this._py11;
            }
            set
            {
                this._py11 = value;
            }
        }

        /// <summary>
        /// 每片碰面数
        /// </summary>

        public int PY12
        {
            get
            {
                return this._py12;
            }
            set
            {
                this._py12 = value;
            }
        }

        /// <summary>
        /// 片摆.翻.收次数
        /// </summary>

        public int PY13
        {
            get
            {
                return this._py13;
            }
            set
            {
                this._py13 = value;
            }
        }

        /// <summary>
        /// 长向摆放个数
        /// </summary>

        public int PY14
        {
            get
            {
                return this._py14;
            }
            set
            {
                this._py14 = value;
            }
        }

        /// <summary>
        /// 每片.每面喷.涂遍数
        /// </summary>

        public int PY15
        {
            get
            {
                return this._py15;
            }
            set
            {
                this._py15 = value;
            }
        }

        /// <summary>
        /// 日排小工人数
        /// </summary>

        public decimal PY16
        {
            get
            {
                return this._py16;
            }
            set
            {
                this._py16 = value;
            }
        }

        /// <summary>
        /// 管理提成(%)
        /// </summary>

        public decimal PY17
        {
            get
            {
                return this._py17;
            }
            set
            {
                this._py17 = value;
            }
        }

        /// <summary>
        /// 宽向摆放个数
        /// </summary>

        public decimal PY18
        {
            get
            {
                return this._py18;
            }
            set
            {
                this._py18 = value;
            }
        }

        /// <summary>
        /// 规定小工标准日工资
        /// </summary>

        public int PY19
        {
            get
            {
                return this._py19;
            }
            set
            {
                this._py19 = value;
            }
        }

        /// <summary>
        /// 老师标准日工资
        /// </summary>

        public int PY20
        {
            get
            {
                return this._py20;
            }
            set
            {
                this._py20 = value;
            }
        }

        /// <summary>
        /// 日喷单面单遍板数
        /// </summary>

        public int PY21
        {
            get
            {
                return this._py21;
            }
            set
            {
                this._py21 = value;
            }
        }

        /// <summary>
        /// 基材
        /// </summary>

        public string PY22
        {
            get
            {
                return this._py22;
            }
            set
            {
                this._py22 = value;
            }
        }

        /// <summary>
        /// 每平方米工资单价
        /// </summary>

        public decimal PY23
        {
            get
            {
                return this._py23;
            }
            set
            {
                this._py23 = value;
            }
        }

        /// <summary>
        /// 加工工艺
        /// </summary>

        public string PY24
        {
            get
            {
                return this._py24;
            }
            set
            {
                this._py24 = value;
            }
        }

        /// <summary>
        /// 零件名称
        /// </summary>

        public string PY25
        {
            get
            {
                return this._py25;
            }
            set
            {
                this._py25 = value;
            }
        }

        /// <summary>
        /// 工序
        /// </summary>

        public string PY36
        {
            get
            {
                return this._py36;
            }
            set
            {
                this._py36 = value;
            }
        }

        /// <summary>
        /// 油漆种类
        /// </summary>

        public string PY26
        {
            get
            {
                return this._py26;
            }
            set
            {
                this._py26 = value;
            }
        }

        /// <summary>
        /// 维护意见
        /// </summary>

        public string PY28
        {
            get
            {
                return this._py28;
            }
            set
            {
                this._py28 = value;
            }
        }

        /// <summary>
        /// 维护记录
        /// </summary>

        public string PY29
        {
            get
            {
                return this._py29;
            }
            set
            {
                this._py29 = value;
            }
        }

        /// <summary>
        /// 每板喷单面单遍单价(程序计算)
        /// </summary>

        public decimal PY35
        {
            get
            {
                return this._py35;
            }
            set
            {
                this._py35 = value;
            }
        }

        /// <summary>
        /// 是否复制
        /// </summary>

        public string PY37
        {
            get
            {
                return this._py37;
            }
            set
            {
                this._py37 = value;
            }
        }

        /// <summary>
        /// 审核人
        /// </summary>

        public string PY39
        {
            get
            {
                return this._py39;
            }
            set
            {
                this._py39 = value;
            }
        }

        /// <summary>
        /// 审核日期
        /// </summary>

        public DateTime PY40
        {
            get
            {
                return this._py40;
            }
            set
            {
                this._py40 = value;
            }
        }

        /// <summary>
        /// 生产车间
        /// </summary>

        public string PY41
        {
            get
            {
                return this._py41;
            }
            set
            {
                this._py41 = value;
            }
        }

        /// <summary>
        /// 大小单
        /// </summary>

        public string PY42
        {
            get
            {
                return this._py42;
            }
            set
            {
                this._py42 = value;
            }
        }

        /// <summary>
        /// 个数/板
        /// </summary>

        public string PY43
        {
            get
            {
                return this._py43;
            }
            set
            {
                this._py43 = value;
            }
        }
        
        /// <summary>
        /// 打印时间
        /// </summary>
                 
        public DateTime? PY44
        {
            get
            {
                return this._py44;
            }
            set
            {
                this._py44 = value;
            }
        }
        
        // 
        public string PY45
        {
            get
            {
                return this._py45;
            }
            set
            {
                this._py45 = value;
            }
        }
        
        /// <summary>
        /// 是否结账
        /// </summary>
        public string PY46
        {
            get
            {
                return _py46;
            }
            set
            {
                _py46 = value;
            }
        }

        /// <summary>
        /// 是否超补
        /// </summary>
        public bool? PY47
        {
            get
            {
                return _py47;
            }
            set
            {
                _py47 = value;
            }
        }

        // 
        public int U12
        {
            get
            {
                return this._u12;
            }
            set
            {
                this._u12 = value;
            }
        }
        
        // 
        public int U14
        {
            get
            {
                return this._u14;
            }
            set
            {
                this._u14 = value;
            }
        }
        
        // 
        public decimal U24
        {
            get
            {
                return this._u24;
            }
            set
            {
                this._u24 = value;
            }
        }
        
        // 
        public decimal U26
        {
            get
            {
                return this._u26;
            }
            set
            {
                this._u26 = value;
            }
        }
    }
}
