//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class MaterialProcurementSummaryBO
    {
        
        private int _idx;
        
        private string _bo001;
        
        private int _bo002;
        
        private int _bo003;
        
        private int _bo004;
        
        private int _bo005;
        
        private int _bo006;
        
        private int _bo007;
        
        private int _bo008;
        
        private int _bo009;
        
        private int _bo010;
        
        private int _bo011;
        
        private int _bo012;
        
        private int _bo013;
        
        private int _bo014;
        
        private int _bo015;
        
        private int _bo016;
        
        private int _bo017;
        
        private string _bo018;
        
        private string _bo019;
        
        private string _bo020;
        
        private string _bo021;
        
        private string _bo022;
        
        private string _bo023;
        
        private string _bo024;
        
        private string _bo025;
        
        private string _bo026;
        
        private string _bo027;
        
        private string _bo028;
        
        private string _bo029;
        
        private string _bo030;
        
        /// <summary>
        /// 
        /// </summary>
                 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }
        
        /// <summary>
        /// 单号
        /// </summary>
                 
        public string BO001
        {
            get
            {
                return this._bo001;
            }
            set
            {
                this._bo001 = value;
            }
        }
        
        /// <summary>
        /// 剩库存漆金额337
        /// </summary>

        public int BO002
        {
            get
            {
                return this._bo002;
            }
            set
            {
                this._bo002 = value;
            }
        }

        /// <summary>
        /// 盘库存漆金额337
        /// </summary>

        public int BO003
        {
            get
            {
                return this._bo003;
            }
            set
            {
                this._bo003 = value;
            }
        }

        /// <summary>
        /// 剩库存胶合密度板金额338
        /// </summary>

        public int BO004
        {
            get
            {
                return this._bo004;
            }
            set
            {
                this._bo004 = value;
            }
        }

        /// <summary>
        /// 盘库存胶合密度板金额338
        /// </summary>

        public int BO005
        {
            get
            {
                return this._bo005;
            }
            set
            {
                this._bo005 = value;
            }
        }

        /// <summary>
        /// 剩库存密度板金额338
        /// </summary>

        public int BO006
        {
            get
            {
                return this._bo006;
            }
            set
            {
                this._bo006 = value;
            }
        }

        /// <summary>
        /// 盘库存密度板金额338
        /// </summary>

        public int BO007
        {
            get
            {
                return this._bo007;
            }
            set
            {
                this._bo007 = value;
            }
        }

        /// <summary>
        /// 剩库存五金件金额343
        /// </summary>

        public int BO008
        {
            get
            {
                return this._bo008;
            }
            set
            {
                this._bo008 = value;
            }
        }

        /// <summary>
        /// 盘库存五金件金额343
        /// </summary>

        public int BO009
        {
            get
            {
                return this._bo009;
            }
            set
            {
                this._bo009 = value;
            }
        }

        /// <summary>
        /// 剩库存塑布件金额347
        /// </summary>

        public int BO010
        {
            get
            {
                return this._bo010;
            }
            set
            {
                this._bo010 = value;
            }
        }

        /// <summary>
        /// 盘库存塑布件金额347
        /// </summary>

        public int BO011
        {
            get
            {
                return this._bo011;
            }
            set
            {
                this._bo011 = value;
            }
        }

        /// <summary>
        /// 剩库存木材金额341
        /// </summary>

        public int BO012
        {
            get
            {
                return this._bo012;
            }
            set
            {
                this._bo012 = value;
            }
        }

        /// <summary>
        /// 盘库存木材金额341
        /// </summary>

        public int BO013
        {
            get
            {
                return this._bo013;
            }
            set
            {
                this._bo013 = value;
            }
        }

        /// <summary>
        /// 剩库存车木件金额342
        /// </summary>

        public int BO014
        {
            get
            {
                return this._bo014;
            }
            set
            {
                this._bo014 = value;
            }
        }

        /// <summary>
        /// 盘库存车木件金额342
        /// </summary>

        public int BO015
        {
            get
            {
                return this._bo015;
            }
            set
            {
                this._bo015 = value;
            }
        }

        /// <summary>
        /// 剩库辅料库存金额
        /// </summary>

        public int BO016
        {
            get
            {
                return this._bo016;
            }
            set
            {
                this._bo016 = value;
            }
        }

        /// <summary>
        /// 盘库辅料库存金额
        /// </summary>

        public int BO017
        {
            get
            {
                return this._bo017;
            }
            set
            {
                this._bo017 = value;
            }
        }
        
        // 
        public string BO018
        {
            get
            {
                return this._bo018;
            }
            set
            {
                this._bo018 = value;
            }
        }
        
        // 
        public string BO019
        {
            get
            {
                return this._bo019;
            }
            set
            {
                this._bo019 = value;
            }
        }
        
        // 
        public string BO020
        {
            get
            {
                return this._bo020;
            }
            set
            {
                this._bo020 = value;
            }
        }
        
        // 
        public string BO021
        {
            get
            {
                return this._bo021;
            }
            set
            {
                this._bo021 = value;
            }
        }
        
        // 
        public string BO022
        {
            get
            {
                return this._bo022;
            }
            set
            {
                this._bo022 = value;
            }
        }
        
        // 
        public string BO023
        {
            get
            {
                return this._bo023;
            }
            set
            {
                this._bo023 = value;
            }
        }
        
        // 
        public string BO024
        {
            get
            {
                return this._bo024;
            }
            set
            {
                this._bo024 = value;
            }
        }
        
        // 
        public string BO025
        {
            get
            {
                return this._bo025;
            }
            set
            {
                this._bo025 = value;
            }
        }
        
        // 
        public string BO026
        {
            get
            {
                return this._bo026;
            }
            set
            {
                this._bo026 = value;
            }
        }
        
        // 
        public string BO027
        {
            get
            {
                return this._bo027;
            }
            set
            {
                this._bo027 = value;
            }
        }
        
        // 
        public string BO028
        {
            get
            {
                return this._bo028;
            }
            set
            {
                this._bo028 = value;
            }
        }
        
        // 
        public string BO029
        {
            get
            {
                return this._bo029;
            }
            set
            {
                this._bo029 = value;
            }
        }
        
        // 
        public string BO030
        {
            get
            {
                return this._bo030;
            }
            set
            {
                this._bo030 = value;
            }
        }
    }
}
