//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class MaterialProcurementSummaryBK
    {
        
        private int _idx;
        
        private string _bk001;
        
        private string _bk002;
        
        private string _bk003;
        
        private string _bk004;
        
        private string _bk005;
        
        private string _bk006;
        
        private string _bk007;
        
        private string _bk008;
        
        private decimal _bk009;
        
        private int _bk010;
        
        private int _bk011;
        
        private decimal _bk012;
        
        private DateTime _bk013;
        
        private string _bk014;
        
        private string _bk015;
        
        private int _bk016;
        
        private string _bk017;
        
        private string _bk018;
        
        private string _bk019;
        
        private string _bk020;
        
        private string _bk021;
        
        private string _bk022;
        
        private string _bk023;
        
        private string _bk024;
        
        private string _bk025;
        
        private string _bk026;
        
        private string _bk027;
        
        private string _bk028;
        
        private string _bk029;
        
        private string _bk030;
        
        /// <summary>
        /// idx
        /// </summary>
                 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string BK001
        {
            get
            {
                return this._bk001;
            }
            set
            {
                this._bk001 = value;
            }
        }

        /// <summary>
        /// 单别
        /// </summary>

        public string BK002
        {
            get
            {
                return this._bk002;
            }
            set
            {
                this._bk002 = value;
            }
        }

        /// <summary>
        /// 使用产品名称
        /// </summary>

        public string BK003
        {
            get
            {
                return this._bk003;
            }
            set
            {
                this._bk003 = value;
            }
        }

        /// <summary>
        /// 使用产品货号
        /// </summary>

        public string BK004
        {
            get
            {
                return this._bk004;
            }
            set
            {
                this._bk004 = value;
            }
        }

        /// <summary>
        /// 使用工艺
        /// </summary>

        public string BK005
        {
            get
            {
                return this._bk005;
            }
            set
            {
                this._bk005 = value;
            }
        }

        /// <summary>
        /// 物资名称
        /// </summary>

        public string BK006
        {
            get
            {
                return this._bk006;
            }
            set
            {
                this._bk006 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string BK007
        {
            get
            {
                return this._bk007;
            }
            set
            {
                this._bk007 = value;
            }
        }

        /// <summary>
        /// 单位
        /// </summary>

        public string BK008
        {
            get
            {
                return this._bk008;
            }
            set
            {
                this._bk008 = value;
            }
        }

        /// <summary>
        /// 单价
        /// </summary>

        public decimal BK009
        {
            get
            {
                return this._bk009;
            }
            set
            {
                this._bk009 = value;
            }
        }

        /// <summary>
        /// 剩库存量个
        /// </summary>

        public int BK010
        {
            get
            {
                return this._bk010;
            }
            set
            {
                this._bk010 = value;
            }
        }

        /// <summary>
        /// 盘库存量个
        /// </summary>

        public int BK011
        {
            get
            {
                return this._bk011;
            }
            set
            {
                this._bk011 = value;
            }
        }

        /// <summary>
        /// 每套产品用量
        /// </summary>

        public decimal BK012
        {
            get
            {
                return this._bk012;
            }
            set
            {
                this._bk012 = value;
            }
        }

        /// <summary>
        /// 开合同时间
        /// </summary>

        public DateTime BK013
        {
            get
            {
                return this._bk013;
            }
            set
            {
                this._bk013 = value;
            }
        }

        /// <summary>
        /// 开合同人
        /// </summary>

        public string BK014
        {
            get
            {
                return this._bk014;
            }
            set
            {
                this._bk014 = value;
            }
        }

        /// <summary>
        /// 使用车间.人
        /// </summary>

        public string BK015
        {
            get
            {
                return this._bk015;
            }
            set
            {
                this._bk015 = value;
            }
        }

        /// <summary>
        /// 退库量
        /// </summary>

        public int BK016
        {
            get
            {
                return this._bk016;
            }
            set
            {
                this._bk016 = value;
            }
        }

        /// <summary>
        /// 退库人
        /// </summary>

        public string BK017
        {
            get
            {
                return this._bk017;
            }
            set
            {
                this._bk017 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string BK018
        {
            get
            {
                return this._bk018;
            }
            set
            {
                this._bk018 = value;
            }
        }
        
        // 
        public string BK019
        {
            get
            {
                return this._bk019;
            }
            set
            {
                this._bk019 = value;
            }
        }
        
        // 
        public string BK020
        {
            get
            {
                return this._bk020;
            }
            set
            {
                this._bk020 = value;
            }
        }
        
        // 
        public string BK021
        {
            get
            {
                return this._bk021;
            }
            set
            {
                this._bk021 = value;
            }
        }
        
        // 
        public string BK022
        {
            get
            {
                return this._bk022;
            }
            set
            {
                this._bk022 = value;
            }
        }
        
        // 
        public string BK023
        {
            get
            {
                return this._bk023;
            }
            set
            {
                this._bk023 = value;
            }
        }
        
        // 
        public string BK024
        {
            get
            {
                return this._bk024;
            }
            set
            {
                this._bk024 = value;
            }
        }
        
        // 
        public string BK025
        {
            get
            {
                return this._bk025;
            }
            set
            {
                this._bk025 = value;
            }
        }
        
        // 
        public string BK026
        {
            get
            {
                return this._bk026;
            }
            set
            {
                this._bk026 = value;
            }
        }
        
        // 
        public string BK027
        {
            get
            {
                return this._bk027;
            }
            set
            {
                this._bk027 = value;
            }
        }
        
        // 
        public string BK028
        {
            get
            {
                return this._bk028;
            }
            set
            {
                this._bk028 = value;
            }
        }
        
        // 
        public string BK029
        {
            get
            {
                return this._bk029;
            }
            set
            {
                this._bk029 = value;
            }
        }
        
        // 
        public string BK030
        {
            get
            {
                return this._bk030;
            }
            set
            {
                this._bk030 = value;
            }
        }
    }
}
