//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class MaterialProcurementSummaryBH
    {
        
        private int _idx;
        
        private string _bh001;
        
        private string _bh002;
        
        private string _bh003;
        
        private string _bh004;
        
        private int _bh005;
        
        private int _bh006;
        
        private int _bh007;
        
        private int _bh008;
        
        private int _bh009;
        
        private int _bh010;
        
        private int _bh011;
        
        private int _bh012;
        
        private string _bh013;
        
        private string _bh014;
        
        private string _bh015;
        
        private string _bh016;
        
        private string _bh017;
        
        private string _bh018;
        
        private string _bh019;
        
        private string _bh020;
        
        private string _bh021;
        
        private string _bh022;
        
        private string _bh023;
        
        private string _bh024;
        
        private string _bh025;
        
        private string _bh026;
        
        /// <summary>
        /// idx
        /// </summary>
                 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }
        /// <summary>
        /// 单号
        /// </summary>
        public string BH001
        {
            get
            {
                return this._bh001;
            }
            set
            {
                this._bh001 = value;
            }
        }

        /// <summary>
        /// 单别
        /// </summary>

        public string BH002
        {
            get
            {
                return this._bh002;
            }
            set
            {
                this._bh002 = value;
            }
        }

        /// <summary>
        /// 工艺
        /// </summary>

        public string BH003
        {
            get
            {
                return this._bh003;
            }
            set
            {
                this._bh003 = value;
            }
        }

        /// <summary>
        /// 色名
        /// </summary>

        public string BH004
        {
            get
            {
                return this._bh004;
            }
            set
            {
                this._bh004 = value;
            }
        }

        /// <summary>
        /// 采购库存漆量kg
        /// </summary>

        public int BH005
        {
            get
            {
                return this._bh005;
            }
            set
            {
                this._bh005 = value;
            }
        }

        /// <summary>
        /// 计划用漆量kg
        /// </summary>

        public int BH006
        {
            get
            {
                return this._bh006;
            }
            set
            {
                this._bh006 = value;
            }
        }

        /// <summary>
        /// 实领用漆量kg
        /// </summary>

        public int BH007
        {
            get
            {
                return this._bh007;
            }
            set
            {
                this._bh007 = value;
            }
        }

        /// <summary>
        /// 盘库存量kg
        /// </summary>

        public int BH008
        {
            get
            {
                return this._bh008;
            }
            set
            {
                this._bh008 = value;
            }
        }

        /// <summary>
        /// 采购库存漆金额
        /// </summary>

        public int BH009
        {
            get
            {
                return this._bh009;
            }
            set
            {
                this._bh009 = value;
            }
        }

        /// <summary>
        /// 计划用漆金额
        /// </summary>

        public int BH010
        {
            get
            {
                return this._bh010;
            }
            set
            {
                this._bh010 = value;
            }
        }

        /// <summary>
        /// 实领用漆金额
        /// </summary>

        public int BH011
        {
            get
            {
                return this._bh011;
            }
            set
            {
                this._bh011 = value;
            }
        }

        /// <summary>
        /// 盘库存金额
        /// </summary>

        public int BH012
        {
            get
            {
                return this._bh012;
            }
            set
            {
                this._bh012 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string BH013
        {
            get
            {
                return this._bh013;
            }
            set
            {
                this._bh013 = value;
            }
        }
        
        // 
        public string BH014
        {
            get
            {
                return this._bh014;
            }
            set
            {
                this._bh014 = value;
            }
        }
        
        // 
        public string BH015
        {
            get
            {
                return this._bh015;
            }
            set
            {
                this._bh015 = value;
            }
        }
        
        // 
        public string BH016
        {
            get
            {
                return this._bh016;
            }
            set
            {
                this._bh016 = value;
            }
        }
        
        // 
        public string BH017
        {
            get
            {
                return this._bh017;
            }
            set
            {
                this._bh017 = value;
            }
        }
        
        // 
        public string BH018
        {
            get
            {
                return this._bh018;
            }
            set
            {
                this._bh018 = value;
            }
        }
        
        // 
        public string BH019
        {
            get
            {
                return this._bh019;
            }
            set
            {
                this._bh019 = value;
            }
        }
        
        // 
        public string BH020
        {
            get
            {
                return this._bh020;
            }
            set
            {
                this._bh020 = value;
            }
        }
        
        // 
        public string BH021
        {
            get
            {
                return this._bh021;
            }
            set
            {
                this._bh021 = value;
            }
        }
        
        // 
        public string BH022
        {
            get
            {
                return this._bh022;
            }
            set
            {
                this._bh022 = value;
            }
        }
        
        // 
        public string BH023
        {
            get
            {
                return this._bh023;
            }
            set
            {
                this._bh023 = value;
            }
        }
        
        // 
        public string BH024
        {
            get
            {
                return this._bh024;
            }
            set
            {
                this._bh024 = value;
            }
        }
        
        // 
        public string BH025
        {
            get
            {
                return this._bh025;
            }
            set
            {
                this._bh025 = value;
            }
        }
        
        // 
        public string BH026
        {
            get
            {
                return this._bh026;
            }
            set
            {
                this._bh026 = value;
            }
        }
    }
}
