//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class MaterialProcurementSummaryBI
    {
        
        private int _idx;
        
        private string _bi001;
        
        private string _bi002;
        
        private string _bi003;
        
        private string _bi004;
        
        private string _bi005;
        
        private string _bi006;
        
        private string _bi007;
        
        private string _bi008;
        
        private decimal _bi009;
        
        private decimal _bi010;
        
        private int _bi011;
        
        private decimal _bi012;
        
        private DateTime _bi013;
        
        private string _bi014;
        
        private string _bi015;
        
        private int _bi016;
        
        private string _bi017;
        
        private string _bi018;
        
        private string _bi019;
        
        private string _bi020;
        
        private string _bi021;
        
        private string _bi022;
        
        private string _bi023;
        
        private string _bi024;
        
        private string _bi025;
        
        private string _bi026;
        
        private string _bi027;
        
        private string _bi028;
        
        private string _bi029;
        
        private string _bi030;
        
        /// <summary>
        /// idx
        /// </summary>
                 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string BI001
        {
            get
            {
                return this._bi001;
            }
            set
            {
                this._bi001 = value;
            }
        }

        /// <summary>
        /// 单别
        /// </summary>

        public string BI002
        {
            get
            {
                return this._bi002;
            }
            set
            {
                this._bi002 = value;
            }
        }

        /// <summary>
        /// 使用产品名称
        /// </summary>

        public string BI003
        {
            get
            {
                return this._bi003;
            }
            set
            {
                this._bi003 = value;
            }
        }

        /// <summary>
        /// 使用产品货号
        /// </summary>

        public string BI004
        {
            get
            {
                return this._bi004;
            }
            set
            {
                this._bi004 = value;
            }
        }

        /// <summary>
        /// 使用工艺
        /// </summary>

        public string BI005
        {
            get
            {
                return this._bi005;
            }
            set
            {
                this._bi005 = value;
            }
        }

        /// <summary>
        /// 物资名称
        /// </summary>

        public string BI006
        {
            get
            {
                return this._bi006;
            }
            set
            {
                this._bi006 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string BI007
        {
            get
            {
                return this._bi007;
            }
            set
            {
                this._bi007 = value;
            }
        }

        /// <summary>
        /// 单位
        /// </summary>

        public string BI008
        {
            get
            {
                return this._bi008;
            }
            set
            {
                this._bi008 = value;
            }
        }

        /// <summary>
        /// 单价
        /// </summary>

        public decimal BI009
        {
            get
            {
                return this._bi009;
            }
            set
            {
                this._bi009 = value;
            }
        }

        /// <summary>
        /// 剩库存量张
        /// </summary>

        public decimal BI010
        {
            get
            {
                return this._bi010;
            }
            set
            {
                this._bi010 = value;
            }
        }

        /// <summary>
        /// 盘库存量张
        /// </summary>

        public int BI011
        {
            get
            {
                return this._bi011;
            }
            set
            {
                this._bi011 = value;
            }
        }

        /// <summary>
        /// 每张可做产品套数
        /// </summary>

        public decimal BI012
        {
            get
            {
                return this._bi012;
            }
            set
            {
                this._bi012 = value;
            }
        }

        /// <summary>
        /// 开合同时间
        /// </summary>

        public DateTime BI013
        {
            get
            {
                return this._bi013;
            }
            set
            {
                this._bi013 = value;
            }
        }

        /// <summary>
        /// 开合同人
        /// </summary>

        public string BI014
        {
            get
            {
                return this._bi014;
            }
            set
            {
                this._bi014 = value;
            }
        }

        /// <summary>
        /// 使用车间.人
        /// </summary>

        public string BI015
        {
            get
            {
                return this._bi015;
            }
            set
            {
                this._bi015 = value;
            }
        }

        /// <summary>
        /// 退库量
        /// </summary>

        public int BI016
        {
            get
            {
                return this._bi016;
            }
            set
            {
                this._bi016 = value;
            }
        }

        /// <summary>
        /// 退库人
        /// </summary>

        public string BI017
        {
            get
            {
                return this._bi017;
            }
            set
            {
                this._bi017 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string BI018
        {
            get
            {
                return this._bi018;
            }
            set
            {
                this._bi018 = value;
            }
        }
        
        // 
        public string BI019
        {
            get
            {
                return this._bi019;
            }
            set
            {
                this._bi019 = value;
            }
        }
        
        // 
        public string BI020
        {
            get
            {
                return this._bi020;
            }
            set
            {
                this._bi020 = value;
            }
        }
        
        // 
        public string BI021
        {
            get
            {
                return this._bi021;
            }
            set
            {
                this._bi021 = value;
            }
        }
        
        // 
        public string BI022
        {
            get
            {
                return this._bi022;
            }
            set
            {
                this._bi022 = value;
            }
        }
        
        // 
        public string BI023
        {
            get
            {
                return this._bi023;
            }
            set
            {
                this._bi023 = value;
            }
        }
        
        // 
        public string BI024
        {
            get
            {
                return this._bi024;
            }
            set
            {
                this._bi024 = value;
            }
        }
        
        // 
        public string BI025
        {
            get
            {
                return this._bi025;
            }
            set
            {
                this._bi025 = value;
            }
        }
        
        // 
        public string BI026
        {
            get
            {
                return this._bi026;
            }
            set
            {
                this._bi026 = value;
            }
        }
        
        // 
        public string BI027
        {
            get
            {
                return this._bi027;
            }
            set
            {
                this._bi027 = value;
            }
        }
        
        // 
        public string BI028
        {
            get
            {
                return this._bi028;
            }
            set
            {
                this._bi028 = value;
            }
        }
        
        // 
        public string BI029
        {
            get
            {
                return this._bi029;
            }
            set
            {
                this._bi029 = value;
            }
        }
        
        // 
        public string BI030
        {
            get
            {
                return this._bi030;
            }
            set
            {
                this._bi030 = value;
            }
        }
    }
}
