//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class MaterialProcurementSummaryBL
    {
        
        private int _idx;
        
        private string _bl001;
        
        private string _bl002;
        
        private string _bl003;
        
        private string _bl004;
        
        private string _bl005;
        
        private string _bl006;
        
        private string _bl007;
        
        private string _bl008;
        
        private decimal _bl009;
        
        private decimal _bl010;
        
        private decimal _bl011;
        
        private decimal _bl012;
        
        private DateTime _bl013;
        
        private string _bl014;
        
        private string _bl015;
        
        private int _bl016;
        
        private string _bl017;
        
        private string _bl018;
        
        private string _bl019;
        
        private string _bl020;
        
        private string _bl021;
        
        private string _bl022;
        
        private string _bl023;
        
        private string _bl024;
        
        private string _bl025;
        
        private string _bl026;
        
        private string _bl027;
        
        private string _bl028;
        
        private string _bl029;
        
        private string _bl030;
        
        /// <summary>
        /// 
        /// </summary>
                 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string BL001
        {
            get
            {
                return this._bl001;
            }
            set
            {
                this._bl001 = value;
            }
        }

        /// <summary>
        /// 单别
        /// </summary>

        public string BL002
        {
            get
            {
                return this._bl002;
            }
            set
            {
                this._bl002 = value;
            }
        }

        /// <summary>
        /// 使用产品名称
        /// </summary>

        public string BL003
        {
            get
            {
                return this._bl003;
            }
            set
            {
                this._bl003 = value;
            }
        }

        /// <summary>
        /// 使用产品货号
        /// </summary>

        public string BL004
        {
            get
            {
                return this._bl004;
            }
            set
            {
                this._bl004 = value;
            }
        }

        /// <summary>
        /// 使用工艺
        /// </summary>

        public string BL005
        {
            get
            {
                return this._bl005;
            }
            set
            {
                this._bl005 = value;
            }
        }

        /// <summary>
        /// 物资名称
        /// </summary>

        public string BL006
        {
            get
            {
                return this._bl006;
            }
            set
            {
                this._bl006 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string BL007
        {
            get
            {
                return this._bl007;
            }
            set
            {
                this._bl007 = value;
            }
        }

        /// <summary>
        /// 单位
        /// </summary>

        public string BL008
        {
            get
            {
                return this._bl008;
            }
            set
            {
                this._bl008 = value;
            }
        }

        /// <summary>
        /// 单价
        /// </summary>

        public decimal BL009
        {
            get
            {
                return this._bl009;
            }
            set
            {
                this._bl009 = value;
            }
        }

        /// <summary>
        /// 剩库存量m³
        /// </summary>

        public decimal BL010
        {
            get
            {
                return this._bl010;
            }
            set
            {
                this._bl010 = value;
            }
        }

        /// <summary>
        /// 盘库存量m³
        /// </summary>

        public decimal BL011
        {
            get
            {
                return this._bl011;
            }
            set
            {
                this._bl011 = value;
            }
        }

        /// <summary>
        /// 每套产品用量
        /// </summary>

        public decimal BL012
        {
            get
            {
                return this._bl012;
            }
            set
            {
                this._bl012 = value;
            }
        }

        /// <summary>
        /// 开合同时间
        /// </summary>

        public DateTime BL013
        {
            get
            {
                return this._bl013;
            }
            set
            {
                this._bl013 = value;
            }
        }

        /// <summary>
        /// 开合同人
        /// </summary>

        public string BL014
        {
            get
            {
                return this._bl014;
            }
            set
            {
                this._bl014 = value;
            }
        }

        /// <summary>
        /// 使用车间.人
        /// </summary>

        public string BL015
        {
            get
            {
                return this._bl015;
            }
            set
            {
                this._bl015 = value;
            }
        }

        /// <summary>
        /// 退库量
        /// </summary>

        public int BL016
        {
            get
            {
                return this._bl016;
            }
            set
            {
                this._bl016 = value;
            }
        }

        /// <summary>
        /// 退库人
        /// </summary>

        public string BL017
        {
            get
            {
                return this._bl017;
            }
            set
            {
                this._bl017 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string BL018
        {
            get
            {
                return this._bl018;
            }
            set
            {
                this._bl018 = value;
            }
        }
        
        // 
        public string BL019
        {
            get
            {
                return this._bl019;
            }
            set
            {
                this._bl019 = value;
            }
        }
        
        // 
        public string BL020
        {
            get
            {
                return this._bl020;
            }
            set
            {
                this._bl020 = value;
            }
        }
        
        // 
        public string BL021
        {
            get
            {
                return this._bl021;
            }
            set
            {
                this._bl021 = value;
            }
        }
        
        // 
        public string BL022
        {
            get
            {
                return this._bl022;
            }
            set
            {
                this._bl022 = value;
            }
        }
        
        // 
        public string BL023
        {
            get
            {
                return this._bl023;
            }
            set
            {
                this._bl023 = value;
            }
        }
        
        // 
        public string BL024
        {
            get
            {
                return this._bl024;
            }
            set
            {
                this._bl024 = value;
            }
        }
        
        // 
        public string BL025
        {
            get
            {
                return this._bl025;
            }
            set
            {
                this._bl025 = value;
            }
        }
        
        // 
        public string BL026
        {
            get
            {
                return this._bl026;
            }
            set
            {
                this._bl026 = value;
            }
        }
        
        // 
        public string BL027
        {
            get
            {
                return this._bl027;
            }
            set
            {
                this._bl027 = value;
            }
        }
        
        // 
        public string BL028
        {
            get
            {
                return this._bl028;
            }
            set
            {
                this._bl028 = value;
            }
        }
        
        // 
        public string BL029
        {
            get
            {
                return this._bl029;
            }
            set
            {
                this._bl029 = value;
            }
        }
        
        // 
        public string BL030
        {
            get
            {
                return this._bl030;
            }
            set
            {
                this._bl030 = value;
            }
        }
    }
}
