//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class OtherExpenseStatementLibrary
    {
        
        private int _idx;
        
        private string _be015;
        
        private string _be001;
        
        private string _be002;
        
        private string _be003;
        
        private string _be004;
        
        private int _be005;
        
        private string _be006;
        
        private decimal _be007;
        
        private decimal _be008;
        
        private decimal _be009;
        
        private decimal _be010;
        
        private decimal _be011;
        
        private decimal _be012;
        
        private string _be013;
        
        private DateTime _be014;
        
        private string _be016;
        
        private string _be017;
        
        private string _be018;
        
        private string _be019;
        
        private string _be020;
        
        private string _be021;
        
        private string _be022;
        
        private string _be023;
        
        private string _be024;
        
        private string _be025;
        
        /// <summary>
        /// 
        /// </summary>
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }


        ////// <summary>
        /// 单号 
        /// </summary>
        public string BE015
        {
            get
            {
                return this._be015;
            }
            set
            {
                this._be015 = value;
            }
        }

        /// <summary>
        /// 产品名称  
        /// </summary>
        public string BE001
        {
            get
            {
                return this._be001;
            }
            set
            {
                this._be001 = value;
            }
        }

        /// <summary>
        /// 流水号
        /// </summary>
        public string BE002
        {
            get
            {
                return this._be002;
            }
            set
            {
                this._be002 = value;
            }
        }


        /// <summary>
        /// 货号
        /// </summary>
        public string BE003
        {
            get
            {
                return this._be003;
            }
            set
            {
                this._be003 = value;
            }
        }


        /// <summary>
        /// 合同号
        /// </summary>
        public string BE004
        {
            get
            {
                return this._be004;
            }
            set
            {
                this._be004 = value;
            }
        }


        /// <summary>
        /// 产品数量
        /// </summary>
        public int BE005
        {
            get
            {
                return this._be005;
            }
            set
            {
                this._be005 = value;
            }
        }


        /// <summary>
        /// 生产人
        /// </summary>
        public string BE006
        {
            get
            {
                return this._be006;
            }
            set
            {
                this._be006 = value;
            }
        }


        /// <summary>
        /// 装运费
        /// </summary>
        public decimal BE007
        {
            get
            {
                return this._be007;
            }
            set
            {
                this._be007 = value;
            }
        }

        /// <summary>
        /// 拖柜费
        /// </summary>
        public decimal BE008
        {
            get
            {
                return this._be008;
            }
            set
            {
                this._be008 = value;
            }
        }


        /// <summary>
        /// 代理费
        /// </summary>
        public decimal BE009
        {
            get
            {
                return this._be009;
            }
            set
            {
                this._be009 = value;
            }
        }

        /// <summary>
        /// 检测费
        /// </summary>
        public decimal BE010
        {
            get
            {
                return this._be010;
            }
            set
            {
                this._be010 = value;
            }
        }

        /// <summary>
        /// 红包
        /// </summary>
        public decimal BE011
        {
            get
            {
                return this._be011;
            }
            set
            {
                this._be011 = value;
            }
        }

        /// <summary>
        /// 其他费用
        /// </summary>
        public decimal BE012
        {
            get
            {
                return this._be012;
            }
            set
            {
                this._be012 = value;
            }
        }

        /// <summary>
        /// 231状态
        /// </summary>
        public string BE013
        {
            get
            {
                return this._be013;
            }
            set
            {
                this._be013 = value;
            }
        }

        /// <summary>
        /// 231状态日期
        /// </summary>
        public DateTime BE014
        {
            get
            {
                return this._be014;
            }
            set
            {
                this._be014 = value;
            }
        }
        
        /// <summary>
        /// 供应商编号
        /// </summary>
                 
        public string BE016
        {
            get
            {
                return this._be016;
            }
            set
            {
                this._be016 = value;
            }
        }
        
        /// <summary>
        /// 备注
        /// </summary>
                 
        public string BE017
        {
            get
            {
                return this._be017;
            }
            set
            {
                this._be017 = value;
            }
        }
        
        // 
        public string BE018
        {
            get
            {
                return this._be018;
            }
            set
            {
                this._be018 = value;
            }
        }
        
        // 
        public string BE019
        {
            get
            {
                return this._be019;
            }
            set
            {
                this._be019 = value;
            }
        }
        
        // 
        public string BE020
        {
            get
            {
                return this._be020;
            }
            set
            {
                this._be020 = value;
            }
        }
        
        // 
        public string BE021
        {
            get
            {
                return this._be021;
            }
            set
            {
                this._be021 = value;
            }
        }
        
        // 
        public string BE022
        {
            get
            {
                return this._be022;
            }
            set
            {
                this._be022 = value;
            }
        }
        
        // 
        public string BE023
        {
            get
            {
                return this._be023;
            }
            set
            {
                this._be023 = value;
            }
        }
        
        // 
        public string BE024
        {
            get
            {
                return this._be024;
            }
            set
            {
                this._be024 = value;
            }
        }
        
        // 
        public string BE025
        {
            get
            {
                return this._be025;
            }
            set
            {
                this._be025 = value;
            }
        }
    }
}
