//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class PaintEntity
    {
        
        private int _idx;
        
        private string _ed001;
        
        private string _ed002;
        
        private string _ed003;
        
        private int _ed004;
        
        private DateTime? _ed005;
        
        private decimal _ed006;
        
        private decimal _ed007;
        
        private decimal _ed008;
        
        private decimal _ed009;
        
        private decimal _ed010;
        
        private decimal _ed011;
        
        private decimal _ed012;
        
        private decimal _ed013;
        
        private decimal _ed014;
        
        private decimal _ed015;
        
        private decimal _ed016;
        
        private decimal _ed017;
        
        private decimal _ed018;
        
        private decimal _ed019;
        
        private decimal _ed020;
        
        private decimal _ed021;
        
        private decimal _ed022;
        
        private decimal _ed023;
        
        private decimal _ed024;
        
        private decimal _ed025;
        
        private decimal _ed026;
        
        private decimal _ed027;
        
        private decimal _ed028;
        
        private string _ed029;
        
        private string _ed030;
        
        private decimal _ed031;
        
        private string _ed032;
        
        private string _ed033;
        
        private string _ed034;
        
        private string _ed035;
        
        private string _ed036;
        
        private string _ed037;
        
        private string _ed038;
        
        private string _ed039;
        
        private string _ed040;
        
        private string _ed041;
        
        private string _ed042;
        
        private string _ed043;
        
        private string _ed044;
        
        private string _ed045;
        
        private string _ed046;
        
        private string _ed047;
        
        private string _ed048;
        
        private string _ed049;
        
        private string _ed050;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 产品名称
        /// </summary>

        public string ED001
        {
            get
            {
                return this._ed001;
            }
            set
            {
                this._ed001 = value;
            }
        }

        /// <summary>
        /// 流水号
        /// </summary>

        public string ED002
        {
            get
            {
                return this._ed002;
            }
            set
            {
                this._ed002 = value;
            }
        }

        /// <summary>
        /// 
        /// 货号
        /// </summary>
        public string ED003
        {
            get
            {
                return this._ed003;
            }
            set
            {
                this._ed003 = value;
            }
        }

        /// <summary>
        /// 产品数量
        /// </summary>

        public int ED004
        {
            get
            {
                return this._ed004;
            }
            set
            {
                this._ed004 = value;
            }
        }

        /// <summary>
        /// 交货日期
        /// </summary>

        public DateTime? ED005
        {
            get
            {
                return this._ed005;
            }
            set
            {
                this._ed005 = value;
            }
        }

        /// <summary>
        /// 
        ///  R-059原每套成本(喷漆)
        /// </summary>
        public decimal ED006
        {
            get
            {
                return this._ed006;
            }
            set
            {
                this._ed006 = value;
            }
        }

        /// <summary>
        /// 
        ///  R-241原每套成本(喷漆)
        /// </summary>
        public decimal ED007
        {
            get
            {
                return this._ed007;
            }
            set
            {
                this._ed007 = value;
            }
        }

        /// <summary>
        /// R-241现每套成本(喷漆)
        /// </summary>

        public decimal ED008
        {
            get
            {
                return this._ed008;
            }
            set
            {
                this._ed008 = value;
            }
        }

        /// <summary>
        ///  R-059原每套成本(滚漆)
        /// </summary>
        public decimal ED009
        {
            get
            {
                return this._ed009;
            }
            set
            {
                this._ed009 = value;
            }
        }

        /// <summary>
        ///  R-241原每套成本(滚漆)
        /// </summary>
        public decimal ED010
        {
            get
            {
                return this._ed010;
            }
            set
            {
                this._ed010 = value;
            }
        }

        /// <summary>
        ///  R-241现每套成本(滚漆)
        /// </summary>
        public decimal ED011
        {
            get
            {
                return this._ed011;
            }
            set
            {
                this._ed011 = value;
            }
        }
        
        // 
        public decimal ED012
        {
            get
            {
                return this._ed012;
            }
            set
            {
                this._ed012 = value;
            }
        }
        
        // 
        public decimal ED013
        {
            get
            {
                return this._ed013;
            }
            set
            {
                this._ed013 = value;
            }
        }
        
        // 
        public decimal ED014
        {
            get
            {
                return this._ed014;
            }
            set
            {
                this._ed014 = value;
            }
        }
        
        // 
        public decimal ED015
        {
            get
            {
                return this._ed015;
            }
            set
            {
                this._ed015 = value;
            }
        }
        
        // 
        public decimal ED016
        {
            get
            {
                return this._ed016;
            }
            set
            {
                this._ed016 = value;
            }
        }
        
        // 
        public decimal ED017
        {
            get
            {
                return this._ed017;
            }
            set
            {
                this._ed017 = value;
            }
        }
        
        // 
        public decimal ED018
        {
            get
            {
                return this._ed018;
            }
            set
            {
                this._ed018 = value;
            }
        }
        
        // 
        public decimal ED019
        {
            get
            {
                return this._ed019;
            }
            set
            {
                this._ed019 = value;
            }
        }
        
        // 
        public decimal ED020
        {
            get
            {
                return this._ed020;
            }
            set
            {
                this._ed020 = value;
            }
        }
        
        // 
        public decimal ED021
        {
            get
            {
                return this._ed021;
            }
            set
            {
                this._ed021 = value;
            }
        }
        
        // 
        public decimal ED022
        {
            get
            {
                return this._ed022;
            }
            set
            {
                this._ed022 = value;
            }
        }
        
        // 
        public decimal ED023
        {
            get
            {
                return this._ed023;
            }
            set
            {
                this._ed023 = value;
            }
        }

        /// <summary>
        /// 喷漆节省提成
        /// </summary>

        public decimal ED024
        {
            get
            {
                return this._ed024;
            }
            set
            {
                this._ed024 = value;
            }
        }

        /// <summary>
        /// 滚漆节省提成
        /// </summary>

        public decimal ED025
        {
            get
            {
                return this._ed025;
            }
            set
            {
                this._ed025 = value;
            }
        }
        
        // 
        public decimal ED026
        {
            get
            {
                return this._ed026;
            }
            set
            {
                this._ed026 = value;
            }
        }
        
        // 
        public decimal ED027
        {
            get
            {
                return this._ed027;
            }
            set
            {
                this._ed027 = value;
            }
        }
        
        // 
        public decimal ED028
        {
            get
            {
                return this._ed028;
            }
            set
            {
                this._ed028 = value;
            }
        }

        /// <summary>
        /// 主管人
        /// </summary>

        public string ED029
        {
            get
            {
                return this._ed029;
            }
            set
            {
                this._ed029 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string ED030
        {
            get
            {
                return this._ed030;
            }
            set
            {
                this._ed030 = value;
            }
        }
        
        // 
        public decimal ED031
        {
            get
            {
                return this._ed031;
            }
            set
            {
                this._ed031 = value;
            }
        }
        
        // 
        public string ED032
        {
            get
            {
                return this._ed032;
            }
            set
            {
                this._ed032 = value;
            }
        }
        
        // 
        public string ED033
        {
            get
            {
                return this._ed033;
            }
            set
            {
                this._ed033 = value;
            }
        }
        
        // 
        public string ED034
        {
            get
            {
                return this._ed034;
            }
            set
            {
                this._ed034 = value;
            }
        }
        
        // 
        public string ED035
        {
            get
            {
                return this._ed035;
            }
            set
            {
                this._ed035 = value;
            }
        }
        
        // 
        public string ED036
        {
            get
            {
                return this._ed036;
            }
            set
            {
                this._ed036 = value;
            }
        }
        
        // 
        public string ED037
        {
            get
            {
                return this._ed037;
            }
            set
            {
                this._ed037 = value;
            }
        }
        
        // 
        public string ED038
        {
            get
            {
                return this._ed038;
            }
            set
            {
                this._ed038 = value;
            }
        }
        
        // 
        public string ED039
        {
            get
            {
                return this._ed039;
            }
            set
            {
                this._ed039 = value;
            }
        }
        
        // 
        public string ED040
        {
            get
            {
                return this._ed040;
            }
            set
            {
                this._ed040 = value;
            }
        }
        
        // 
        public string ED041
        {
            get
            {
                return this._ed041;
            }
            set
            {
                this._ed041 = value;
            }
        }
        
        // 
        public string ED042
        {
            get
            {
                return this._ed042;
            }
            set
            {
                this._ed042 = value;
            }
        }
        
        // 
        public string ED043
        {
            get
            {
                return this._ed043;
            }
            set
            {
                this._ed043 = value;
            }
        }
        
        // 
        public string ED044
        {
            get
            {
                return this._ed044;
            }
            set
            {
                this._ed044 = value;
            }
        }
        
        // 
        public string ED045
        {
            get
            {
                return this._ed045;
            }
            set
            {
                this._ed045 = value;
            }
        }
        
        // 
        public string ED046
        {
            get
            {
                return this._ed046;
            }
            set
            {
                this._ed046 = value;
            }
        }
        
        // 
        public string ED047
        {
            get
            {
                return this._ed047;
            }
            set
            {
                this._ed047 = value;
            }
        }
        
        // 
        public string ED048
        {
            get
            {
                return this._ed048;
            }
            set
            {
                this._ed048 = value;
            }
        }
        
        // 
        public string ED049
        {
            get
            {
                return this._ed049;
            }
            set
            {
                this._ed049 = value;
            }
        }
        
        // 
        public string ED050
        {
            get
            {
                return this._ed050;
            }
            set
            {
                this._ed050 = value;
            }
        }
    }
}
