//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class PowerEntity
    {
        
        private long _idx;
        
        private string _dbb001;
        
        private string _dbb002;
        
        private string _dbb003;
        
        private string _dbb004;
        
        private string _dbb005;
        
        private string _dbb006;
        
        private string _dbb007;
        
        private string _dbb008;
        
        private string _dbb009;
        
        private string _dbb010;
        
        private string _dbb011;
        
        private string _dbb012;
        
        private string _dbb013;
        
        private string _dbb014;
        
        private string _dbb015;
        
        private string _dbb016;
        
        private string _dbb017;
        
        private string _dbb018;
        
        private string _dbb019;
        
        private string _dbb020;
        
        private string _dbb021;
        
        private string _dbb022;
        
        private string _dbb023;
        
        private string _dbb024;
        
        private string _dbb025;
        
        private string _dbb026;
        
        private string _dbb027;
        
        private string _dbb028;
        
        private string _dbb029;
        
        private string _dbb030;
        
        // 
        public long idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 人员编号
        /// </summary>

        public string DBB001
        {
            get
            {
                return this._dbb001;
            }
            set
            {
                this._dbb001 = value;
            }
        }

        /// <summary>
        /// 程序编号
        /// </summary>

        public string DBB002
        {
            get
            {
                return this._dbb002;
            }
            set
            {
                this._dbb002 = value;
            }
        }

        /// <summary>
        /// 运行权限
        /// </summary>

        public string DBB003
        {
            get
            {
                return this._dbb003;
            }
            set
            {
                this._dbb003 = value;
            }
        }

        /// <summary>
        /// 新增权限
        /// </summary>

        public string DBB004
        {
            get
            {
                return this._dbb004;
            }
            set
            {
                this._dbb004 = value;
            }
        }

        /// <summary>
        /// 查询权限
        /// </summary>

        public string DBB005
        {
            get
            {
                return this._dbb005;
            }
            set
            {
                this._dbb005 = value;
            }
        }

        /// <summary>
        /// 更改权限
        /// </summary>

        public string DBB006
        {
            get
            {
                return this._dbb006;
            }
            set
            {
                this._dbb006 = value;
            }
        }

        /// <summary>
        /// 删除权限
        /// </summary>

        public string DBB007
        {
            get
            {
                return this._dbb007;
            }
            set
            {
                this._dbb007 = value;
            }
        }

        /// <summary>
        /// 打印权限
        /// </summary>

        public string DBB008
        {
            get
            {
                return this._dbb008;
            }
            set
            {
                this._dbb008 = value;
            }
        }

        /// <summary>
        /// 送审权限
        /// </summary>

        public string DBB009
        {
            get
            {
                return this._dbb009;
            }
            set
            {
                this._dbb009 = value;
            }
        }

        /// <summary>
        /// 导出权限
        /// </summary>

        public string DBB010
        {
            get
            {
                return this._dbb010;
            }
            set
            {
                this._dbb010 = value;
            }
        }

        /// <summary>
        /// 执行权限
        /// </summary>

        public string DBB011
        {
            get
            {
                return this._dbb011;
            }
            set
            {
                this._dbb011 = value;
            }
        }

        /// <summary>
        /// 维护权限
        /// </summary>

        public string DBB012
        {
            get
            {
                return this._dbb012;
            }
            set
            {
                this._dbb012 = value;
            }
        }

        /// <summary>
        /// 出库权限
        /// </summary>

        public string DBB013
        {
            get
            {
                return this._dbb013;
            }
            set
            {
                this._dbb013 = value;
            }
        }

        /// <summary>
        /// 入库权限
        /// </summary>

        public string DBB014
        {
            get
            {
                return this._dbb014;
            }
            set
            {
                this._dbb014 = value;
            }
        }

        /// <summary>
        /// 保存权限
        /// </summary>

        public string DBB015
        {
            get
            {
                return this._dbb015;
            }
            set
            {
                this._dbb015 = value;
            }
        }

        /// <summary>
        /// 取消权限
        /// </summary>

        public string DBB016
        {
            get
            {
                return this._dbb016;
            }
            set
            {
                this._dbb016 = value;
            }
        }

        /// <summary>
        /// 复制权限
        /// </summary>

        public string DBB017
        {
            get
            {
                return this._dbb017;
            }
            set
            {
                this._dbb017 = value;
            }
        }
        
        // 
        public string DBB018
        {
            get
            {
                return this._dbb018;
            }
            set
            {
                this._dbb018 = value;
            }
        }
        
        // 
        public string DBB019
        {
            get
            {
                return this._dbb019;
            }
            set
            {
                this._dbb019 = value;
            }
        }
        
        // 
        public string DBB020
        {
            get
            {
                return this._dbb020;
            }
            set
            {
                this._dbb020 = value;
            }
        }
        
        // 
        public string DBB021
        {
            get
            {
                return this._dbb021;
            }
            set
            {
                this._dbb021 = value;
            }
        }
        
        // 
        public string DBB022
        {
            get
            {
                return this._dbb022;
            }
            set
            {
                this._dbb022 = value;
            }
        }
        
        // 
        public string DBB023
        {
            get
            {
                return this._dbb023;
            }
            set
            {
                this._dbb023 = value;
            }
        }
        
        // 
        public string DBB024
        {
            get
            {
                return this._dbb024;
            }
            set
            {
                this._dbb024 = value;
            }
        }
        
        // 
        public string DBB025
        {
            get
            {
                return this._dbb025;
            }
            set
            {
                this._dbb025 = value;
            }
        }
        
        // 
        public string DBB026
        {
            get
            {
                return this._dbb026;
            }
            set
            {
                this._dbb026 = value;
            }
        }
        
        // 
        public string DBB027
        {
            get
            {
                return this._dbb027;
            }
            set
            {
                this._dbb027 = value;
            }
        }
        
        // 
        public string DBB028
        {
            get
            {
                return this._dbb028;
            }
            set
            {
                this._dbb028 = value;
            }
        }
        
        // 
        public string DBB029
        {
            get
            {
                return this._dbb029;
            }
            set
            {
                this._dbb029 = value;
            }
        }
        
        // 
        public string DBB030
        {
            get
            {
                return this._dbb030;
            }
            set
            {
                this._dbb030 = value;
            }
        }
    }
}
