//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class ProductSpecificationDHEntity
    {
        
        private int _idx;
        
        private string _dh001;
        
        private string _dh002;
        
        private string _dh003;
        
        private string _dh004;
        
        private string _dh005;
        
        private string _dh006;
        
        private string _dh007;
        
        private string _dh008;
        
        private string _dh009;
        
        private string _dh010;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 项类
        /// </summary>

        public string DH001
        {
            get
            {
                return this._dh001;
            }
            set
            {
                this._dh001 = value;
            }
        }

        /// <summary>
        /// 项号
        /// </summary>

        public string DH002
        {
            get
            {
                return this._dh002;
            }
            set
            {
                this._dh002 = value;
            }
        }

        /// <summary>
        /// 项目
        /// </summary>

        public string DH003
        {
            get
            {
                return this._dh003;
            }
            set
            {
                this._dh003 = value;
            }
        }
        
        // 
        public string DH004
        {
            get
            {
                return this._dh004;
            }
            set
            {
                this._dh004 = value;
            }
        }
        
        // 
        public string DH005
        {
            get
            {
                return this._dh005;
            }
            set
            {
                this._dh005 = value;
            }
        }
        
        // 
        public string DH006
        {
            get
            {
                return this._dh006;
            }
            set
            {
                this._dh006 = value;
            }
        }
        
        // 
        public string DH007
        {
            get
            {
                return this._dh007;
            }
            set
            {
                this._dh007 = value;
            }
        }
        
        // 
        public string DH008
        {
            get
            {
                return this._dh008;
            }
            set
            {
                this._dh008 = value;
            }
        }
        
        // 
        public string DH009
        {
            get
            {
                return this._dh009;
            }
            set
            {
                this._dh009 = value;
            }
        }
        
        // 
        public string DH010
        {
            get
            {
                return this._dh010;
            }
            set
            {
                this._dh010 = value;
            }
        }
    }
}
