//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class ProductSpecificationDGEntity
    {
        
        private int _idx;
        
        private string _dg001;
        
        private DateTime? _dg002;
        
        private string _dg003;
        
        private string _dg004;
        
        private string _dg005;
        
        private int _dg006;
        
        private int _dg007;
        
        private int _dg008;
        
        private int _dg009;
        
        private int _dg010;
        
        private int _dg011;
        
        private int _dg012;
        
        private int _dg013;
        
        private int _dg014;
        
        private decimal _dg015;
        
        private decimal _dg016;
        
        private string _dg017;
        
        private string _dg018;
        
        private string _dg019;
        
        private string _dg020;
        
        private string _dg021;
        
        private string _dg022;
        
        private string _dg023;
        
        private string _dg024;
        
        private string _dg025;
        
        private string _dg026;
        
        private string _dg027;
        
        private string _dg028;
        
        private string _dg029;
        
        private string _dg030;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string DG001
        {
            get
            {
                return this._dg001;
            }
            set
            {
                this._dg001 = value;
            }
        }

        /// <summary>
        /// 检期
        /// </summary>

        public DateTime? DG002
        {
            get
            {
                return this._dg002;
            }
            set
            {
                this._dg002 = value;
            }
        }

        /// <summary>
        /// 部件名称
        /// </summary>

        public string DG003
        {
            get
            {
                return this._dg003;
            }
            set
            {
                this._dg003 = value;
            }
        }

        /// <summary>
        /// 被检验工序
        /// </summary>

        public string DG004
        {
            get
            {
                return this._dg004;
            }
            set
            {
                this._dg004 = value;
            }
        }

        /// <summary>
        /// 干燥度
        /// </summary>

        public string DG005
        {
            get
            {
                return this._dg005;
            }
            set
            {
                this._dg005 = value;
            }
        }

        /// <summary>
        /// 部件数量
        /// </summary>

        public int DG006
        {
            get
            {
                return this._dg006;
            }
            set
            {
                this._dg006 = value;
            }
        }

        /// <summary>
        /// 送检数
        /// </summary>

        public int DG007
        {
            get
            {
                return this._dg007;
            }
            set
            {
                this._dg007 = value;
            }
        }

        /// <summary>
        /// 送检累计数量
        /// </summary>

        public int DG008
        {
            get
            {
                return this._dg008;
            }
            set
            {
                this._dg008 = value;
            }
        }

        /// <summary>
        /// 全检合格品数
        /// </summary>

        public int DG009
        {
            get
            {
                return this._dg009;
            }
            set
            {
                this._dg009 = value;
            }
        }

        /// <summary>
        /// 累计合格品数
        /// </summary>

        public int DG010
        {
            get
            {
                return this._dg010;
            }
            set
            {
                this._dg010 = value;
            }
        }

        /// <summary>
        /// 报废品数
        /// </summary>

        public int DG011
        {
            get
            {
                return this._dg011;
            }
            set
            {
                this._dg011 = value;
            }
        }

        /// <summary>
        /// 可返修数
        /// </summary>

        public int DG012
        {
            get
            {
                return this._dg012;
            }
            set
            {
                this._dg012 = value;
            }
        }

        /// <summary>
        /// 需再补产数
        /// </summary>

        public int DG013
        {
            get
            {
                return this._dg013;
            }
            set
            {
                this._dg013 = value;
            }
        }

        /// <summary>
        /// 余量
        /// </summary>

        public int DG014
        {
            get
            {
                return this._dg014;
            }
            set
            {
                this._dg014 = value;
            }
        }

        /// <summary>
        /// 检前合格率
        /// </summary>

        public decimal DG015
        {
            get
            {
                return this._dg015;
            }
            set
            {
                this._dg015 = value;
            }
        }

        /// <summary>
        /// 检后合格率
        /// </summary>

        public decimal DG016
        {
            get
            {
                return this._dg016;
            }
            set
            {
                this._dg016 = value;
            }
        }

        /// <summary>
        /// QC检验人
        /// </summary>

        public string DG017
        {
            get
            {
                return this._dg017;
            }
            set
            {
                this._dg017 = value;
            }
        }

        /// <summary>
        /// 检后合格率鉴定人
        /// </summary>

        public string DG018
        {
            get
            {
                return this._dg018;
            }
            set
            {
                this._dg018 = value;
            }
        }

        /// <summary>
        /// 标准样签发人
        /// </summary>

        public string DG019
        {
            get
            {
                return this._dg019;
            }
            set
            {
                this._dg019 = value;
            }
        }

        /// <summary>
        /// 可返修品不同质量分类存放记录或检验要点描述及生产人
        /// </summary>

        public string DG020
        {
            get
            {
                return this._dg020;
            }
            set
            {
                this._dg020 = value;
            }
        }

        /// <summary>
        /// 检验规定工时
        /// </summary>

        public string DG021
        {
            get
            {
                return this._dg021;
            }
            set
            {
                this._dg021 = value;
            }
        }
        
        // 
        public string DG022
        {
            get
            {
                return this._dg022;
            }
            set
            {
                this._dg022 = value;
            }
        }
        
        // 
        public string DG023
        {
            get
            {
                return this._dg023;
            }
            set
            {
                this._dg023 = value;
            }
        }
        
        // 
        public string DG024
        {
            get
            {
                return this._dg024;
            }
            set
            {
                this._dg024 = value;
            }
        }
        
        // 
        public string DG025
        {
            get
            {
                return this._dg025;
            }
            set
            {
                this._dg025 = value;
            }
        }
        
        // 
        public string DG026
        {
            get
            {
                return this._dg026;
            }
            set
            {
                this._dg026 = value;
            }
        }
        
        // 
        public string DG027
        {
            get
            {
                return this._dg027;
            }
            set
            {
                this._dg027 = value;
            }
        }
        
        // 
        public string DG028
        {
            get
            {
                return this._dg028;
            }
            set
            {
                this._dg028 = value;
            }
        }
        
        // 
        public string DG029
        {
            get
            {
                return this._dg029;
            }
            set
            {
                this._dg029 = value;
            }
        }
        
        // 
        public string DG030
        {
            get
            {
                return this._dg030;
            }
            set
            {
                this._dg030 = value;
            }
        }
    }
}
