//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class ProductSpecificationDFEntity
    {
        
        private int _idx;
        
        private string _df001;
        
        private string _df002;
        
        private string _df003;
        
        private string _df004;
        
        private int _df005;
        
        private DateTime? _df006;
        
        private int _df007;
        
        private string _df008;
        
        private string _df009;
        
        private string _df010;

        private bool _df011;
        private bool _df012;
        private bool _df013;
        private bool _df014;
        private bool _df015;
        private bool _df016;
        private bool _df017;
        private bool _df018;
        private bool _df019;
        private bool _df020;
        private bool _df021;
        private bool _df022;
        private bool _df023;
        private bool _df024;
        private bool _df025;
        private bool _df026;
        private bool _df027;
        private bool _df028;
        private bool _df029;
        private bool _df030;
        private bool _df031;
        private bool _df032;
        private bool _df033;
        private bool _df034;
        private bool _df035;
        private bool _df036;
        private bool _df037;
        private bool _df038;
        private bool _df039;
        private bool _df040;
        private bool _df041;
        private bool _df042;
        private bool _df043;
        private bool _df044;
        private bool _df045;
        private bool _df046;
        private bool _df047;
        private bool _df048;
        private bool _df049;
        private bool _df050;
        private bool _df051;
        private bool _df052;
        private bool _df053;
        private bool _df054;
        private bool _df055;
        private bool _df056;
        private bool _df057;
        private bool _df058;
        private bool _df059;
        private bool _df060;
        private bool _df061;
        private bool _df062;
        private bool _df063;
        private bool _df064;
        private bool _df065;
        private bool _df066;
        private bool _df067;
        private bool _df068;
        private bool _df069;

        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string DF001
        {
            get
            {
                return this._df001;
            }
            set
            {
                this._df001 = value;
            }
        }

        /// <summary>
        /// 产品名称
        /// </summary>

        public string DF002
        {
            get
            {
                return this._df002;
            }
            set
            {
                this._df002 = value;
            }
        }

        /// <summary>
        /// 货号
        /// </summary>

        public string DF003
        {
            get
            {
                return this._df003;
            }
            set
            {
                this._df003 = value;
            }
        }

        /// <summary>
        /// 流水号
        /// </summary>

        public string DF004
        {
            get
            {
                return this._df004;
            }
            set
            {
                this._df004 = value;
            }
        }

        /// <summary>
        /// 产品数量
        /// </summary>

        public int DF005
        {
            get
            {
                return this._df005;
            }
            set
            {
                this._df005 = value;
            }
        }

        /// <summary>
        /// 交货日期
        /// </summary>

        public DateTime? DF006
        {
            get
            {
                return this._df006;
            }
            set
            {
                this._df006 = value;
            }
        }

        /// <summary>
        /// 检验次数
        /// </summary>

        public int DF007
        {
            get
            {
                return this._df007;
            }
            set
            {
                this._df007 = value;
            }
        }

        /// <summary>
        /// QC组长
        /// </summary>

        public string DF008
        {
            get
            {
                return this._df008;
            }
            set
            {
                this._df008 = value;
            }
        }

        /// <summary>
        /// QC检验员
        /// </summary>

        public string DF009
        {
            get
            {
                return this._df009;
            }
            set
            {
                this._df009 = value;
            }
        }

        /// <summary>
        /// 生产人
        /// </summary>

        public string DF010
        {
            get
            {
                return this._df010;
            }
            set
            {
                this._df010 = value;
            }
        }

        /// <summary>
        /// ⑴喷、涂漆
        /// </summary>
        public bool DF011
        {
            set
            {
                _df011 = value;
            }
            get
            {
                return _df011;
            }
        }
        /// <summary>
        /// ⑵滚漆
        /// </summary>
        public bool DF012
        {
            set
            {
                _df012 = value;
            }
            get
            {
                return _df012;
            }
        }
        /// <summary>
        /// ⑶丝网、走台印刷
        /// </summary>
        public bool DF013
        {
            set
            {
                _df013 = value;
            }
            get
            {
                return _df013;
            }
        }
        /// <summary>
        /// ⑷热转印
        /// </summary>
        public bool DF014
        {
            set
            {
                _df014 = value;
            }
            get
            {
                return _df014;
            }
        }
        /// <summary>
        /// ⑸移印
        /// </summary>
        public bool DF015
        {
            set
            {
                _df015 = value;
            }
            get
            {
                return _df015;
            }
        }
        /// <summary>
        ///  ⑹烫印
        /// </summary>
        public bool DF016
        {
            set
            {
                _df016 = value;
            }
            get
            {
                return _df016;
            }
        }
        /// <summary>
        /// ⑺描画
        /// </summary>
        public bool DF017
        {
            set
            {
                _df017 = value;
            }
            get
            {
                return _df017;
            }
        }
        /// <summary>
        /// ⑻粘接
        /// </summary>
        public bool DF018
        {
            set
            {
                _df018 = value;
            }
            get
            {
                return _df018;
            }
        }
        /// <summary>
        /// ⑼组装
        /// </summary>
        public bool DF019
        {
            set
            {
                _df019 = value;
            }
            get
            {
                return _df019;
            }
        }
        /// <summary>
        /// ⑽检验
        /// </summary>
        public bool DF020
        {
            set
            {
                _df020 = value;
            }
            get
            {
                return _df020;
            }
        }
        /// <summary>
        /// ⑾包装
        /// </summary>
        public bool DF021
        {
            set
            {
                _df021 = value;
            }
            get
            {
                return _df021;
            }
        }
        /// <summary>
        /// ⑿木档、竹扦干燥度
        /// </summary>
        public bool DF022
        {
            set
            {
                _df022 = value;
            }
            get
            {
                return _df022;
            }
        }
        /// <summary>
        /// ⒀虫蛀、霉烂
        /// </summary>
        public bool DF023
        {
            set
            {
                _df023 = value;
            }
            get
            {
                return _df023;
            }
        }
        /// <summary>
        /// ⒁开裂、变形
        /// </summary>
        public bool DF024
        {
            set
            {
                _df024 = value;
            }
            get
            {
                return _df024;
            }
        }
        /// <summary>
        /// (15)干燥度
        /// </summary>
        public bool DF025
        {
            set
            {
                _df025 = value;
            }
            get
            {
                return _df025;
            }
        }
        /// <summary>
        /// (16)材质符合性
        /// </summary>
        public bool DF026
        {
            set
            {
                _df026 = value;
            }
            get
            {
                return _df026;
            }
        }
        /// <summary>
        /// (17)尺寸公差
        /// </summary>
        public bool DF027
        {
            set
            {
                _df027 = value;
            }
            get
            {
                return _df027;
            }
        }
        /// <summary>
        /// (18)板缝紧密度
        /// </summary>
        public bool DF028
        {
            set
            {
                _df028 = value;
            }
            get
            {
                return _df028;
            }
        }
        /// <summary>
        /// (19)开裂
        /// </summary>
        public bool DF029
        {
            set
            {
                _df029 = value;
            }
            get
            {
                return _df029;
            }
        }
        /// <summary>
        /// (20)变形弯曲
        /// </summary>
        public bool DF030
        {
            set
            {
                _df030 = value;
            }
            get
            {
                return _df030;
            }
        }
        /// <summary>
        /// (21)蛀虫
        /// </summary>
        public bool DF031
        {
            set
            {
                _df031 = value;
            }
            get
            {
                return _df031;
            }
        }
        /// <summary>
        /// (22)砂、磨、抛光洁度
        /// </summary>
        public bool DF032
        {
            set
            {
                _df032 = value;
            }
            get
            {
                return _df032;
            }
        }
        /// <summary>
        /// (23)老鼠牙
        /// </summary>
        public bool DF033
        {
            set
            {
                _df033 = value;
            }
            get
            {
                return _df033;
            }
        }
        /// <summary>
        /// (24)砂皮补灰
        /// </summary>
        public bool DF034
        {
            set
            {
                _df034 = value;
            }
            get
            {
                return _df034;
            }
        }
        /// <summary>
        /// (25)利边、尖端、毛刺
        /// </summary>
        public bool DF035
        {
            set
            {
                _df035 = value;
            }
            get
            {
                return _df035;
            }
        }
        /// <summary>
        /// (26)划、碰压损伤
        /// </summary>
        public bool DF036
        {
            set
            {
                _df036 = value;
            }
            get
            {
                return _df036;
            }
        }
        /// <summary>
        /// (27)光滑度、利边
        /// </summary>
        public bool DF037
        {
            set
            {
                _df037 = value;
            }
            get
            {
                return _df037;
            }
        }
        /// <summary>
        /// (28)色差
        /// </summary>
        public bool DF038
        {
            set
            {
                _df038 = value;
            }
            get
            {
                return _df038;
            }
        }
        /// <summary>
        /// (29)色均匀度
        /// </summary>
        public bool DF039
        {
            set
            {
                _df039 = value;
            }
            get
            {
                return _df039;
            }
        }
        /// <summary>
        /// (30)剥底漆
        /// </summary>
        public bool DF040
        {
            set
            {
                _df040 = value;
            }
            get
            {
                return _df040;
            }
        }
        /// <summary>
        /// (31)掉面漆、挂漆
        /// </summary>
        public bool DF041
        {
            set
            {
                _df041 = value;
            }
            get
            {
                return _df041;
            }
        }
        /// <summary>
        /// (32)色转移（用纸布擦）
        /// </summary>
        public bool DF042
        {
            set
            {
                _df042 = value;
            }
            get
            {
                return _df042;
            }
        }
        /// <summary>
        /// (33)吐色(湿布或水浸)
        /// </summary>
        public bool DF043
        {
            set
            {
                _df043 = value;
            }
            get
            {
                return _df043;
            }
        }
        /// <summary>
        ///  (34)粘漆
        /// </summary>
        public bool DF044
        {
            set
            {
                _df044 = value;
            }
            get
            {
                return _df044;
            }
        }
        /// <summary>
        ///  (35)互染色
        /// </summary>
        public bool DF045
        {
            set
            {
                _df045 = value;
            }
            get
            {
                return _df045;
            }
        }
        /// <summary>
        /// (36)面、底漆厚薄及均匀度 ⑾亚光、半亚、亮光度
        /// </summary>
        public bool DF046
        {
            set
            {
                _df046 = value;
            }
            get
            {
                return _df046;
            }
        }
        /// <summary>
        /// (37)漏底
        /// </summary>
        public bool DF047
        {
            set
            {
                _df047 = value;
            }
            get
            {
                return _df047;
            }
        }
        /// <summary>
        /// (38)泛白
        /// </summary>
        public bool DF048
        {
            set
            {
                _df048 = value;
            }
            get
            {
                return _df048;
            }
        }
        /// <summary>
        ///  (39)点斑
        /// </summary>
        public bool DF049
        {
            set
            {
                _df049 = value;
            }
            get
            {
                return _df049;
            }
        }
        /// <summary>
        /// (40)污脏
        /// </summary>
        public bool DF050
        {
            set
            {
                _df050 = value;
            }
            get
            {
                return _df050;
            }
        }
        /// <summary>
        /// (41)划、碰、压伤
        /// </summary>
        public bool DF051
        {
            set
            {
                _df051 = value;
            }
            get
            {
                return _df051;
            }
        }
        /// <summary>
        /// (42)印刷图案
        /// </summary>
        public bool DF052
        {
            set
            {
                _df052 = value;
            }
            get
            {
                return _df052;
            }
        }
        /// <summary>
        ///  (43)位置正确度
        /// </summary>
        public bool DF053
        {
            set
            {
                _df053 = value;
            }
            get
            {
                return _df053;
            }
        }
        /// <summary>
        /// (44)清晰度
        /// </summary>
        public bool DF054
        {
            set
            {
                _df054 = value;
            }
            get
            {
                return _df054;
            }
        }
        /// <summary>
        /// (45)线条精细度
        /// </summary>
        public bool DF055
        {
            set
            {
                _df055 = value;
            }
            get
            {
                return _df055;
            }
        }
        /// <summary>
        /// (46)亚光、半亚、亮光度
        /// </summary>
        public bool DF056
        {
            set
            {
                _df056 = value;
            }
            get
            {
                return _df056;
            }
        }
        /// <summary>
        /// (59)牢固度
        /// </summary>
        public bool DF057
        {
            set
            {
                _df057 = value;
            }
            get
            {
                return _df057;
            }
        }
        /// <summary>
        /// (47)功能（转动灵活、部位用途功能符合要求）
        /// </summary>
        public bool DF058
        {
            set
            {
                _df058 = value;
            }
            get
            {
                return _df058;
            }
        }
        /// <summary>
        /// (48)公差配合度
        /// </summary>
        public bool DF059
        {
            set
            {
                _df059 = value;
            }
            get
            {
                return _df059;
            }
        }
        /// <summary>
        /// (49)接缝紧密度
        /// </summary>
        public bool DF060
        {
            set
            {
                _df060 = value;
            }
            get
            {
                return _df060;
            }
        }

        /// <summary>
        /// (50)白胶外溢
        /// </summary>
        public bool DF061
        {
            get
            {
                return _df061;
            }

            set
            {
                _df061 = value;
            }
        }

        /// <summary>
        /// (51)换位、倒位、偏位、移位
        /// </summary>
        public bool DF062
        {
            get
            {
                return _df062;
            }

            set
            {
                _df062 = value;
            }
        }

        /// <summary>
        /// (52)缺装件
        /// </summary>
        public bool DF063
        {
            get
            {
                return _df063;
            }

            set
            {
                _df063 = value;
            }
        }

        /// <summary>
        /// (53)利边、尖端、毛刺、光洁度
        /// </summary>
        public bool DF064
        {
            get
            {
                return _df064;
            }

            set
            {
                _df064 = value;
            }
        }

        /// <summary>
        /// (54)划、碰、压伤 
        /// </summary>
        public bool DF065
        {
            get
            {
                return _df065;
            }

            set
            {
                _df065 = value;
            }
        }

        /// <summary>
        /// (55)部件合格性
        /// </summary>
        public bool DF066
        {
            get
            {
                return _df066;
            }

            set
            {
                _df066 = value;
            }
        }

        /// <summary>
        /// (56)铁锈斑点
        /// </summary>
        public bool DF067
        {
            get
            {
                return _df067;
            }

            set
            {
                _df067 = value;
            }
        }

        /// <summary>
        /// (57)绳、带的长短
        /// </summary>
        public bool DF068
        {
            get
            {
                return _df068;
            }

            set
            {
                _df068 = value;
            }
        }

        /// <summary>
        /// (58)绳、带打结的牢固度 
        /// </summary>
        public bool DF069
        {
            get
            {
                return _df069;
            }

            set
            {
                _df069 = value;
            }
        }
    }
}
