//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class QualityFinalInspsctionDIEntity
    {
        
        private int _idx;
        
        private string _di001;
        
        private string _di002;
        
        private string _di003;
        
        private string _di004;
        
        private int _di005;
        
        private string _di006;
        
        private string _di007;
        
        private int _di008;
        
        private DateTime? _di009;
        
        private DateTime? _di010;
        
        private string _di011;
        
        private DateTime? _di012;
        
        private DateTime? _di013;
        
        private string _di014;
        
        private DateTime? _di015;
        
        private bool _di016;
        
        private bool _di017;
        
        private bool _di018;
        
        private bool _di019;
        
        private bool _di020;
        
        private bool _di021;
        
        private bool _di022;
        
        private bool _di023;
        
        private decimal _di024;
        
        private int _di025;
        
        private int _di026;
        
        private int _di027;
        
        private decimal _di028;
        
        private int _di029;
        
        private int _di030;
        
        private int _di031;
        
        private decimal _di032;
        
        private int _di033;
        
        private int _di034;
        
        private int _di035;
        
        private string _di036;
        
        private string _di037;
        
        private string _di038;
        
        private string _di039;
        
        private string _di040;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string DI001
        {
            get
            {
                return this._di001;
            }
            set
            {
                this._di001 = value;
            }
        }

        /// <summary>
        /// 流水号
        /// </summary>

        public string DI002
        {
            get
            {
                return this._di002;
            }
            set
            {
                this._di002 = value;
            }
        }

        /// <summary>
        /// 品名
        /// </summary>

        public string DI003
        {
            get
            {
                return this._di003;
            }
            set
            {
                this._di003 = value;
            }
        }

        /// <summary>
        /// 货号
        /// </summary>

        public string DI004
        {
            get
            {
                return this._di004;
            }
            set
            {
                this._di004 = value;
            }
        }

        /// <summary>
        /// 产品数量
        /// </summary>

        public int DI005
        {
            get
            {
                return this._di005;
            }
            set
            {
                this._di005 = value;
            }
        }

        /// <summary>
        /// 目的国
        /// </summary>

        public string DI006
        {
            get
            {
                return this._di006;
            }
            set
            {
                this._di006 = value;
            }
        }

        /// <summary>
        /// 年龄段
        /// </summary>
        public string DI007
        {
            get
            {
                return this._di007;
            }
            set
            {
                this._di007 = value;
            }
        }

        /// <summary>
        /// 抽检数量
        /// </summary>

        public int DI008
        {
            get
            {
                return this._di008;
            }
            set
            {
                this._di008 = value;
            }
        }

        /// <summary>
        /// 计划包装时间
        /// </summary>

        public DateTime? DI009
        {
            get
            {
                return this._di009;
            }
            set
            {
                this._di009 = value;
            }
        }

        /// <summary>
        /// 应出货时间
        /// </summary>

        public DateTime? DI010
        {
            get
            {
                return this._di010;
            }
            set
            {
                this._di010 = value;
            }
        }

        /// <summary>
        /// 报检人
        /// </summary>

        public string DI011
        {
            get
            {
                return this._di011;
            }
            set
            {
                this._di011 = value;
            }
        }

        /// <summary>
        /// 报检时间
        /// </summary>

        public DateTime? DI012
        {
            get
            {
                return this._di012;
            }
            set
            {
                this._di012 = value;
            }
        }

        /// <summary>
        /// 审核确定时间
        /// </summary>

        public DateTime? DI013
        {
            get
            {
                return this._di013;
            }
            set
            {
                this._di013 = value;
            }
        }

        /// <summary>
        /// 审核人
        /// </summary>

        public string DI014
        {
            get
            {
                return this._di014;
            }
            set
            {
                this._di014 = value;
            }
        }

        /// <summary>
        /// 终检时间
        /// </summary>

        public DateTime? DI015
        {
            get
            {
                return this._di015;
            }
            set
            {
                this._di015 = value;
            }
        }

        /// <summary>
        /// 检验类别第一次
        /// </summary>

        public bool DI016
        {
            get
            {
                return this._di016;
            }
            set
            {
                this._di016 = value;
            }
        }

        /// <summary>
        /// 检验类别第二次
        /// </summary>

        public bool DI017
        {
            get
            {
                return this._di017;
            }
            set
            {
                this._di017 = value;
            }
        }

        /// <summary>
        /// 合同有
        /// </summary>

        public bool DI018
        {
            get
            {
                return this._di018;
            }
            set
            {
                this._di018 = value;
            }
        }

        /// <summary>
        /// 合同无
        /// </summary>

        public bool DI019
        {
            get
            {
                return this._di019;
            }
            set
            {
                this._di019 = value;
            }
        }

        /// <summary>
        /// 样品有
        /// </summary>

        public bool DI020
        {
            get
            {
                return this._di020;
            }
            set
            {
                this._di020 = value;
            }
        }

        /// <summary>
        /// 样品无
        /// </summary>

        public bool DI021
        {
            get
            {
                return this._di021;
            }
            set
            {
                this._di021 = value;
            }
        }

        /// <summary>
        /// 最终检验通过
        /// </summary>

        public bool DI022
        {
            get
            {
                return this._di022;
            }
            set
            {
                this._di022 = value;
            }
        }

        /// <summary>
        /// 最终检验不通过
        /// </summary>

        public bool DI023
        {
            get
            {
                return this._di023;
            }
            set
            {
                this._di023 = value;
            }
        }

        /// <summary>
        /// 极严重缺陷AQL
        /// </summary>

        public decimal DI024
        {
            get
            {
                return this._di024;
            }
            set
            {
                this._di024 = value;
            }
        }

        /// <summary>
        /// 极严重允许数
        /// </summary>

        public int DI025
        {
            get
            {
                return this._di025;
            }
            set
            {
                this._di025 = value;
            }
        }

        /// <summary>
        /// 极严重拒收数
        /// </summary>

        public int DI026
        {
            get
            {
                return this._di026;
            }
            set
            {
                this._di026 = value;
            }
        }

        /// <summary>
        /// 极严重检验结果
        /// </summary>

        public int DI027
        {
            get
            {
                return this._di027;
            }
            set
            {
                this._di027 = value;
            }
        }

        /// <summary>
        /// 严重缺陷AQL
        /// </summary>

        public decimal DI028
        {
            get
            {
                return this._di028;
            }
            set
            {
                this._di028 = value;
            }
        }

        /// <summary>
        /// 严重缺陷允许数
        /// </summary>

        public int DI029
        {
            get
            {
                return this._di029;
            }
            set
            {
                this._di029 = value;
            }
        }

        /// <summary>
        /// 严重缺陷拒收数
        /// </summary>

        public int DI030
        {
            get
            {
                return this._di030;
            }
            set
            {
                this._di030 = value;
            }
        }

        /// <summary>
        /// 严重缺陷检验结果
        /// </summary>

        public int DI031
        {
            get
            {
                return this._di031;
            }
            set
            {
                this._di031 = value;
            }
        }

        /// <summary>
        /// 轻微缺陷AQL
        /// </summary>

        public decimal DI032
        {
            get
            {
                return this._di032;
            }
            set
            {
                this._di032 = value;
            }
        }

        /// <summary>
        /// 轻微缺陷允许数
        /// </summary>

        public int DI033
        {
            get
            {
                return this._di033;
            }
            set
            {
                this._di033 = value;
            }
        }

        /// <summary>
        /// 轻微缺陷拒收数
        /// </summary>

        public int DI034
        {
            get
            {
                return this._di034;
            }
            set
            {
                this._di034 = value;
            }
        }

        /// <summary>
        /// 轻微缺陷检验结果
        /// </summary>

        public int DI035
        {
            get
            {
                return this._di035;
            }
            set
            {
                this._di035 = value;
            }
        }
        
        // 
        public string DI036
        {
            get
            {
                return this._di036;
            }
            set
            {
                this._di036 = value;
            }
        }
        
        // 
        public string DI037
        {
            get
            {
                return this._di037;
            }
            set
            {
                this._di037 = value;
            }
        }
        
        // 
        public string DI038
        {
            get
            {
                return this._di038;
            }
            set
            {
                this._di038 = value;
            }
        }
        
        // 
        public string DI039
        {
            get
            {
                return this._di039;
            }
            set
            {
                this._di039 = value;
            }
        }
        
        // 
        public string DI040
        {
            get
            {
                return this._di040;
            }
            set
            {
                this._di040 = value;
            }
        }
    }
}
