//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class QualityFinalInspsctionDJEntity
    {
        
        private int _idx;
        
        private string _dj001;
        
        private string _dj002;
        
        private string _dj003;
        
        private string _dj004;
        
        private string _dj005;
        
        private string _dj006;
        
        private DateTime? _dj007;
        
        private int _dj008;
        
        private string _dj009;
        
        private string _dj010;
        
        private string _dj011;
        
        private string _dj012;
        
        private string _dj013;
        
        private string _dj014;
        
        private string _dj015;
        
        private string _dj016;
        
        private string _dj017;
        
        private string _dj018;
        
        private string _dj019;
        
        private string _dj020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string DJ001
        {
            get
            {
                return this._dj001;
            }
            set
            {
                this._dj001 = value;
            }
        }

        /// <summary>
        /// 检验项目
        /// </summary>

        public string DJ002
        {
            get
            {
                return this._dj002;
            }
            set
            {
                this._dj002 = value;
            }
        }

        /// <summary>
        /// 检验项目
        /// </summary>

        public string DJ003
        {
            get
            {
                return this._dj003;
            }
            set
            {
                this._dj003 = value;
            }
        }

        /// <summary>
        /// 质量要求
        /// </summary>

        public string DJ004
        {
            get
            {
                return this._dj004;
            }
            set
            {
                this._dj004 = value;
            }
        }

        /// <summary>
        /// 检验记录
        /// </summary>

        public string DJ005
        {
            get
            {
                return this._dj005;
            }
            set
            {
                this._dj005 = value;
            }
        }

        /// <summary>
        /// 签名
        /// </summary>

        public string DJ006
        {
            get
            {
                return this._dj006;
            }
            set
            {
                this._dj006 = value;
            }
        }
        
        /// <summary>
        /// 日期
        /// </summary>
                 
        public DateTime? DJ007
        {
            get
            {
                return this._dj007;
            }
            set
            {
                this._dj007 = value;
            }
        }

        /// <summary>
        /// 检验结果
        /// </summary>

        public int DJ008
        {
            get
            {
                return this._dj008;
            }
            set
            {
                this._dj008 = value;
            }
        }
        
        // 
        public string DJ009
        {
            get
            {
                return this._dj009;
            }
            set
            {
                this._dj009 = value;
            }
        }
        
        // 
        public string DJ010
        {
            get
            {
                return this._dj010;
            }
            set
            {
                this._dj010 = value;
            }
        }
        
        // 
        public string DJ011
        {
            get
            {
                return this._dj011;
            }
            set
            {
                this._dj011 = value;
            }
        }
        
        // 
        public string DJ012
        {
            get
            {
                return this._dj012;
            }
            set
            {
                this._dj012 = value;
            }
        }
        
        // 
        public string DJ013
        {
            get
            {
                return this._dj013;
            }
            set
            {
                this._dj013 = value;
            }
        }
        
        // 
        public string DJ014
        {
            get
            {
                return this._dj014;
            }
            set
            {
                this._dj014 = value;
            }
        }
        
        // 
        public string DJ015
        {
            get
            {
                return this._dj015;
            }
            set
            {
                this._dj015 = value;
            }
        }
        
        // 
        public string DJ016
        {
            get
            {
                return this._dj016;
            }
            set
            {
                this._dj016 = value;
            }
        }
        
        // 
        public string DJ017
        {
            get
            {
                return this._dj017;
            }
            set
            {
                this._dj017 = value;
            }
        }
        
        // 
        public string DJ018
        {
            get
            {
                return this._dj018;
            }
            set
            {
                this._dj018 = value;
            }
        }
        
        // 
        public string DJ019
        {
            get
            {
                return this._dj019;
            }
            set
            {
                this._dj019 = value;
            }
        }
        
        // 
        public string DJ020
        {
            get
            {
                return this._dj020;
            }
            set
            {
                this._dj020 = value;
            }
        }
    }
}
