//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class SafetyManegerAndControlDDEntity
    {
        
        private int _idx;
        
        private string _dd001;
        
        private DateTime? _dd002;
        
        private string _dd003;
        
        private string _dd004;
        
        private string _dd005;
        
        private string _dd006;
        
        private string _dd007;
        
        private string _dd008;
        
        private int _dd009;
        
        private string _dd010;
        
        private string _dd011;
        
        private string _dd012;
        
        private string _dd013;
        
        private bool _dd014;
        
        private bool _dd015;
        
        private bool _dd016;
        
        private bool _dd017;
        
        private bool _dd018;
        
        private bool _dd019;
        
        private bool _dd020;
        
        private bool _dd021;
        
        private bool _dd022;
        
        private int _dd023;
        
        private string _dd024;
        
        private string _dd025;
        
        private string _dd026;
        
        private string _dd027;
        
        private string _dd028;
        
        private string _dd029;
        
        private string _dd030;
        
        private string _dd031;
        
        private string _dd032;
        
        private string _dd033;
        
        private string _dd034;
        
        private string _dd035;
        
        private string _dd036;
        
        private string _dd037;
        
        private string _dd038;
        
        private string _dd039;
        
        private string _dd040;
        
        private string _dd041;
        
        private string _dd042;
        
        private string _dd043;
        
        private string _dd044;
        
        private string _dd045;
        
        private string _dd046;
        
        private string _dd047;
        
        private string _dd048;
        
        private string _dd049;
        
        private string _dd050;
        
        private string _dd051;
        
        private string _dd052;
        
        private string _dd053;
        
        private string _dd054;
        
        private string _dd055;
        
        private string _dd056;
        
        private string _dd057;
        
        private string _dd058;
        
        private string _dd059;
        
        private string _dd060;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string DD001
        {
            get
            {
                return this._dd001;
            }
            set
            {
                this._dd001 = value;
            }
        }

        /// <summary>
        /// 送测日期
        /// </summary>

        public DateTime? DD002
        {
            get
            {
                return this._dd002;
            }
            set
            {
                this._dd002 = value;
            }
        }

        /// <summary>
        /// 工艺名称
        /// </summary>

        public string DD003
        {
            get
            {
                return this._dd003;
            }
            set
            {
                this._dd003 = value;
            }
        }

        /// <summary>
        /// 零件名称
        /// </summary>

        public string DD004
        {
            get
            {
                return this._dd004;
            }
            set
            {
                this._dd004 = value;
            }
        }

        /// <summary>
        /// 化学品材料名称
        /// </summary>

        public string DD005
        {
            get
            {
                return this._dd005;
            }
            set
            {
                this._dd005 = value;
            }
        }

        /// <summary>
        /// 品牌
        /// </summary>

        public string DD006
        {
            get
            {
                return this._dd006;
            }
            set
            {
                this._dd006 = value;
            }
        }

        /// <summary>
        /// 色名(号)
        /// </summary>

        public string DD007
        {
            get
            {
                return this._dd007;
            }
            set
            {
                this._dd007 = value;
            }
        }

        /// <summary>
        /// 配剂名称
        /// </summary>

        public string DD008
        {
            get
            {
                return this._dd008;
            }
            set
            {
                this._dd008 = value;
            }
        }

        /// <summary>
        /// 送测数量
        /// </summary>

        public int DD009
        {
            get
            {
                return this._dd009;
            }
            set
            {
                this._dd009 = value;
            }
        }

        /// <summary>
        /// 批次号
        /// </summary>

        public string DD010
        {
            get
            {
                return this._dd010;
            }
            set
            {
                this._dd010 = value;
            }
        }

        /// <summary>
        /// 收发责任人
        /// </summary>

        public string DD011
        {
            get
            {
                return this._dd011;
            }
            set
            {
                this._dd011 = value;
            }
        }

        /// <summary>
        /// 生产责任人
        /// </summary>

        public string DD012
        {
            get
            {
                return this._dd012;
            }
            set
            {
                this._dd012 = value;
            }
        }

        /// <summary>
        /// 漆料色板
        /// </summary>

        public string DD013
        {
            get
            {
                return this._dd013;
            }
            set
            {
                this._dd013 = value;
            }
        }

        /// <summary>
        /// 样品
        /// </summary>

        public bool DD014
        {
            get
            {
                return this._dd014;
            }
            set
            {
                this._dd014 = value;
            }
        }

        /// <summary>
        /// 试产样品
        /// </summary>

        public bool DD015
        {
            get
            {
                return this._dd015;
            }
            set
            {
                this._dd015 = value;
            }
        }

        /// <summary>
        /// 量产到齐数量kg
        /// </summary>

        public bool DD016
        {
            get
            {
                return this._dd016;
            }
            set
            {
                this._dd016 = value;
            }
        }

        /// <summary>
        /// 厂购 或委购
        /// </summary>

        public bool DD017
        {
            get
            {
                return this._dd017;
            }
            set
            {
                this._dd017 = value;
            }
        }

        /// <summary>
        /// 漆料色板工艺
        /// </summary>

        public bool DD018
        {
            get
            {
                return this._dd018;
            }
            set
            {
                this._dd018 = value;
            }
        }

        /// <summary>
        /// 样品工艺
        /// </summary>

        public bool DD019
        {
            get
            {
                return this._dd019;
            }
            set
            {
                this._dd019 = value;
            }
        }

        /// <summary>
        /// 试产样品工艺
        /// </summary>

        public bool DD020
        {
            get
            {
                return this._dd020;
            }
            set
            {
                this._dd020 = value;
            }
        }

        /// <summary>
        /// 量产部件工艺
        /// </summary>

        public bool DD021
        {
            get
            {
                return this._dd021;
            }
            set
            {
                this._dd021 = value;
            }
        }

        /// <summary>
        /// 量产整套工艺
        /// </summary>

        public bool DD022
        {
            get
            {
                return this._dd022;
            }
            set
            {
                this._dd022 = value;
            }
        }

        /// <summary>
        /// 送测 次数
        /// </summary>

        public int DD023
        {
            get
            {
                return this._dd023;
            }
            set
            {
                this._dd023 = value;
            }
        }

        /// <summary>
        /// 被测  项号
        /// </summary>

        public string DD024
        {
            get
            {
                return this._dd024;
            }
            set
            {
                this._dd024 = value;
            }
        }

        /// <summary>
        /// 数值或结论
        /// </summary>

        public string DD025
        {
            get
            {
                return this._dd025;
            }
            set
            {
                this._dd025 = value;
            }
        }

        /// <summary>
        /// 被测项号
        /// </summary>

        public string DD026
        {
            get
            {
                return this._dd026;
            }
            set
            {
                this._dd026 = value;
            }
        }

        /// <summary>
        /// 数值或结论
        /// </summary>

        public string DD027
        {
            get
            {
                return this._dd027;
            }
            set
            {
                this._dd027 = value;
            }
        }

        /// <summary>
        /// 被测 项号
        /// </summary>

        public string DD028
        {
            get
            {
                return this._dd028;
            }
            set
            {
                this._dd028 = value;
            }
        }

        /// <summary>
        /// 数值或结论
        /// </summary>

        public string DD029
        {
            get
            {
                return this._dd029;
            }
            set
            {
                this._dd029 = value;
            }
        }

        /// <summary>
        /// 被测项号
        /// </summary>

        public string DD030
        {
            get
            {
                return this._dd030;
            }
            set
            {
                this._dd030 = value;
            }
        }

        /// <summary>
        /// 数值或结论
        /// </summary>

        public string DD031
        {
            get
            {
                return this._dd031;
            }
            set
            {
                this._dd031 = value;
            }
        }

        /// <summary>
        /// 被测项号
        /// </summary>

        public string DD032
        {
            get
            {
                return this._dd032;
            }
            set
            {
                this._dd032 = value;
            }
        }

        /// <summary>
        /// 数值或结论
        /// </summary>

        public string DD033
        {
            get
            {
                return this._dd033;
            }
            set
            {
                this._dd033 = value;
            }
        }

        /// <summary>
        /// 检测机构
        /// </summary>

        public string DD034
        {
            get
            {
                return this._dd034;
            }
            set
            {
                this._dd034 = value;
            }
        }

        /// <summary>
        /// 吐液测试结果
        /// </summary>

        public string DD035
        {
            get
            {
                return this._dd035;
            }
            set
            {
                this._dd035 = value;
            }
        }

        /// <summary>
        /// 汗液测结果
        /// </summary>

        public string DD036
        {
            get
            {
                return this._dd036;
            }
            set
            {
                this._dd036 = value;
            }
        }

        /// <summary>
        /// 剥入测试结果
        /// </summary>

        public string DD037
        {
            get
            {
                return this._dd037;
            }
            set
            {
                this._dd037 = value;
            }
        }

        /// <summary>
        /// 浸泡 测试结果
        /// </summary>

        public string DD038
        {
            get
            {
                return this._dd038;
            }
            set
            {
                this._dd038 = value;
            }
        }

        /// <summary>
        /// 耐温＞60°测试抗粘结果
        /// </summary>

        public string DD039
        {
            get
            {
                return this._dd039;
            }
            set
            {
                this._dd039 = value;
            }
        }

        /// <summary>
        /// 抗冻剥落开裂结果
        /// </summary>

        public string DD040
        {
            get
            {
                return this._dd040;
            }
            set
            {
                this._dd040 = value;
            }
        }

        /// <summary>
        /// 染色色牢度测结果
        /// </summary>

        public string DD041
        {
            get
            {
                return this._dd041;
            }
            set
            {
                this._dd041 = value;
            }
        }

        /// <summary>
        /// 色差 校对结果
        /// </summary>

        public string DD042
        {
            get
            {
                return this._dd042;
            }
            set
            {
                this._dd042 = value;
            }
        }

        /// <summary>
        /// 亮亚度校对
        /// </summary>

        public string DD043
        {
            get
            {
                return this._dd043;
            }
            set
            {
                this._dd043 = value;
            }
        }

        /// <summary>
        /// 防锈盐务测试结果
        /// </summary>

        public string DD044
        {
            get
            {
                return this._dd044;
            }
            set
            {
                this._dd044 = value;
            }
        }

        /// <summary>
        /// 防霉烂 测试结果
        /// </summary>

        public string DD045
        {
            get
            {
                return this._dd045;
            }
            set
            {
                this._dd045 = value;
            }
        }

        /// <summary>
        /// 绳长 测量
        /// </summary>

        public string DD046
        {
            get
            {
                return this._dd046;
            }
            set
            {
                this._dd046 = value;
            }
        }

        /// <summary>
        /// 拉力测试
        /// </summary>

        public string DD047
        {
            get
            {
                return this._dd047;
            }
            set
            {
                this._dd047 = value;
            }
        }

        /// <summary>
        /// 扭力测试
        /// </summary>

        public string DD048
        {
            get
            {
                return this._dd048;
            }
            set
            {
                this._dd048 = value;
            }
        }

        /// <summary>
        /// 跌落 测试
        /// </summary>

        public string DD049
        {
            get
            {
                return this._dd049;
            }
            set
            {
                this._dd049 = value;
            }
        }

        /// <summary>
        /// 利边尖端测试
        /// </summary>

        public string DD050
        {
            get
            {
                return this._dd050;
            }
            set
            {
                this._dd050 = value;
            }
        }

        /// <summary>
        /// 冲击测试
        /// </summary>

        public string DD051
        {
            get
            {
                return this._dd051;
            }
            set
            {
                this._dd051 = value;
            }
        }

        /// <summary>
        /// 功能结构测试
        /// </summary>

        public string DD052
        {
            get
            {
                return this._dd052;
            }
            set
            {
                this._dd052 = value;
            }
        }

        /// <summary>
        /// 外观标准确认
        /// </summary>

        public string DD053
        {
            get
            {
                return this._dd053;
            }
            set
            {
                this._dd053 = value;
            }
        }

        /// <summary>
        /// 胶水牢度
        /// </summary>

        public string DD054
        {
            get
            {
                return this._dd054;
            }
            set
            {
                this._dd054 = value;
            }
        }

        /// <summary>
        /// A模板测试
        /// </summary>

        public string DD055
        {
            get
            {
                return this._dd055;
            }
            set
            {
                this._dd055 = value;
            }
        }

        /// <summary>
        /// B模板测试
        /// </summary>

        public string DD056
        {
            get
            {
                return this._dd056;
            }
            set
            {
                this._dd056 = value;
            }
        }
        
        // 
        public string DD057
        {
            get
            {
                return this._dd057;
            }
            set
            {
                this._dd057 = value;
            }
        }
        
        // 
        public string DD058
        {
            get
            {
                return this._dd058;
            }
            set
            {
                this._dd058 = value;
            }
        }
        
        // 
        public string DD059
        {
            get
            {
                return this._dd059;
            }
            set
            {
                this._dd059 = value;
            }
        }
        
        // 
        public string DD060
        {
            get
            {
                return this._dd060;
            }
            set
            {
                this._dd060 = value;
            }
        }
    }
}
