//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class SafetyManegerAndControlDCEntity
    {
        
        private int _idx;
        
        private string _dc001;
        
        private string _dc002;
        
        private string _dc003;
        
        private string _dc004;
        
        private int? _dc005;
        
        private string _dc006;
        
        private string _dc007;
        
        private DateTime? _dc008;
        
        private string _dc009;
        
        private string _dc010;
        
        private string _dc011;
        
        private string _dc012;
        
        private string _dc013;
        
        private string _dc014;

        private bool _dc015;
        private bool _dc016;
        private bool _dc017;
        private bool _dc018;
        private bool _dc019;
        private bool _dc020;
        private bool _dc021;
        private bool _dc022;
        private bool _dc023;
        private bool _dc024;
        private bool _dc025;
        private bool _dc026;
        private bool _dc027;
        private bool _dc028;
        private bool _dc029;
        private bool _dc030;
        private bool _dc031;
        private bool _dc032;
        private string _dc033;
        private string _dc034;
        private string _dc035;
        private string _dc036;
        private string _dc037;

        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string DC001
        {
            get
            {
                return this._dc001;
            }
            set
            {
                this._dc001 = value;
            }
        }

        /// <summary>
        /// 产品名称
        /// </summary>

        public string DC002
        {
            get
            {
                return this._dc002;
            }
            set
            {
                this._dc002 = value;
            }
        }

        /// <summary>
        /// 货号
        /// </summary>

        public string DC003
        {
            get
            {
                return this._dc003;
            }
            set
            {
                this._dc003 = value;
            }
        }

        /// <summary>
        /// 流水号
        /// </summary>

        public string DC004
        {
            get
            {
                return this._dc004;
            }
            set
            {
                this._dc004 = value;
            }
        }

        /// <summary>
        /// 产品数量
        /// </summary>

        public int? DC005
        {
            get
            {
                return this._dc005;
            }
            set
            {
                this._dc005 = value;
            }
        }

        /// <summary>
        /// 年龄段
        /// </summary>

        public string DC006
        {
            get
            {
                return this._dc006;
            }
            set
            {
                this._dc006 = value;
            }
        }

        /// <summary>
        /// 输入国
        /// </summary>

        public string DC007
        {
            get
            {
                return this._dc007;
            }
            set
            {
                this._dc007 = value;
            }
        }

        /// <summary>
        /// 填表日期
        /// </summary>

        public DateTime? DC008
        {
            get
            {
                return this._dc008;
            }
            set
            {
                this._dc008 = value;
            }
        }

        /// <summary>
        /// 管控责任人
        /// </summary>

        public string DC009
        {
            get
            {
                return this._dc009;
            }
            set
            {
                this._dc009 = value;
            }
        }

        /// <summary>
        /// 审核责任人
        /// </summary>

        public string DC010
        {
            get
            {
                return this._dc010;
            }
            set
            {
                this._dc010 = value;
            }
        }

        /// <summary>
        /// 生产监管人
        /// </summary>

        public string DC011
        {
            get
            {
                return this._dc011;
            }
            set
            {
                this._dc011 = value;
            }
        }

        /// <summary>
        /// 批准责任人
        /// </summary>

        public string DC012
        {
            get
            {
                return this._dc012;
            }
            set
            {
                this._dc012 = value;
            }
        }

        /// <summary>
        /// 生产责任人
        /// </summary>

        public string DC013
        {
            get
            {
                return this._dc013;
            }
            set
            {
                this._dc013 = value;
            }
        }

        /// <summary>
        /// 特殊限制要求说明
        /// </summary>

        public string DC014
        {
            get
            {
                return this._dc014;
            }
            set
            {
                this._dc014 = value;
            }
        }

        /// <summary>
        /// (1)一类限量
        /// </summary>
        public bool DC015
        {
            set
            {
                _dc015 = value;
            }
            get
            {
                return _dc015;
            }
        }
        /// <summary>
        /// (2)二类限量
        /// </summary>
        public bool DC016
        {
            set
            {
                _dc016 = value;
            }
            get
            {
                return _dc016;
            }
        }
        /// <summary>
        /// (3)11项
        /// </summary>
        public bool DC017
        {
            set
            {
                _dc017 = value;
            }
            get
            {
                return _dc017;
            }
        }
        /// <summary>
        /// (4)欧标 限量
        /// </summary>
        public bool DC018
        {
            set
            {
                _dc018 = value;
            }
            get
            {
                return _dc018;
            }
        }
        /// <summary>
        /// (5)美标限量
        /// </summary>
        public bool DC019
        {
            set
            {
                _dc019 = value;
            }
            get
            {
                return _dc019;
            }
        }
        /// <summary>
        /// (6)加拿大
        /// </summary>
        public bool DC020
        {
            set
            {
                _dc020 = value;
            }
            get
            {
                return _dc020;
            }
        }
        /// <summary>
        /// (7)日本
        /// </summary>
        public bool DC021
        {
            set
            {
                _dc021 = value;
            }
            get
            {
                return _dc021;
            }
        }
        /// <summary>
        /// (8)3种含量
        /// </summary>
        public bool DC022
        {
            set
            {
                _dc022 = value;
            }
            get
            {
                return _dc022;
            }
        }
        /// <summary>
        /// (9)6种含量
        /// </summary>
        public bool DC023
        {
            set
            {
                _dc023 = value;
            }
            get
            {
                return _dc023;
            }
        }
        /// <summary>
        /// (10)15种含量
        /// </summary>
        public bool DC024
        {
            set
            {
                _dc024 = value;
            }
            get
            {
                return _dc024;
            }
        }
        /// <summary>
        /// (11)限量值
        /// </summary>
        public bool DC025
        {
            set
            {
                _dc025 = value;
            }
            get
            {
                return _dc025;
            }
        }
        /// <summary>
        /// (12)E0级
        /// </summary>
        public bool DC026
        {
            set
            {
                _dc026 = value;
            }
            get
            {
                return _dc026;
            }
        }
        /// <summary>
        /// (13)E1级
        /// </summary>
        public bool DC027
        {
            set
            {
                _dc027 = value;
            }
            get
            {
                return _dc027;
            }
        }
        /// <summary>
        /// (14)限量值
        /// </summary>
        public bool DC028
        {
            set
            {
                _dc028 = value;
            }
            get
            {
                return _dc028;
            }
        }
        /// <summary>
        /// (15)(总)每种限量
        /// </summary>
        public bool DC029
        {
            set
            {
                _dc029 = value;
            }
            get
            {
                return _dc029;
            }
        }
        /// <summary>
        /// (16)限量值
        /// </summary>
        public bool DC030
        {
            set
            {
                _dc030 = value;
            }
            get
            {
                return _dc030;
            }
        }
        /// <summary>
        /// (17)4项总和
        /// </summary>
        public bool DC031
        {
            set
            {
                _dc031 = value;
            }
            get
            {
                return _dc031;
            }
        }
        /// <summary>
        /// (18)限值
        /// </summary>
        public bool DC032
        {
            set
            {
                _dc032 = value;
            }
            get
            {
                return _dc032;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string DC033
        {
            set
            {
                _dc033 = value;
            }
            get
            {
                return _dc033;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string DC034
        {
            set
            {
                _dc034 = value;
            }
            get
            {
                return _dc034;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string DC035
        {
            set
            {
                _dc035 = value;
            }
            get
            {
                return _dc035;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string DC036
        {
            set
            {
                _dc036 = value;
            }
            get
            {
                return _dc036;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string DC037
        {
            set
            {
                _dc037 = value;
            }
            get
            {
                return _dc037;
            }
        }
    }
}
