//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class StandardAuditForCHEntity
    {
        
        private int _idx;
        
        private string _ch001;
        
        private string _ch002;
        
        private string _ch003;
        
        private string _ch004;
        
        private string _ch005;
        
        private string _ch006;
        
        private string _ch007;
        
        private string _ch008;
        
        private string _ch009;
        
        private string _ch010;
        
        private string _ch011;
        
        private string _ch012;
        
        private string _ch013;
        
        private string _ch014;
        
        private string _ch015;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string CH001
        {
            get
            {
                return this._ch001;
            }
            set
            {
                this._ch001 = value;
            }
        }

        /// <summary>
        /// 配件数
        /// </summary>

        public string CH002
        {
            get
            {
                return this._ch002;
            }
            set
            {
                this._ch002 = value;
            }
        }

        /// <summary>
        /// 填表人
        /// </summary>

        public string CH003
        {
            get
            {
                return this._ch003;
            }
            set
            {
                this._ch003 = value;
            }
        }

        /// <summary>
        /// 审核人
        /// </summary>

        public string CH004
        {
            get
            {
                return this._ch004;
            }
            set
            {
                this._ch004 = value;
            }
        }

        /// <summary>
        /// 报审人
        /// </summary>

        public string CH005
        {
            get
            {
                return this._ch005;
            }
            set
            {
                this._ch005 = value;
            }
        }

        /// <summary>
        /// 标准样签发人
        /// </summary>

        public string CH006
        {
            get
            {
                return this._ch006;
            }
            set
            {
                this._ch006 = value;
            }
        }
        
        // 
        public string CH007
        {
            get
            {
                return this._ch007;
            }
            set
            {
                this._ch007 = value;
            }
        }
        
        // 
        public string CH008
        {
            get
            {
                return this._ch008;
            }
            set
            {
                this._ch008 = value;
            }
        }
        
        // 
        public string CH009
        {
            get
            {
                return this._ch009;
            }
            set
            {
                this._ch009 = value;
            }
        }
        
        // 
        public string CH010
        {
            get
            {
                return this._ch010;
            }
            set
            {
                this._ch010 = value;
            }
        }
        
        // 
        public string CH011
        {
            get
            {
                return this._ch011;
            }
            set
            {
                this._ch011 = value;
            }
        }
        
        // 
        public string CH012
        {
            get
            {
                return this._ch012;
            }
            set
            {
                this._ch012 = value;
            }
        }
        
        // 
        public string CH013
        {
            get
            {
                return this._ch013;
            }
            set
            {
                this._ch013 = value;
            }
        }
        
        // 
        public string CH014
        {
            get
            {
                return this._ch014;
            }
            set
            {
                this._ch014 = value;
            }
        }
        
        // 
        public string CH015
        {
            get
            {
                return this._ch015;
            }
            set
            {
                this._ch015 = value;
            }
        }
    }
}
