//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class StandardAuditTreCGEntity
    {
        
        private int _idx;
        
        private string _cg001;
        
        private string _cg002;
        
        private string _cg003;
        
        private string _cg004;
        
        private DateTime? _cg005;
        
        private DateTime? _cg006;
        
        private string _cg007;
        
        private string _cg008;
        
        private string _cg009;
        
        private string _cg010;
        
        private string _cg011;
        
        private string _cg012;
        
        private string _cg022;
        
        private string _cg023;
        
        private string _cg013;
        
        private DateTime? _cg014;
        
        private string _cg015;
        
        private DateTime? _cg016;
        
        private string _cg017;
        
        private DateTime? _cg018;
        
        private string _cg019;
        
        private string _cg020;
        
        private string _cg021;
        
        private string _cg024;
        
        private string _cg025;
        
        private string _cg026;
        
        private string _cg027;
        
        private string _cg028;
        
        private string _cg029;
        
        private string _cg030;
        
        private string _cg031;
        
        private string _cg032;
        
        private string _cg033;
        
        private string _cg034;
        
        private string _cg035;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string CG001
        {
            get
            {
                return this._cg001;
            }
            set
            {
                this._cg001 = value;
            }
        }

        /// <summary>
        /// 部件名称
        /// </summary>

        public string CG002
        {
            get
            {
                return this._cg002;
            }
            set
            {
                this._cg002 = value;
            }
        }

        /// <summary>
        /// 工序名称
        /// </summary>

        public string CG003
        {
            get
            {
                return this._cg003;
            }
            set
            {
                this._cg003 = value;
            }
        }

        /// <summary>
        /// 审核依据
        /// </summary>

        public string CG004
        {
            get
            {
                return this._cg004;
            }
            set
            {
                this._cg004 = value;
            }
        }

        /// <summary>
        /// 审核日期
        /// </summary>

        public DateTime? CG005
        {
            get
            {
                return this._cg005;
            }
            set
            {
                this._cg005 = value;
            }
        }

        /// <summary>
        /// 生产日期
        /// </summary>

        public DateTime? CG006
        {
            get
            {
                return this._cg006;
            }
            set
            {
                this._cg006 = value;
            }
        }

        /// <summary>
        /// 图纸与靠坊公差尺寸核对
        /// </summary>

        public string CG007
        {
            get
            {
                return this._cg007;
            }
            set
            {
                this._cg007 = value;
            }
        }

        /// <summary>
        /// A量检具与靠坊尺寸公差核对
        /// </summary>

        public string CG008
        {
            get
            {
                return this._cg008;
            }
            set
            {
                this._cg008 = value;
            }
        }

        /// <summary>
        /// B量检具与靠坊尺寸公差核对
        /// </summary>

        public string CG009
        {
            get
            {
                return this._cg009;
            }
            set
            {
                this._cg009 = value;
            }
        }

        /// <summary>
        /// C量检具与靠坊尺寸公差核对
        /// </summary>

        public string CG010
        {
            get
            {
                return this._cg010;
            }
            set
            {
                this._cg010 = value;
            }
        }

        /// <summary>
        /// D量检具与靠坊尺寸公差核对
        /// </summary>

        public string CG011
        {
            get
            {
                return this._cg011;
            }
            set
            {
                this._cg011 = value;
            }
        }

        /// <summary>
        /// E量检具与靠坊尺寸公差核对
        /// </summary>

        public string CG012
        {
            get
            {
                return this._cg012;
            }
            set
            {
                this._cg012 = value;
            }
        }

        /// <summary>
        /// 配合件互配公差适合度审核
        /// </summary>

        public string CG022
        {
            get
            {
                return this._cg022;
            }
            set
            {
                this._cg022 = value;
            }
        }

        /// <summary>
        /// 部件所靠基准点合理审核
        /// </summary>

        public string CG023
        {
            get
            {
                return this._cg023;
            }
            set
            {
                this._cg023 = value;
            }
        }

        /// <summary>
        /// 工程人员
        /// </summary>

        public string CG013
        {
            get
            {
                return this._cg013;
            }
            set
            {
                this._cg013 = value;
            }
        }

        /// <summary>
        /// 工程人员日期
        /// </summary>

        public DateTime? CG014
        {
            get
            {
                return this._cg014;
            }
            set
            {
                this._cg014 = value;
            }
        }

        /// <summary>
        /// 车间经理
        /// </summary>

        public string CG015
        {
            get
            {
                return this._cg015;
            }
            set
            {
                this._cg015 = value;
            }
        }

        /// <summary>
        /// 车间经理日期
        /// </summary>

        public DateTime? CG016
        {
            get
            {
                return this._cg016;
            }
            set
            {
                this._cg016 = value;
            }
        }

        /// <summary>
        /// 动力组长
        /// </summary>

        public string CG017
        {
            get
            {
                return this._cg017;
            }
            set
            {
                this._cg017 = value;
            }
        }

        /// <summary>
        /// 动力组长
        /// </summary>

        public DateTime? CG018
        {
            get
            {
                return this._cg018;
            }
            set
            {
                this._cg018 = value;
            }
        }

        /// <summary>
        /// 对靠坊稳固及可操性审核
        /// </summary>

        public string CG019
        {
            get
            {
                return this._cg019;
            }
            set
            {
                this._cg019 = value;
            }
        }

        /// <summary>
        /// 操作人岗前培训及达标审核
        /// </summary>

        public string CG020
        {
            get
            {
                return this._cg020;
            }
            set
            {
                this._cg020 = value;
            }
        }

        /// <summary>
        /// 每次不合格下面打×并说明
        /// </summary>

        public string CG021
        {
            get
            {
                return this._cg021;
            }
            set
            {
                this._cg021 = value;
            }
        }
        
        // 
        public string CG024
        {
            get
            {
                return this._cg024;
            }
            set
            {
                this._cg024 = value;
            }
        }
        
        // 
        public string CG025
        {
            get
            {
                return this._cg025;
            }
            set
            {
                this._cg025 = value;
            }
        }
        
        // 
        public string CG026
        {
            get
            {
                return this._cg026;
            }
            set
            {
                this._cg026 = value;
            }
        }
        
        // 
        public string CG027
        {
            get
            {
                return this._cg027;
            }
            set
            {
                this._cg027 = value;
            }
        }
        
        // 
        public string CG028
        {
            get
            {
                return this._cg028;
            }
            set
            {
                this._cg028 = value;
            }
        }
        
        // 
        public string CG029
        {
            get
            {
                return this._cg029;
            }
            set
            {
                this._cg029 = value;
            }
        }
        
        // 
        public string CG030
        {
            get
            {
                return this._cg030;
            }
            set
            {
                this._cg030 = value;
            }
        }
        
        // 
        public string CG031
        {
            get
            {
                return this._cg031;
            }
            set
            {
                this._cg031 = value;
            }
        }
        
        // 
        public string CG032
        {
            get
            {
                return this._cg032;
            }
            set
            {
                this._cg032 = value;
            }
        }
        
        // 
        public string CG033
        {
            get
            {
                return this._cg033;
            }
            set
            {
                this._cg033 = value;
            }
        }
        
        // 
        public string CG034
        {
            get
            {
                return this._cg034;
            }
            set
            {
                this._cg034 = value;
            }
        }
        
        // 
        public string CG035
        {
            get
            {
                return this._cg035;
            }
            set
            {
                this._cg035 = value;
            }
        }
    }
}
