//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class StandardAuditOneCBEntity
    {
        
        private int _idx;
        
        private string _cb001;
        
        private string _cb002;
        
        private string _cb003;
        
        private string _cb004;
        
        private int _cb005;
        
        private string _cb006;
        
        private string _cb007;
        
        private string _cb008;
        
        private string _cb009;
        
        private string _cb010;
        
        private string _cb011;
        
        private string _cb012;
        
        private string _cb013;
        
        private string _cb014;
        
        private string _cb015;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string CB001
        {
            get
            {
                return this._cb001;
            }
            set
            {
                this._cb001 = value;
            }
        }

        /// <summary>
        /// 流水号
        /// </summary>

        public string CB002
        {
            get
            {
                return this._cb002;
            }
            set
            {
                this._cb002 = value;
            }
        }

        /// <summary>
        /// 产品名称
        /// </summary>

        public string CB003
        {
            get
            {
                return this._cb003;
            }
            set
            {
                this._cb003 = value;
            }
        }

        /// <summary>
        /// 货号
        /// </summary>

        public string CB004
        {
            get
            {
                return this._cb004;
            }
            set
            {
                this._cb004 = value;
            }
        }

        /// <summary>
        /// 产品数量
        /// </summary>

        public int CB005
        {
            get
            {
                return this._cb005;
            }
            set
            {
                this._cb005 = value;
            }
        }

        /// <summary>
        /// 色数
        /// </summary>

        public string CB006
        {
            get
            {
                return this._cb006;
            }
            set
            {
                this._cb006 = value;
            }
        }

        /// <summary>
        /// 填表人
        /// </summary>

        public string CB007
        {
            get
            {
                return this._cb007;
            }
            set
            {
                this._cb007 = value;
            }
        }

        /// <summary>
        /// 审核人
        /// </summary>

        public string CB008
        {
            get
            {
                return this._cb008;
            }
            set
            {
                this._cb008 = value;
            }
        }

        /// <summary>
        /// 报审人
        /// </summary>

        public string CB009
        {
            get
            {
                return this._cb009;
            }
            set
            {
                this._cb009 = value;
            }
        }

        /// <summary>
        /// 标准样签发人
        /// </summary>

        public string CB010
        {
            get
            {
                return this._cb010;
            }
            set
            {
                this._cb010 = value;
            }
        }
        
        // 
        public string CB011
        {
            get
            {
                return this._cb011;
            }
            set
            {
                this._cb011 = value;
            }
        }
        
        // 
        public string CB012
        {
            get
            {
                return this._cb012;
            }
            set
            {
                this._cb012 = value;
            }
        }
        
        // 
        public string CB013
        {
            get
            {
                return this._cb013;
            }
            set
            {
                this._cb013 = value;
            }
        }
        
        // 
        public string CB014
        {
            get
            {
                return this._cb014;
            }
            set
            {
                this._cb014 = value;
            }
        }
        
        // 
        public string CB015
        {
            get
            {
                return this._cb015;
            }
            set
            {
                this._cb015 = value;
            }
        }
    }
}
