//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class StandardAuditTreCFEntity
    {
        
        private int _idx;
        
        private string _cf001;
        
        private string _cf002;
        
        private string _cf003;
        
        private string _cf004;
        
        private int _cf005;
        
        private string _cf006;
        
        private string _cf007;
        
        private string _cf008;
        
        private string _cf009;
        
        private string _cf010;
        
        private string _cf011;
        
        private string _cf012;
        
        private string _cf013;
        
        private string _cf014;
        
        private string _cf015;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string CF001
        {
            get
            {
                return this._cf001;
            }
            set
            {
                this._cf001 = value;
            }
        }

        /// <summary>
        /// 流水号
        /// </summary>

        public string CF002
        {
            get
            {
                return this._cf002;
            }
            set
            {
                this._cf002 = value;
            }
        }

        /// <summary>
        /// 产品名称
        /// </summary>

        public string CF003
        {
            get
            {
                return this._cf003;
            }
            set
            {
                this._cf003 = value;
            }
        }

        /// <summary>
        /// 货号
        /// </summary>

        public string CF004
        {
            get
            {
                return this._cf004;
            }
            set
            {
                this._cf004 = value;
            }
        }

        /// <summary>
        /// 产品数量
        /// </summary>

        public int CF005
        {
            get
            {
                return this._cf005;
            }
            set
            {
                this._cf005 = value;
            }
        }

        /// <summary>
        /// 量检具数
        /// </summary>

        public string CF006
        {
            get
            {
                return this._cf006;
            }
            set
            {
                this._cf006 = value;
            }
        }

        /// <summary>
        /// 填表人
        /// </summary>

        public string CF007
        {
            get
            {
                return this._cf007;
            }
            set
            {
                this._cf007 = value;
            }
        }

        /// <summary>
        /// 审核人
        /// </summary>

        public string CF008
        {
            get
            {
                return this._cf008;
            }
            set
            {
                this._cf008 = value;
            }
        }

        /// <summary>
        /// 报审人
        /// </summary>

        public string CF009
        {
            get
            {
                return this._cf009;
            }
            set
            {
                this._cf009 = value;
            }
        }

        /// <summary>
        /// 量检具签发人
        /// </summary>

        public string CF010
        {
            get
            {
                return this._cf010;
            }
            set
            {
                this._cf010 = value;
            }
        }
        
        // 
        public string CF011
        {
            get
            {
                return this._cf011;
            }
            set
            {
                this._cf011 = value;
            }
        }
        
        // 
        public string CF012
        {
            get
            {
                return this._cf012;
            }
            set
            {
                this._cf012 = value;
            }
        }
        
        // 
        public string CF013
        {
            get
            {
                return this._cf013;
            }
            set
            {
                this._cf013 = value;
            }
        }
        
        // 
        public string CF014
        {
            get
            {
                return this._cf014;
            }
            set
            {
                this._cf014 = value;
            }
        }
        
        // 
        public string CF015
        {
            get
            {
                return this._cf015;
            }
            set
            {
                this._cf015 = value;
            }
        }
    }
}
