//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class StandardTestCLEntity
    {
        
        private int _idx;
        
        private int? _cl001;
        
        private int? _cl002;
        
        private int? _cl003;
        
        private int? _cl004;
        
        private int? _cl005;
        
        private int? _cl006;
        
        private int? _cl007;
        
        private string _cl008;
        
        private string _cl009;
        
        private string _cl010;
        
        private string _cl011;
        
        private string _cl012;
        
        private string _cl013;
        
        private string _cl014;
        
        private string _cl015;
        
        private string _cl016;
        
        private string _cl017;
        
        private string _cl018;
        
        private string _cl019;
        
        private string _cl020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 批量范围头
        /// </summary>

        public int? CL001
        {
            get
            {
                return this._cl001;
            }
            set
            {
                this._cl001 = value;
            }
        }

        /// <summary>
        /// 批量范围尾
        /// </summary>

        public int? CL002
        {
            get
            {
                return this._cl002;
            }
            set
            {
                this._cl002 = value;
            }
        }

        /// <summary>
        /// 抽检数
        /// </summary>

        public int? CL003
        {
            get
            {
                return this._cl003;
            }
            set
            {
                this._cl003 = value;
            }
        }

        /// <summary>
        /// 严重AQL允许
        /// </summary>

        public int? CL004
        {
            get
            {
                return this._cl004;
            }
            set
            {
                this._cl004 = value;
            }
        }

        /// <summary>
        /// 严重AQL拒收
        /// </summary>

        public int? CL005
        {
            get
            {
                return this._cl005;
            }
            set
            {
                this._cl005 = value;
            }
        }

        /// <summary>
        /// 轻度AQL允许
        /// </summary>

        public int? CL006
        {
            get
            {
                return this._cl006;
            }
            set
            {
                this._cl006 = value;
            }
        }

        /// <summary>
        /// 轻度AQL拒收
        /// </summary>

        public int? CL007
        {
            get
            {
                return this._cl007;
            }
            set
            {
                this._cl007 = value;
            }
        }
        
        // 
        public string CL008
        {
            get
            {
                return this._cl008;
            }
            set
            {
                this._cl008 = value;
            }
        }
        
        // 
        public string CL009
        {
            get
            {
                return this._cl009;
            }
            set
            {
                this._cl009 = value;
            }
        }
        
        // 
        public string CL010
        {
            get
            {
                return this._cl010;
            }
            set
            {
                this._cl010 = value;
            }
        }
        
        // 
        public string CL011
        {
            get
            {
                return this._cl011;
            }
            set
            {
                this._cl011 = value;
            }
        }
        
        // 
        public string CL012
        {
            get
            {
                return this._cl012;
            }
            set
            {
                this._cl012 = value;
            }
        }
        
        // 
        public string CL013
        {
            get
            {
                return this._cl013;
            }
            set
            {
                this._cl013 = value;
            }
        }
        
        // 
        public string CL014
        {
            get
            {
                return this._cl014;
            }
            set
            {
                this._cl014 = value;
            }
        }
        
        // 
        public string CL015
        {
            get
            {
                return this._cl015;
            }
            set
            {
                this._cl015 = value;
            }
        }
        
        // 
        public string CL016
        {
            get
            {
                return this._cl016;
            }
            set
            {
                this._cl016 = value;
            }
        }
        
        // 
        public string CL017
        {
            get
            {
                return this._cl017;
            }
            set
            {
                this._cl017 = value;
            }
        }
        
        // 
        public string CL018
        {
            get
            {
                return this._cl018;
            }
            set
            {
                this._cl018 = value;
            }
        }
        
        // 
        public string CL019
        {
            get
            {
                return this._cl019;
            }
            set
            {
                this._cl019 = value;
            }
        }
        
        // 
        public string CL020
        {
            get
            {
                return this._cl020;
            }
            set
            {
                this._cl020 = value;
            }
        }
    }
}
