//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class StandardAuditForCIEntity
    {
        
        private int _idx;
        
        private string _ci001;
        
        private string _ci002;
        
        private string _ci003;
        
        private string _ci004;
        
        private DateTime? _ci005;
        
        private DateTime? _ci006;
        
        private string _ci007;
        
        private string _ci008;
        
        private string _ci009;
        
        private string _ci010;
        
        private string _ci011;
        
        private string _ci012;
        
        private string _ci022;
        
        private string _ci023;
        
        private string _ci013;
        
        private DateTime? _ci014;
        
        private string _ci015;
        
        private DateTime? _ci016;
        
        private string _ci017;
        
        private DateTime? _ci018;
        
        private int? _ci019;
        
        private string _ci020;
        
        private string _ci021;
        
        private int? _ci024;
        
        private string _ci025;
        
        private string _ci026;
        
        private string _ci027;
        
        private string _ci028;
        
        private string _ci029;
        
        private string _ci030;
        
        private string _ci031;
        
        private string _ci032;
        
        private string _ci033;
        
        private string _ci034;
        
        private string _ci035;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string CI001
        {
            get
            {
                return this._ci001;
            }
            set
            {
                this._ci001 = value;
            }
        }

        /// <summary>
        /// 合同号
        /// </summary>

        public string CI002
        {
            get
            {
                return this._ci002;
            }
            set
            {
                this._ci002 = value;
            }
        }

        /// <summary>
        /// 产品名称
        /// </summary>

        public string CI003
        {
            get
            {
                return this._ci003;
            }
            set
            {
                this._ci003 = value;
            }
        }

        /// <summary>
        /// 货号
        /// </summary>

        public string CI004
        {
            get
            {
                return this._ci004;
            }
            set
            {
                this._ci004 = value;
            }
        }

        /// <summary>
        /// 审核日期
        /// </summary>

        public DateTime? CI005
        {
            get
            {
                return this._ci005;
            }
            set
            {
                this._ci005 = value;
            }
        }

        /// <summary>
        /// 包装日期
        /// </summary>

        public DateTime? CI006
        {
            get
            {
                return this._ci006;
            }
            set
            {
                this._ci006 = value;
            }
        }

        /// <summary>
        /// 包装功能防护
        /// </summary>

        public string CI007
        {
            get
            {
                return this._ci007;
            }
            set
            {
                this._ci007 = value;
            }
        }

        /// <summary>
        /// 包装规范
        /// </summary>

        public string CI008
        {
            get
            {
                return this._ci008;
            }
            set
            {
                this._ci008 = value;
            }
        }

        /// <summary>
        /// 配件数量
        /// </summary>

        public string CI009
        {
            get
            {
                return this._ci009;
            }
            set
            {
                this._ci009 = value;
            }
        }

        /// <summary>
        /// 各种标签和警告语
        /// </summary>

        public string CI010
        {
            get
            {
                return this._ci010;
            }
            set
            {
                this._ci010 = value;
            }
        }

        /// <summary>
        /// 喷码
        /// </summary>

        public string CI011
        {
            get
            {
                return this._ci011;
            }
            set
            {
                this._ci011 = value;
            }
        }

        /// <summary>
        /// 流水号
        /// </summary>

        public string CI012
        {
            get
            {
                return this._ci012;
            }
            set
            {
                this._ci012 = value;
            }
        }
        
        // 
        public string CI022
        {
            get
            {
                return this._ci022;
            }
            set
            {
                this._ci022 = value;
            }
        }
        
        // 
        public string CI023
        {
            get
            {
                return this._ci023;
            }
            set
            {
                this._ci023 = value;
            }
        }

        /// <summary>
        /// 工程人员
        /// </summary>

        public string CI013
        {
            get
            {
                return this._ci013;
            }
            set
            {
                this._ci013 = value;
            }
        }

        /// <summary>
        /// 工程人员日期
        /// </summary>

        public DateTime? CI014
        {
            get
            {
                return this._ci014;
            }
            set
            {
                this._ci014 = value;
            }
        }

        /// <summary>
        /// 包装组长
        /// </summary>

        public string CI015
        {
            get
            {
                return this._ci015;
            }
            set
            {
                this._ci015 = value;
            }
        }

        /// <summary>
        /// 包装组长日期
        /// </summary>

        public DateTime? CI016
        {
            get
            {
                return this._ci016;
            }
            set
            {
                this._ci016 = value;
            }
        }

        /// <summary>
        /// 业务员
        /// </summary>

        public string CI017
        {
            get
            {
                return this._ci017;
            }
            set
            {
                this._ci017 = value;
            }
        }

        /// <summary>
        /// 业务员日期
        /// </summary>

        public DateTime? CI018
        {
            get
            {
                return this._ci018;
            }
            set
            {
                this._ci018 = value;
            }
        }

        /// <summary>
        /// 产品数量
        /// </summary>

        public int? CI019
        {
            get
            {
                return this._ci019;
            }
            set
            {
                this._ci019 = value;
            }
        }

        /// <summary>
        /// 审核依据
        /// </summary>

        public string CI020
        {
            get
            {
                return this._ci020;
            }
            set
            {
                this._ci020 = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>

        public string CI021
        {
            get
            {
                return this._ci021;
            }
            set
            {
                this._ci021 = value;
            }
        }
        
        /// <summary>
        /// 配件数
        /// </summary>
                 
        public int? CI024
        {
            get
            {
                return this._ci024;
            }
            set
            {
                this._ci024 = value;
            }
        }
        
        // 
        public string CI025
        {
            get
            {
                return this._ci025;
            }
            set
            {
                this._ci025 = value;
            }
        }
        
        // 
        public string CI026
        {
            get
            {
                return this._ci026;
            }
            set
            {
                this._ci026 = value;
            }
        }
        
        // 
        public string CI027
        {
            get
            {
                return this._ci027;
            }
            set
            {
                this._ci027 = value;
            }
        }
        
        // 
        public string CI028
        {
            get
            {
                return this._ci028;
            }
            set
            {
                this._ci028 = value;
            }
        }
        
        // 
        public string CI029
        {
            get
            {
                return this._ci029;
            }
            set
            {
                this._ci029 = value;
            }
        }
        
        // 
        public string CI030
        {
            get
            {
                return this._ci030;
            }
            set
            {
                this._ci030 = value;
            }
        }
        
        // 
        public string CI031
        {
            get
            {
                return this._ci031;
            }
            set
            {
                this._ci031 = value;
            }
        }
        
        // 
        public string CI032
        {
            get
            {
                return this._ci032;
            }
            set
            {
                this._ci032 = value;
            }
        }
        
        // 
        public string CI033
        {
            get
            {
                return this._ci033;
            }
            set
            {
                this._ci033 = value;
            }
        }
        
        // 
        public string CI034
        {
            get
            {
                return this._ci034;
            }
            set
            {
                this._ci034 = value;
            }
        }
        
        // 
        public string CI035
        {
            get
            {
                return this._ci035;
            }
            set
            {
                this._ci035 = value;
            }
        }
    }
}
