//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class StandardAuditFivCJEntity
    {
        
        private int _idx;
        
        private string _cj001;
        
        private string _cj002;
        
        private string _cj003;
        
        private string _cj004;
        
        private int _cj005;
        
        private string _cj006;
        
        private string _cj007;
        
        private string _cj008;
        
        private string _cj009;
        
        private string _cj010;
        
        private string _cj011;
        
        private string _cj012;
        
        private string _cj013;
        
        private string _cj014;
        
        private string _cj015;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string CJ001
        {
            get
            {
                return this._cj001;
            }
            set
            {
                this._cj001 = value;
            }
        }

        /// <summary>
        /// 流水号
        /// </summary>

        public string CJ002
        {
            get
            {
                return this._cj002;
            }
            set
            {
                this._cj002 = value;
            }
        }

        /// <summary>
        /// 产品名称
        /// </summary>

        public string CJ003
        {
            get
            {
                return this._cj003;
            }
            set
            {
                this._cj003 = value;
            }
        }

        /// <summary>
        /// 货号
        /// </summary>

        public string CJ004
        {
            get
            {
                return this._cj004;
            }
            set
            {
                this._cj004 = value;
            }
        }

        /// <summary>
        /// 产品数量
        /// </summary>

        public int CJ005
        {
            get
            {
                return this._cj005;
            }
            set
            {
                this._cj005 = value;
            }
        }

        /// <summary>
        /// 量检具数
        /// </summary>

        public string CJ006
        {
            get
            {
                return this._cj006;
            }
            set
            {
                this._cj006 = value;
            }
        }

        /// <summary>
        /// 填表人
        /// </summary>

        public string CJ007
        {
            get
            {
                return this._cj007;
            }
            set
            {
                this._cj007 = value;
            }
        }

        /// <summary>
        /// 审核人
        /// </summary>

        public string CJ008
        {
            get
            {
                return this._cj008;
            }
            set
            {
                this._cj008 = value;
            }
        }

        /// <summary>
        /// 报审人
        /// </summary>

        public string CJ009
        {
            get
            {
                return this._cj009;
            }
            set
            {
                this._cj009 = value;
            }
        }

        /// <summary>
        /// 量检具签发人
        /// </summary>

        public string CJ010
        {
            get
            {
                return this._cj010;
            }
            set
            {
                this._cj010 = value;
            }
        }
        
        // 
        public string CJ011
        {
            get
            {
                return this._cj011;
            }
            set
            {
                this._cj011 = value;
            }
        }
        
        // 
        public string CJ012
        {
            get
            {
                return this._cj012;
            }
            set
            {
                this._cj012 = value;
            }
        }
        
        // 
        public string CJ013
        {
            get
            {
                return this._cj013;
            }
            set
            {
                this._cj013 = value;
            }
        }
        
        // 
        public string CJ014
        {
            get
            {
                return this._cj014;
            }
            set
            {
                this._cj014 = value;
            }
        }
        
        // 
        public string CJ015
        {
            get
            {
                return this._cj015;
            }
            set
            {
                this._cj015 = value;
            }
        }
    }
}
