//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class StandardAuditOneCCEntity
    {
        
        private int _idx;
        
        private string _cc001;
        
        private string _cc002;
        
        private string _cc003;
        
        private string _cc004;
        
        private DateTime? _cc005;
        
        private DateTime? _cc006;
        
        private string _cc007;
        
        private string _cc008;
        
        private string _cc009;
        
        private string _cc010;
        
        private string _cc011;
        
        private string _cc012;
        
        private string _cc013;
        
        private DateTime? _cc014;
        
        private string _cc015;
        
        private DateTime? _cc016;
        
        private string _cc017;
        
        private DateTime? _cc018;
        
        private string _cc019;
        
        private DateTime? _cc020;
        
        private string _cc021;
        
        private string _cc022;
        
        private string _cc023;
        
        private string _cc024;
        
        private string _cc025;
        
        private string _cc026;
        
        private string _cc027;
        
        private string _cc028;
        
        private string _cc029;
        
        private string _cc030;
        
        private string _cc031;
        
        private string _cc032;
        
        private string _cc033;
        
        private string _cc034;
        
        private string _cc035;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string CC001
        {
            get
            {
                return this._cc001;
            }
            set
            {
                this._cc001 = value;
            }
        }

        /// <summary>
        /// 审核依据
        /// </summary>

        public string CC002
        {
            get
            {
                return this._cc002;
            }
            set
            {
                this._cc002 = value;
            }
        }

        /// <summary>
        /// 部件名称
        /// </summary>

        public string CC003
        {
            get
            {
                return this._cc003;
            }
            set
            {
                this._cc003 = value;
            }
        }

        /// <summary>
        /// 
        ///  色名(号)
        /// </summary>
        public string CC004
        {
            get
            {
                return this._cc004;
            }
            set
            {
                this._cc004 = value;
            }
        }

        /// <summary>
        /// 
        /// 审核日期
        /// </summary>
        public DateTime? CC005
        {
            get
            {
                return this._cc005;
            }
            set
            {
                this._cc005 = value;
            }
        }

        /// <summary>
        /// 生产日期
        /// </summary>

        public DateTime? CC006
        {
            get
            {
                return this._cc006;
            }
            set
            {
                this._cc006 = value;
            }
        }

        /// <summary>
        /// 油漆品牌和批次审核
        /// </summary>

        public string CC007
        {
            get
            {
                return this._cc007;
            }
            set
            {
                this._cc007 = value;
            }
        }

        /// <summary>
        /// 调剂品牌和批次审核
        /// </summary>

        public string CC008
        {
            get
            {
                return this._cc008;
            }
            set
            {
                this._cc008 = value;
            }
        }

        /// <summary>
        /// 色转移.色牢度.剥落审核
        /// </summary>

        public string CC009
        {
            get
            {
                return this._cc009;
            }
            set
            {
                this._cc009 = value;
            }
        }

        /// <summary>
        /// 溶器及二次污染等符合审核
        /// </summary>

        public string CC010
        {
            get
            {
                return this._cc010;
            }
            set
            {
                this._cc010 = value;
            }
        }

        /// <summary>
        /// 色号与色板间的色差核对
        /// </summary>

        public string CC011
        {
            get
            {
                return this._cc011;
            }
            set
            {
                this._cc011 = value;
            }
        }

        /// <summary>
        /// 白坯光洁度符合性审核
        /// </summary>

        public string CC012
        {
            get
            {
                return this._cc012;
            }
            set
            {
                this._cc012 = value;
            }
        }

        /// <summary>
        /// 质检部
        /// </summary>

        public string CC013
        {
            get
            {
                return this._cc013;
            }
            set
            {
                this._cc013 = value;
            }
        }

        /// <summary>
        /// 质检部日期
        /// </summary>

        public DateTime? CC014
        {
            get
            {
                return this._cc014;
            }
            set
            {
                this._cc014 = value;
            }
        }

        /// <summary>
        /// 车间经理
        /// </summary>

        public string CC015
        {
            get
            {
                return this._cc015;
            }
            set
            {
                this._cc015 = value;
            }
        }

        /// <summary>
        /// 车间经理日期
        /// </summary>

        public DateTime? CC016
        {
            get
            {
                return this._cc016;
            }
            set
            {
                this._cc016 = value;
            }
        }

        /// <summary>
        /// 滚、喷、涂漆组长
        /// </summary>

        public string CC017
        {
            get
            {
                return this._cc017;
            }
            set
            {
                this._cc017 = value;
            }
        }

        /// <summary>
        /// 滚、喷、涂漆组长日期
        /// </summary>

        public DateTime? CC018
        {
            get
            {
                return this._cc018;
            }
            set
            {
                this._cc018 = value;
            }
        }

        /// <summary>
        /// 业务员
        /// </summary>

        public string CC019
        {
            get
            {
                return this._cc019;
            }
            set
            {
                this._cc019 = value;
            }
        }

        /// <summary>
        /// 业务员日期
        /// </summary>

        public DateTime? CC020
        {
            get
            {
                return this._cc020;
            }
            set
            {
                this._cc020 = value;
            }
        }

        /// <summary>
        /// 不良问题处理说明
        /// </summary>

        public string CC021
        {
            get
            {
                return this._cc021;
            }
            set
            {
                this._cc021 = value;
            }
        }
        
        // 
        public string CC022
        {
            get
            {
                return this._cc022;
            }
            set
            {
                this._cc022 = value;
            }
        }
        
        // 
        public string CC023
        {
            get
            {
                return this._cc023;
            }
            set
            {
                this._cc023 = value;
            }
        }
        
        // 
        public string CC024
        {
            get
            {
                return this._cc024;
            }
            set
            {
                this._cc024 = value;
            }
        }
        
        // 
        public string CC025
        {
            get
            {
                return this._cc025;
            }
            set
            {
                this._cc025 = value;
            }
        }
        
        // 
        public string CC026
        {
            get
            {
                return this._cc026;
            }
            set
            {
                this._cc026 = value;
            }
        }
        
        // 
        public string CC027
        {
            get
            {
                return this._cc027;
            }
            set
            {
                this._cc027 = value;
            }
        }
        
        // 
        public string CC028
        {
            get
            {
                return this._cc028;
            }
            set
            {
                this._cc028 = value;
            }
        }
        
        // 
        public string CC029
        {
            get
            {
                return this._cc029;
            }
            set
            {
                this._cc029 = value;
            }
        }
        
        // 
        public string CC030
        {
            get
            {
                return this._cc030;
            }
            set
            {
                this._cc030 = value;
            }
        }
        
        // 
        public string CC031
        {
            get
            {
                return this._cc031;
            }
            set
            {
                this._cc031 = value;
            }
        }
        
        // 
        public string CC032
        {
            get
            {
                return this._cc032;
            }
            set
            {
                this._cc032 = value;
            }
        }
        
        // 
        public string CC033
        {
            get
            {
                return this._cc033;
            }
            set
            {
                this._cc033 = value;
            }
        }
        
        // 
        public string CC034
        {
            get
            {
                return this._cc034;
            }
            set
            {
                this._cc034 = value;
            }
        }
        
        // 
        public string CC035
        {
            get
            {
                return this._cc035;
            }
            set
            {
                this._cc035 = value;
            }
        }
    }
}
