//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class StandardAuditFivCKEntity
    {
        
        private int _idx;
        
        private string _ck001;
        
        private string _ck002;
        
        private string _ck003;
        
        private string _ck004;
        
        private DateTime? _ck005;
        
        private DateTime? _ck006;
        
        private string _ck007;
        
        private string _ck008;
        
        private string _ck009;
        
        private string _ck010;
        
        private string _ck011;
        
        private string _ck012;
        
        private string _ck022;
        
        private string _ck023;
        
        private string _ck013;
        
        private DateTime? _ck014;
        
        private string _ck015;
        
        private DateTime? _ck016;
        
        private string _ck017;
        
        private DateTime? _ck018;
        
        private string _ck019;
        
        private string _ck020;
        
        private string _ck021;
        
        private string _ck024;
        
        private string _ck025;
        
        private string _ck026;
        
        private string _ck027;
        
        private string _ck028;
        
        private string _ck029;
        
        private string _ck030;
        
        private string _ck031;
        
        private string _ck032;
        
        private string _ck033;
        
        private string _ck034;
        
        private string _ck035;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string CK001
        {
            get
            {
                return this._ck001;
            }
            set
            {
                this._ck001 = value;
            }
        }

        /// <summary>
        /// 部件名称
        /// </summary>

        public string CK002
        {
            get
            {
                return this._ck002;
            }
            set
            {
                this._ck002 = value;
            }
        }

        /// <summary>
        /// 工序名称
        /// </summary>

        public string CK003
        {
            get
            {
                return this._ck003;
            }
            set
            {
                this._ck003 = value;
            }
        }

        /// <summary>
        /// 审核依据
        /// </summary>

        public string CK004
        {
            get
            {
                return this._ck004;
            }
            set
            {
                this._ck004 = value;
            }
        }

        /// <summary>
        /// 审核日期
        /// </summary>

        public DateTime? CK005
        {
            get
            {
                return this._ck005;
            }
            set
            {
                this._ck005 = value;
            }
        }

        /// <summary>
        /// 生产日期
        /// </summary>

        public DateTime? CK006
        {
            get
            {
                return this._ck006;
            }
            set
            {
                this._ck006 = value;
            }
        }

        /// <summary>
        /// 密度板密度及雕刻光洁度审核
        /// </summary>

        public string CK007
        {
            get
            {
                return this._ck007;
            }
            set
            {
                this._ck007 = value;
            }
        }

        /// <summary>
        /// 图纸与实样公差尺寸核对
        /// </summary>

        public string CK008
        {
            get
            {
                return this._ck008;
            }
            set
            {
                this._ck008 = value;
            }
        }

        /// <summary>
        /// 量检具与图纸尺寸公差核对
        /// </summary>

        public string CK009
        {
            get
            {
                return this._ck009;
            }
            set
            {
                this._ck009 = value;
            }
        }

        /// <summary>
        /// 配合件互配公差适合度审核
        /// </summary>

        public string CK010
        {
            get
            {
                return this._ck010;
            }
            set
            {
                this._ck010 = value;
            }
        }

        /// <summary>
        /// 部件所靠基准点合理审核
        /// </summary>

        public string CK011
        {
            get
            {
                return this._ck011;
            }
            set
            {
                this._ck011 = value;
            }
        }

        /// <summary>
        /// 对雕刻叠放张数合理性审核
        /// </summary>

        public string CK012
        {
            get
            {
                return this._ck012;
            }
            set
            {
                this._ck012 = value;
            }
        }

        /// <summary>
        /// 操作人岗前培训及达标审核
        /// </summary>

        public string CK022
        {
            get
            {
                return this._ck022;
            }
            set
            {
                this._ck022 = value;
            }
        }
        
        // 
        public string CK023
        {
            get
            {
                return this._ck023;
            }
            set
            {
                this._ck023 = value;
            }
        }

        /// <summary>
        /// 工程人员
        /// </summary>

        public string CK013
        {
            get
            {
                return this._ck013;
            }
            set
            {
                this._ck013 = value;
            }
        }

        /// <summary>
        /// 工程人员日期
        /// </summary>
        public DateTime? CK014
        {
            get
            {
                return this._ck014;
            }
            set
            {
                this._ck014 = value;
            }
        }

        /// <summary>
        /// 车间经理
        /// </summary>

        public string CK015
        {
            get
            {
                return this._ck015;
            }
            set
            {
                this._ck015 = value;
            }
        }

        /// <summary>
        /// 车间经理日期
        /// </summary>

        public DateTime? CK016
        {
            get
            {
                return this._ck016;
            }
            set
            {
                this._ck016 = value;
            }
        }

        /// <summary>
        /// 动力组长
        /// </summary>

        public string CK017
        {
            get
            {
                return this._ck017;
            }
            set
            {
                this._ck017 = value;
            }
        }

        /// <summary>
        /// 动力组长
        /// </summary>

        public DateTime? CK018
        {
            get
            {
                return this._ck018;
            }
            set
            {
                this._ck018 = value;
            }
        }
        
        // 
        public string CK019
        {
            get
            {
                return this._ck019;
            }
            set
            {
                this._ck019 = value;
            }
        }
        
        // 
        public string CK020
        {
            get
            {
                return this._ck020;
            }
            set
            {
                this._ck020 = value;
            }
        }

        /// <summary>
        /// 每次不合格下面打×并说明
        /// </summary>

        public string CK021
        {
            get
            {
                return this._ck021;
            }
            set
            {
                this._ck021 = value;
            }
        }
        
        // 
        public string CK024
        {
            get
            {
                return this._ck024;
            }
            set
            {
                this._ck024 = value;
            }
        }
        
        // 
        public string CK025
        {
            get
            {
                return this._ck025;
            }
            set
            {
                this._ck025 = value;
            }
        }
        
        // 
        public string CK026
        {
            get
            {
                return this._ck026;
            }
            set
            {
                this._ck026 = value;
            }
        }
        
        // 
        public string CK027
        {
            get
            {
                return this._ck027;
            }
            set
            {
                this._ck027 = value;
            }
        }
        
        // 
        public string CK028
        {
            get
            {
                return this._ck028;
            }
            set
            {
                this._ck028 = value;
            }
        }
        
        // 
        public string CK029
        {
            get
            {
                return this._ck029;
            }
            set
            {
                this._ck029 = value;
            }
        }
        
        // 
        public string CK030
        {
            get
            {
                return this._ck030;
            }
            set
            {
                this._ck030 = value;
            }
        }
        
        // 
        public string CK031
        {
            get
            {
                return this._ck031;
            }
            set
            {
                this._ck031 = value;
            }
        }
        
        // 
        public string CK032
        {
            get
            {
                return this._ck032;
            }
            set
            {
                this._ck032 = value;
            }
        }
        
        // 
        public string CK033
        {
            get
            {
                return this._ck033;
            }
            set
            {
                this._ck033 = value;
            }
        }
        
        // 
        public string CK034
        {
            get
            {
                return this._ck034;
            }
            set
            {
                this._ck034 = value;
            }
        }
        
        // 
        public string CK035
        {
            get
            {
                return this._ck035;
            }
            set
            {
                this._ck035 = value;
            }
        }
    }
}
