//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class TeamLeaderRoutineCheckPqqzc
    {
        private DateTime _qz002;
        
        private string _qz003;
        
        private string _qz004;
        
        private string _qz005;
        
        private decimal _qz006;
        
        private decimal _qz007;
        
        private decimal _qz008;
        
        private decimal _u22;
        
        private decimal _u0;
        
        private decimal _u23;
        
        private int _u1;
        
        private decimal _qz009;
        
        private int _qz011;
        
        private decimal _qz014;
        
        private decimal _u4;
        
        private decimal _u5;
        
        private decimal _u6;

        private decimal _u7;

        private decimal _qz012;
        
        private int _qz013;
        
        private int _qz017;
        
        private decimal _qz018;
        
        private int _qz019;
        
        private decimal _u13;
        
        private long _u14;
        
        private long _u15;
        
        private long _u16;
        
        private long _u17;
        
        private long _u18;
        
        private decimal _qz020;
        
        private int _qz021;
        
        private int _qz022;
        
        private int _qz023;
        
        private int _qz024;
        
        private int _qz025;
        
        private int _qz026;
        
        private int _qz027;
        
        private int _qz028;
        
        private int _qz029;
        
        private int _qz030;
        
        private int _qz039;
        
        private string _dba960;
        
        private decimal _qz015;
        
        private decimal _qz040;
        
        private int _qz016;
        
        private int _qz041;
        
        private decimal _qz042;
        
        private decimal _qz043;
        
        private int _qz044;
        
        private int _qz045;
        
        private int _qz046;
        
        private int _qz047;
        
        private int _qz048;
        
        private int _qz049;
        
        private string _qz031;
        
        private DateTime _qz032;
        
        private string _qz033;
        
        private DateTime _qz034;
        
        private string _qz035;
        
        private DateTime _qz036;
        
        private string _qz037;
        
        private string _qz038;
        
        private string _qz050;
        
        private string _qz051;
        
        private string _qz052;
        
        private string _qz053;
        
        private string _qz054;
        
        private string _qz055;
        
        private string _qz056;
        
        private string _qz057;
        
        private string _qz058;
        
        private string _qz059;
        
        private string _qz060;

        // 日期
        public DateTime QZ002
        {
            get
            {
                return this . _qz002;
            }
            set
            {
                this . _qz002 = value;
            }
        }

        // 部门
        public string QZ003
        {
            get
            {
                return this._qz003;
            }
            set
            {
                this._qz003 = value;
            }
        }
        
        // 姓名
        public string QZ004
        {
            get
            {
                return this._qz004;
            }
            set
            {
                this._qz004 = value;
            }
        }
        
        // 类别
        public string QZ005
        {
            get
            {
                return this._qz005;
            }
            set
            {
                this._qz005 = value;
            }
        }
        
        // 月考勤工数 R502
        public decimal QZ006
        {
            get
            {
                return this._qz006;
            }
            set
            {
                this._qz006 = value;
            }
        }
        
        // 月出勤日 R502
        public decimal QZ007
        {
            get
            {
                return this._qz007;
            }
            set
            {
                this._qz007 = value;
            }
        }
        
        // 月出产值万元 R468
        public decimal QZ008
        {
            get
            {
                return this._qz008;
            }
            set
            {
                this._qz008 = value;
            }
        }
        
        // 
        public decimal U22
        {
            get
            {
                return this._u22;
            }
            set
            {
                this._u22 = value;
            }
        }
        
        // 
        public decimal U0
        {
            get
            {
                return this._u0;
            }
            set
            {
                this._u0 = value;
            }
        }
        
        // 
        public decimal U23
        {
            get
            {
                return this._u23;
            }
            set
            {
                this._u23 = value;
            }
        }
        
        // 
        public int U1
        {
            get
            {
                return this._u1;
            }
            set
            {
                this._u1 = value;
            }
        }
        
        // 系数1(男)
        public decimal QZ009
        {
            get
            {
                return this._qz009;
            }
            set
            {
                this._qz009 = value;
            }
        }
        
        // 系数2(男)
        public int QZ011
        {
            get
            {
                return this._qz011;
            }
            set
            {
                this._qz011 = value;
            }
        }
        
        // 月体系提资额  R502
        public decimal QZ014
        {
            get
            {
                return this._qz014;
            }
            set
            {
                this._qz014 = value;
            }
        }
        
        // 
        public decimal U4
        {
            get
            {
                return this._u4;
            }
            set
            {
                this._u4 = value;
            }
        }
        
        // 
        public decimal U5
        {
            get
            {
                return this._u5;
            }
            set
            {
                this._u5 = value;
            }
        }
        
        // 
        public decimal U6
        {
            get
            {
                return this._u6;
            }
            set
            {
                this._u6 = value;
            }
        }


        // 
        public decimal U7
        {
            get
            {
                return this . _u7;
            }
            set
            {
                this . _u7 = value;
            }
        }

        // 系数3(男)
        public decimal QZ012
        {
            get
            {
                return this._qz012;
            }
            set
            {
                this._qz012 = value;
            }
        }
        
        // 本组创利润额R241
        public int QZ013
        {
            get
            {
                return this._qz013;
            }
            set
            {
                this._qz013 = value;
            }
        }
        
        // 系数4(男)
        public int QZ017
        {
            get
            {
                return this._qz017;
            }
            set
            {
                this._qz017 = value;
            }
        }
        
        // 系数5
        public decimal QZ018
        {
            get
            {
                return this._qz018;
            }
            set
            {
                this._qz018 = value;
            }
        }
        
        // 成本节省金额
        public int QZ019
        {
            get
            {
                return this._qz019;
            }
            set
            {
                this._qz019 = value;
            }
        }
        
        // 
        public decimal U13
        {
            get
            {
                return this._u13;
            }
            set
            {
                this._u13 = value;
            }
        }
        
        // 
        public long U14
        {
            get
            {
                return this._u14;
            }
            set
            {
                this._u14 = value;
            }
        }
        
        // 
        public long U15
        {
            get
            {
                return this._u15;
            }
            set
            {
                this._u15 = value;
            }
        }
        
        // 
        public long U16
        {
            get
            {
                return this._u16;
            }
            set
            {
                this._u16 = value;
            }
        }
        
        // 
        public long U17
        {
            get
            {
                return this._u17;
            }
            set
            {
                this._u17 = value;
            }
        }
        
        // 
        public long U18
        {
            get
            {
                return this._u18;
            }
            set
            {
                this._u18 = value;
            }
        }
        
        // 系数6
        public decimal QZ020
        {
            get
            {
                return this._qz020;
            }
            set
            {
                this._qz020 = value;
            }
        }
        
        // 退货批数
        public int QZ021
        {
            get
            {
                return this._qz021;
            }
            set
            {
                this._qz021 = value;
            }
        }
        
        // 批价
        public int QZ022
        {
            get
            {
                return this._qz022;
            }
            set
            {
                this._qz022 = value;
            }
        }
        
        // 延误批数
        public int QZ023
        {
            get
            {
                return this._qz023;
            }
            set
            {
                this._qz023 = value;
            }
        }
        
        // 批价
        public int QZ024
        {
            get
            {
                return this._qz024;
            }
            set
            {
                this._qz024 = value;
            }
        }
        
        // 产前参与策划批数
        public int QZ025
        {
            get
            {
                return this._qz025;
            }
            set
            {
                this._qz025 = value;
            }
        }
        
        // 批价
        public int QZ026
        {
            get
            {
                return this._qz026;
            }
            set
            {
                this._qz026 = value;
            }
        }
        
        // 跟单批数R299R253
        public int QZ027
        {
            get
            {
                return this._qz027;
            }
            set
            {
                this._qz027 = value;
            }
        }
        
        // 批价
        public int QZ028
        {
            get
            {
                return this._qz028;
            }
            set
            {
                this._qz028 = value;
            }
        }
        
        // 跟单批数R299R253
        public int QZ029
        {
            get
            {
                return this._qz029;
            }
            set
            {
                this._qz029 = value;
            }
        }
        
        // 批价
        public int QZ030
        {
            get
            {
                return this._qz030;
            }
            set
            {
                this._qz030 = value;
            }
        }
        
        // 其它延误
        public int QZ039
        {
            get
            {
                return this._qz039;
            }
            set
            {
                this._qz039 = value;
            }
        }
        
        // 
        public string DBA960
        {
            get
            {
                return this._dba960;
            }
            set
            {
                this._dba960 = value;
            }
        }
        
        // 系数1(女)
        public decimal QZ015
        {
            get
            {
                return this._qz015;
            }
            set
            {
                this._qz015 = value;
            }
        }
        
        // 系数1(其他)
        public decimal QZ040
        {
            get
            {
                return this._qz040;
            }
            set
            {
                this._qz040 = value;
            }
        }
        
        // 系数2(女)
        public int QZ016
        {
            get
            {
                return this._qz016;
            }
            set
            {
                this._qz016 = value;
            }
        }
        
        // 系数2(其他)
        public int QZ041
        {
            get
            {
                return this._qz041;
            }
            set
            {
                this._qz041 = value;
            }
        }
        
        // 系数3(女)
        public decimal QZ042
        {
            get
            {
                return this._qz042;
            }
            set
            {
                this._qz042 = value;
            }
        }
        
        // 系数3(其它)
        public decimal QZ043
        {
            get
            {
                return this._qz043;
            }
            set
            {
                this._qz043 = value;
            }
        }
        
        // 系数4(女)
        public int QZ044
        {
            get
            {
                return this._qz044;
            }
            set
            {
                this._qz044 = value;
            }
        }
        
        // 系数4(其它)
        public int QZ045
        {
            get
            {
                return this._qz045;
            }
            set
            {
                this._qz045 = value;
            }
        }
        
        // 跟单批数R299R253
        public int QZ046
        {
            get
            {
                return this._qz046;
            }
            set
            {
                this._qz046 = value;
            }
        }
        
        // 批价6
        public int QZ047
        {
            get
            {
                return this._qz047;
            }
            set
            {
                this._qz047 = value;
            }
        }
        
        // 跟单批数R299R253
        public int QZ048
        {
            get
            {
                return this._qz048;
            }
            set
            {
                this._qz048 = value;
            }
        }
        
        // 批价7
        public int QZ049
        {
            get
            {
                return this._qz049;
            }
            set
            {
                this._qz049 = value;
            }
        }
        
        // 填表人
        public string QZ031
        {
            get
            {
                return this._qz031;
            }
            set
            {
                this._qz031 = value;
            }
        }
        
        // 填表期
        public DateTime QZ032
        {
            get
            {
                return this._qz032;
            }
            set
            {
                this._qz032 = value;
            }
        }
        
        // 审核人
        public string QZ033
        {
            get
            {
                return this._qz033;
            }
            set
            {
                this._qz033 = value;
            }
        }
        
        // 审核期
        public DateTime QZ034
        {
            get
            {
                return this._qz034;
            }
            set
            {
                this._qz034 = value;
            }
        }
        
        // 审批人
        public string QZ035
        {
            get
            {
                return this._qz035;
            }
            set
            {
                this._qz035 = value;
            }
        }
        
        // 审批期
        public DateTime QZ036
        {
            get
            {
                return this._qz036;
            }
            set
            {
                this._qz036 = value;
            }
        }
        
        // 维护记录
        public string QZ037
        {
            get
            {
                return this._qz037;
            }
            set
            {
                this._qz037 = value;
            }
        }
        
        // 维护意见
        public string QZ038
        {
            get
            {
                return this._qz038;
            }
            set
            {
                this._qz038 = value;
            }
        }
        
        // 
        public string QZ050
        {
            get
            {
                return this._qz050;
            }
            set
            {
                this._qz050 = value;
            }
        }
        
        // 
        public string QZ051
        {
            get
            {
                return this._qz051;
            }
            set
            {
                this._qz051 = value;
            }
        }
        
        // 
        public string QZ052
        {
            get
            {
                return this._qz052;
            }
            set
            {
                this._qz052 = value;
            }
        }
        
        // 
        public string QZ053
        {
            get
            {
                return this._qz053;
            }
            set
            {
                this._qz053 = value;
            }
        }
        
        // 
        public string QZ054
        {
            get
            {
                return this._qz054;
            }
            set
            {
                this._qz054 = value;
            }
        }
        
        // 
        public string QZ055
        {
            get
            {
                return this._qz055;
            }
            set
            {
                this._qz055 = value;
            }
        }
        
        // 
        public string QZ056
        {
            get
            {
                return this._qz056;
            }
            set
            {
                this._qz056 = value;
            }
        }
        
        // 
        public string QZ057
        {
            get
            {
                return this._qz057;
            }
            set
            {
                this._qz057 = value;
            }
        }
        
        // 
        public string QZ058
        {
            get
            {
                return this._qz058;
            }
            set
            {
                this._qz058 = value;
            }
        }
        
        // 
        public string QZ059
        {
            get
            {
                return this._qz059;
            }
            set
            {
                this._qz059 = value;
            }
        }
        
        // 
        public string QZ060
        {
            get
            {
                return this._qz060;
            }
            set
            {
                this._qz060 = value;
            }
        }
    }
}
