//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class TestReportForAQDBEntity
    {
        
        private int _idx;
        
        private string _db001;
        
        private string _db002;
        
        private string _db003;
        
        private int? _db004;
        
        private int? _db005;
        
        private int? _db006;
        
        private int? _db007;
        
        private int? _db008;
        
        private string _db009;
        
        private int _db010;
        
        private string _db011;
        
        private string _db012;
        
        private string _db013;
        
        private string _db014;
        
        private string _db015;
        
        private string _db016;
        
        private string _db017;
        
        private string _db018;
        
        private string _db019;
        
        private string _db020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string DB001
        {
            get
            {
                return this._db001;
            }
            set
            {
                this._db001 = value;
            }
        }

        /// <summary>
        /// 检验标准
        /// </summary>

        public string DB002
        {
            get
            {
                return this._db002;
            }
            set
            {
                this._db002 = value;
            }
        }

        /// <summary>
        /// 检验方法
        /// </summary>

        public string DB003
        {
            get
            {
                return this._db003;
            }
            set
            {
                this._db003 = value;
            }
        }

        /// <summary>
        /// 数量
        /// </summary>

        public int? DB004
        {
            get
            {
                return this._db004;
            }
            set
            {
                this._db004 = value;
            }
        }

        /// <summary>
        /// S.O
        /// </summary>

        public int? DB005
        {
            get
            {
                return this._db005;
            }
            set
            {
                this._db005 = value;
            }
        }

        /// <summary>
        /// S.P
        /// </summary>

        public int? DB006
        {
            get
            {
                return this._db006;
            }
            set
            {
                this._db006 = value;
            }
        }

        /// <summary>
        /// S.E
        /// </summary>

        public int? DB007
        {
            get
            {
                return this._db007;
            }
            set
            {
                this._db007 = value;
            }
        }

        /// <summary>
        /// C.P
        /// </summary>

        public int? DB008
        {
            get
            {
                return this._db008;
            }
            set
            {
                this._db008 = value;
            }
        }

        /// <summary>
        /// 不良品描述
        /// </summary>

        public string DB009
        {
            get
            {
                return this._db009;
            }
            set
            {
                this._db009 = value;
            }
        }
        
        /// <summary>
        /// 序号
        /// </summary>
                 
        public int DB010
        {
            get
            {
                return this._db010;
            }
            set
            {
                this._db010 = value;
            }
        }
        
        // 
        public string DB011
        {
            get
            {
                return this._db011;
            }
            set
            {
                this._db011 = value;
            }
        }
        
        // 
        public string DB012
        {
            get
            {
                return this._db012;
            }
            set
            {
                this._db012 = value;
            }
        }
        
        // 
        public string DB013
        {
            get
            {
                return this._db013;
            }
            set
            {
                this._db013 = value;
            }
        }
        
        // 
        public string DB014
        {
            get
            {
                return this._db014;
            }
            set
            {
                this._db014 = value;
            }
        }
        
        // 
        public string DB015
        {
            get
            {
                return this._db015;
            }
            set
            {
                this._db015 = value;
            }
        }
        
        // 
        public string DB016
        {
            get
            {
                return this._db016;
            }
            set
            {
                this._db016 = value;
            }
        }
        
        // 
        public string DB017
        {
            get
            {
                return this._db017;
            }
            set
            {
                this._db017 = value;
            }
        }
        
        // 
        public string DB018
        {
            get
            {
                return this._db018;
            }
            set
            {
                this._db018 = value;
            }
        }
        
        // 
        public string DB019
        {
            get
            {
                return this._db019;
            }
            set
            {
                this._db019 = value;
            }
        }
        
        // 
        public string DB020
        {
            get
            {
                return this._db020;
            }
            set
            {
                this._db020 = value;
            }
        }
    }
}
