//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class TestResultRecordOneCWEntity
    {
        
        private int _idx;
        
        private string _cw001;
        
        private string _cw002;
        
        private string _cw003;
        
        private string _cw004;
        
        private string _cw005;
        
        private string _cw006;
        
        private string _cw007;
        
        private string _cw008;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 项号
        /// </summary>

        public string CW001
        {
            get
            {
                return this._cw001;
            }
            set
            {
                this._cw001 = value;
            }
        }

        /// <summary>
        /// 项目
        /// </summary>

        public string CW002
        {
            get
            {
                return this._cw002;
            }
            set
            {
                this._cw002 = value;
            }
        }
        
        // 
        public string CW003
        {
            get
            {
                return this._cw003;
            }
            set
            {
                this._cw003 = value;
            }
        }
        
        // 
        public string CW004
        {
            get
            {
                return this._cw004;
            }
            set
            {
                this._cw004 = value;
            }
        }
        
        // 
        public string CW005
        {
            get
            {
                return this._cw005;
            }
            set
            {
                this._cw005 = value;
            }
        }
        
        // 
        public string CW006
        {
            get
            {
                return this._cw006;
            }
            set
            {
                this._cw006 = value;
            }
        }
        
        // 
        public string CW007
        {
            get
            {
                return this._cw007;
            }
            set
            {
                this._cw007 = value;
            }
        }
        
        // 
        public string CW008
        {
            get
            {
                return this._cw008;
            }
            set
            {
                this._cw008 = value;
            }
        }
    }
}
