//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class TestResultRecordOneCVEntity
    {
        
        private int _idx;
        
        private string _cv001;
        
        private string _cv002;
        
        private string _cv003;
        
        private string _cv004;
        
        private string _cv005;
        
        private string _cv006;
        
        private string _cv007;
        
        private string _cv008;
        
        private string _cv009;
        
        private string _cv010;
        
        private string _cv011;
        
        private string _cv012;
        
        private string _cv013;
        
        private string _cv014;
        
        private string _cv015;
        
        private string _cv016;
        
        private string _cv017;
        
        private string _cv018;
        
        private string _cv019;
        
        private string _cv020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string CV001
        {
            get
            {
                return this._cv001;
            }
            set
            {
                this._cv001 = value;
            }
        }

        /// <summary>
        /// 产品名称
        /// </summary>

        public string CV002
        {
            get
            {
                return this._cv002;
            }
            set
            {
                this._cv002 = value;
            }
        }

        /// <summary>
        /// 货号
        /// </summary>

        public string CV003
        {
            get
            {
                return this._cv003;
            }
            set
            {
                this._cv003 = value;
            }
        }

        /// <summary>
        /// 流水号
        /// </summary>

        public string CV004
        {
            get
            {
                return this._cv004;
            }
            set
            {
                this._cv004 = value;
            }
        }

        /// <summary>
        /// 生产部
        /// </summary>

        public string CV005
        {
            get
            {
                return this._cv005;
            }
            set
            {
                this._cv005 = value;
            }
        }

        /// <summary>
        /// 合同号
        /// </summary>

        public string CV006
        {
            get
            {
                return this._cv006;
            }
            set
            {
                this._cv006 = value;
            }
        }

        /// <summary>
        /// 年龄段
        /// </summary>

        public string CV007
        {
            get
            {
                return this._cv007;
            }
            set
            {
                this._cv007 = value;
            }
        }

        /// <summary>
        /// 输入国
        /// </summary>

        public string CV008
        {
            get
            {
                return this._cv008;
            }
            set
            {
                this._cv008 = value;
            }
        }

        /// <summary>
        /// QC主管
        /// </summary>

        public string CV009
        {
            get
            {
                return this._cv009;
            }
            set
            {
                this._cv009 = value;
            }
        }

        /// <summary>
        /// 检测数量
        /// </summary>

        public string CV010
        {
            get
            {
                return this._cv010;
            }
            set
            {
                this._cv010 = value;
            }
        }
        
        // 
        public string CV011
        {
            get
            {
                return this._cv011;
            }
            set
            {
                this._cv011 = value;
            }
        }
        
        // 
        public string CV012
        {
            get
            {
                return this._cv012;
            }
            set
            {
                this._cv012 = value;
            }
        }
        
        // 
        public string CV013
        {
            get
            {
                return this._cv013;
            }
            set
            {
                this._cv013 = value;
            }
        }
        
        // 
        public string CV014
        {
            get
            {
                return this._cv014;
            }
            set
            {
                this._cv014 = value;
            }
        }
        
        // 
        public string CV015
        {
            get
            {
                return this._cv015;
            }
            set
            {
                this._cv015 = value;
            }
        }
        
        // 
        public string CV016
        {
            get
            {
                return this._cv016;
            }
            set
            {
                this._cv016 = value;
            }
        }
        
        // 
        public string CV017
        {
            get
            {
                return this._cv017;
            }
            set
            {
                this._cv017 = value;
            }
        }
        
        // 
        public string CV018
        {
            get
            {
                return this._cv018;
            }
            set
            {
                this._cv018 = value;
            }
        }
        
        // 
        public string CV019
        {
            get
            {
                return this._cv019;
            }
            set
            {
                this._cv019 = value;
            }
        }
        
        // 
        public string CV020
        {
            get
            {
                return this._cv020;
            }
            set
            {
                this._cv020 = value;
            }
        }
    }
}
