//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class UserInfoEntity
    {
        
        private string _dba001;
        
        private string _dba002;
        
        //private string _dba003;
        
        //private string _dba004;
        
        private string _dba005;
        
        private string _dba006;
        
        //private string _dba007;
        
        //private string _dba008;
        
        //private string _dba009;
        
        //private string _dba010;
        
        //private string _dba011;
        
        //private string _dba012;
        
        //private string _dba013;
        
        //private string _dba014;
        
        //private string _dba015;
        
        //private string _dba016;
        
        //private string _dba017;
        
        //private string _dba018;
        
        //private string _dba019;
        
        //private string _dba020;
        
        //private string _dba021;
        
        //private string _dba022;
        
        //private string _dba023;
        
        //private string _dba024;
        
        //private string _dba025;
        
        //private string _dba026;
        
        //private string _dba027;
        
        private string _dba028;
        
        //private string _dba029;
        
        //private string _dba030;
        
        //private string _dba031;
        
        //private string _dba032;
        
        //private string _dba033;
        
        //private string _dba034;
        
        //private string _dba035;
        
        //private string _dba036;
        
        //private string _dba037;
        
        //private string _dba038;
        
        //private int _dba039;
        
        //private string _dba040;
        
        //private string _dba041;
        
        //private string _dba042;
        
        private string _dba043;
        
        //private string _dba044;
        
        //private string _dba045;
        
        //private string _dba046;
        
        //private decimal _dba047;
        
        //private decimal _dba048;
        
        //private string _dba049;
        
        //private string _dba050;
        
        //private decimal _dba051;
        
        //private string _dba052;
        
        //private string _dba053;
        
        //private string _dba054;
        
        //private string _dba055;
        
        private string _dba960;
        
        private string _dba961;
        
        //private string _dba962;
        
        //private string _dba963;
        
        //private string _dba964;
        
        //private string _dba965;
        
        //private decimal _dba980;
        
        //private decimal _dba981;
        
        //private decimal _dba982;
        
        //private decimal _dba983;
        
        //private decimal _dba984;
        
        //private decimal _dba985;
        
        //private string _dba901;
        
        //private string _dba902;
        
        //private string _dba903;
        
        //private string _dba904;
        
        //private int _dba905;

        /// <summary>
        /// 用户编号
        /// </summary>

        public string DBA001
        {
            get
            {
                return this._dba001;
            }
            set
            {
                this._dba001 = value;
            }
        }

        /// <summary>
        /// 用户姓名
        /// </summary>

        public string DBA002
        {
            get
            {
                return this._dba002;
            }
            set
            {
                this._dba002 = value;
            }
        }

        /// <summary>
        /// 英文姓名
        /// </summary>

        //public string DBA003
        //{
        //    get
        //    {
        //        return this._dba003;
        //    }
        //    set
        //    {
        //        this._dba003 = value;
        //    }
        //}

        /// <summary>
        /// 用户口令
        /// </summary>

        //public string DBA004
        //{
        //    get
        //    {
        //        return this._dba004;
        //    }
        //    set
        //    {
        //        this._dba004 = value;
        //    }
        //}

        /// <summary>
        /// 部门编号
        /// </summary>

        public string DBA005
        {
            get
            {
                return this . _dba005;
            }
            set
            {
                this . _dba005 = value;
            }
        }

        /// <summary>
        /// 是否管理人员
        /// </summary>

        public string DBA006
        {
            get
            {
                return this . _dba006;
            }
            set
            {
                this . _dba006 = value;
            }
        }

        /// <summary>
        /// 预留字段
        /// </summary>

        //public string DBA007
        //{
        //    get
        //    {
        //        return this._dba007;
        //    }
        //    set
        //    {
        //        this._dba007 = value;
        //    }
        //}

        /// <summary>
        /// 预留字段
        /// </summary>

        //public string DBA008
        //{
        //    get
        //    {
        //        return this._dba008;
        //    }
        //    set
        //    {
        //        this._dba008 = value;
        //    }
        //}

        /// <summary>
        /// 预留字段
        /// </summary>

        //public string DBA009
        //{
        //    get
        //    {
        //        return this._dba009;
        //    }
        //    set
        //    {
        //        this._dba009 = value;
        //    }
        //}

        /// <summary>
        /// 人员描述
        /// </summary>

        //public string DBA010
        //{
        //    get
        //    {
        //        return this._dba010;
        //    }
        //    set
        //    {
        //        this._dba010 = value;
        //    }
        //}

        /// <summary>
        /// 人员类别
        /// </summary>

        //public string DBA011
        //{
        //    get
        //    {
        //        return this._dba011;
        //    }
        //    set
        //    {
        //        this._dba011 = value;
        //    }
        //}

        /// <summary>
        /// 职务
        /// </summary>

        //public string DBA012
        //{
        //    get
        //    {
        //        return this._dba012;
        //    }
        //    set
        //    {
        //        this._dba012 = value;
        //    }
        //}

        /// <summary>
        /// 入职日期
        /// </summary>

        //public string DBA013
        //{
        //    get
        //    {
        //        return this._dba013;
        //    }
        //    set
        //    {
        //        this._dba013 = value;
        //    }
        //}

        /// <summary>
        /// 离职日期
        /// </summary>

        //public string DBA014
        //{
        //    get
        //    {
        //        return this._dba014;
        //    }
        //    set
        //    {
        //        this._dba014 = value;
        //    }
        //}

        /// <summary>
        /// 性别
        /// </summary>

        //public string DBA015
        //{
        //    get
        //    {
        //        return this._dba015;
        //    }
        //    set
        //    {
        //        this._dba015 = value;
        //    }
        //}

        /// <summary>
        /// 出生年月
        /// </summary>

        //public string DBA016
        //{
        //    get
        //    {
        //        return this._dba016;
        //    }
        //    set
        //    {
        //        this._dba016 = value;
        //    }
        //}

        /// <summary>
        /// 邮政编码
        /// </summary>

        //public string DBA017
        //{
        //    get
        //    {
        //        return this._dba017;
        //    }
        //    set
        //    {
        //        this._dba017 = value;
        //    }
        //}

        /// <summary>
        /// 身份证号
        /// </summary>

        //public string DBA018
        //{
        //    get
        //    {
        //        return this._dba018;
        //    }
        //    set
        //    {
        //        this._dba018 = value;
        //    }
        //}

        /// <summary>
        /// 学历
        /// </summary>

        //public string DBA019
        //{
        //    get
        //    {
        //        return this._dba019;
        //    }
        //    set
        //    {
        //        this._dba019 = value;
        //    }
        //}

        /// <summary>
        /// 技术职称
        /// </summary>

        //public string DBA020
        //{
        //    get
        //    {
        //        return this._dba020;
        //    }
        //    set
        //    {
        //        this._dba020 = value;
        //    }
        //}

        /// <summary>
        /// 婚否
        /// </summary>

        //public string DBA021
        //{
        //    get
        //    {
        //        return this._dba021;
        //    }
        //    set
        //    {
        //        this._dba021 = value;
        //    }
        //}

        /// <summary>
        /// 劳动合同编号
        /// </summary>

        //public string DBA022
        //{
        //    get
        //    {
        //        return this._dba022;
        //    }
        //    set
        //    {
        //        this._dba022 = value;
        //    }
        //}

        /// <summary>
        /// 合同生效日期
        /// </summary>

        //public string DBA023
        //{
        //    get
        //    {
        //        return this._dba023;
        //    }
        //    set
        //    {
        //        this._dba023 = value;
        //    }
        //}

        /// <summary>
        /// 合同失效日期
        /// </summary>

        //public string DBA024
        //{
        //    get
        //    {
        //        return this._dba024;
        //    }
        //    set
        //    {
        //        this._dba024 = value;
        //    }
        //}

        /// <summary>
        /// 外籍人士
        /// </summary>

        //public string DBA025
        //{
        //    get
        //    {
        //        return this._dba025;
        //    }
        //    set
        //    {
        //        this._dba025 = value;
        //    }
        //}

        /// <summary>
        /// 地址
        /// </summary>

        //public string DBA026
        //{
        //    get
        //    {
        //        return this._dba026;
        //    }
        //    set
        //    {
        //        this._dba026 = value;
        //    }
        //}

        /// <summary>
        /// 电话
        /// </summary>

        //public string DBA027
        //{
        //    get
        //    {
        //        return this._dba027;
        //    }
        //    set
        //    {
        //        this._dba027 = value;
        //    }
        //}

        /// <summary>
        /// 手机
        /// </summary>

        public string DBA028
        {
            get
            {
                return this._dba028;
            }
            set
            {
                this._dba028 = value;
            }
        }

        /// <summary>
        /// 电子邮件
        /// </summary>

        //public string DBA029
        //{
        //    get
        //    {
        //        return this._dba029;
        //    }
        //    set
        //    {
        //        this._dba029 = value;
        //    }
        //}

        /// <summary>
        /// 开户银行
        /// </summary>

        //public string DBA030
        //{
        //    get
        //    {
        //        return this._dba030;
        //    }
        //    set
        //    {
        //        this._dba030 = value;
        //    }
        //}

        /// <summary>
        /// 银行帐号
        /// </summary>

        //public string DBA031
        //{
        //    get
        //    {
        //        return this._dba031;
        //    }
        //    set
        //    {
        //        this._dba031 = value;
        //    }
        //}

        /// <summary>
        /// 工资停发
        /// </summary>

        //public string DBA032
        //{
        //    get
        //    {
        //        return this._dba032;
        //    }
        //    set
        //    {
        //        this._dba032 = value;
        //    }
        //}

        /// <summary>
        /// 计税
        /// </summary>

        //public string DBA033
        //{
        //    get
        //    {
        //        return this._dba033;
        //    }
        //    set
        //    {
        //        this._dba033 = value;
        //    }
        //}

        /// <summary>
        /// 调出
        /// </summary>

        //public string DBA034
        //{
        //    get
        //    {
        //        return this._dba034;
        //    }
        //    set
        //    {
        //        this._dba034 = value;
        //    }
        //}

        /// <summary>
        /// 仅是员工
        /// </summary>

        //public string DBA035
        //{
        //    get
        //    {
        //        return this._dba035;
        //    }
        //    set
        //    {
        //        this._dba035 = value;
        //    }
        //}

        /// <summary>
        /// 备注
        /// </summary>

        //public string DBA036
        //{
        //    get
        //    {
        //        return this._dba036;
        //    }
        //    set
        //    {
        //        this._dba036 = value;
        //    }
        //}

        /// <summary>
        /// 使用默认菜单
        /// </summary>

        //public string DBA037
        //{
        //    get
        //    {
        //        return this._dba037;
        //    }
        //    set
        //    {
        //        this._dba037 = value;
        //    }
        //}

        /// <summary>
        /// 提醒设置
        /// </summary>

        //public string DBA038
        //{
        //    get
        //    {
        //        return this._dba038;
        //    }
        //    set
        //    {
        //        this._dba038 = value;
        //    }
        //}

        /// <summary>
        /// 间隔时间
        /// </summary>

        //public int DBA039
        //{
        //    get
        //    {
        //        return this._dba039;
        //    }
        //    set
        //    {
        //        this._dba039 = value;
        //    }
        //}

        /// <summary>
        /// 提醒方式
        /// </summary>

        //public string DBA040
        //{
        //    get
        //    {
        //        return this._dba040;
        //    }
        //    set
        //    {
        //        this._dba040 = value;
        //    }
        //}

        /// <summary>
        /// 核算计件工资
        /// </summary>

        //public string DBA041
        //{
        //    get
        //    {
        //        return this._dba041;
        //    }
        //    set
        //    {
        //        this._dba041 = value;
        //    }
        //}

        /// <summary>
        /// 保存收件箱
        /// </summary>

        //public string DBA042
        //{
        //    get
        //    {
        //        return this._dba042;
        //    }
        //    set
        //    {
        //        this._dba042 = value;
        //    }
        //}

        /// <summary>
        /// 是否注销
        /// </summary>

        public string DBA043
        {
            get
            {
                return this . _dba043;
            }
            set
            {
                this . _dba043 = value;
            }
        }

        /// <summary>
        /// 角色编号
        /// </summary>

        //public string DBA044
        //{
        //    get
        //    {
        //        return this._dba044;
        //    }
        //    set
        //    {
        //        this._dba044 = value;
        //    }
        //}

        /// <summary>
        /// 是否锁定用户
        /// </summary>

        //public string DBA045
        //{
        //    get
        //    {
        //        return this._dba045;
        //    }
        //    set
        //    {
        //        this._dba045 = value;
        //    }
        //}

        /// <summary>
        /// 岗位
        /// </summary>

        //public string DBA046
        //{
        //    get
        //    {
        //        return this._dba046;
        //    }
        //    set
        //    {
        //        this._dba046 = value;
        //    }
        //}

        /// <summary>
        /// 年假天数
        /// </summary>

        //public decimal DBA047
        //{
        //    get
        //    {
        //        return this._dba047;
        //    }
        //    set
        //    {
        //        this._dba047 = value;
        //    }
        //}

        /// <summary>
        /// 年假已休天数
        /// </summary>

        //public decimal DBA048
        //{
        //    get
        //    {
        //        return this._dba048;
        //    }
        //    set
        //    {
        //        this._dba048 = value;
        //    }
        //}

        /// <summary>
        /// QQ
        /// </summary>

        //public string DBA049
        //{
        //    get
        //    {
        //        return this._dba049;
        //    }
        //    set
        //    {
        //        this._dba049 = value;
        //    }
        //}

        /// <summary>
        /// 政治面貌
        /// </summary>

        //public string DBA050
        //{
        //    get
        //    {
        //        return this._dba050;
        //    }
        //    set
        //    {
        //        this._dba050 = value;
        //    }
        //}

        // 工龄
        //public decimal DBA051
        //{
        //    get
        //    {
        //        return this._dba051;
        //    }
        //    set
        //    {
        //        this._dba051 = value;
        //    }
        //}

        // 预计转正日期
        //public string DBA052
        //{
        //    get
        //    {
        //        return this._dba052;
        //    }
        //    set
        //    {
        //        this._dba052 = value;
        //    }
        //}

        // 试用开始日期
        //public string DBA053
        //{
        //    get
        //    {
        //        return this._dba053;
        //    }
        //    set
        //    {
        //        this._dba053 = value;
        //    }
        //}

        // 试用截止日期
        //public string DBA054
        //{
        //    get
        //    {
        //        return this._dba054;
        //    }
        //    set
        //    {
        //        this._dba054 = value;
        //    }
        //}

        // 考勤卡号
        //public string DBA055
        //{
        //    get
        //    {
        //        return this._dba055;
        //    }
        //    set
        //    {
        //        this._dba055 = value;
        //    }
        //}

        /// <summary>
        /// 性别
        /// </summary>
        public string DBA960
        {
            get
            {
                return this._dba960;
            }
            set
            {
                this._dba960 = value;
            }
        }
        
        /// <summary>
        /// 组号
        /// </summary>
        public string DBA961
        {
            get
            {
                return this._dba961;
            }
            set
            {
                this._dba961 = value;
            }
        }
        
        // 自定文字3
        //public string DBA962
        //{
        //    get
        //    {
        //        return this._dba962;
        //    }
        //    set
        //    {
        //        this._dba962 = value;
        //    }
        //}
        
        // 自定文字4
        //public string DBA963
        //{
        //    get
        //    {
        //        return this._dba963;
        //    }
        //    set
        //    {
        //        this._dba963 = value;
        //    }
        //}
        
        // 自定文字5
        //public string DBA964
        //{
        //    get
        //    {
        //        return this._dba964;
        //    }
        //    set
        //    {
        //        this._dba964 = value;
        //    }
        //}
        
        // 自定文字6
        //public string DBA965
        //{
        //    get
        //    {
        //        return this._dba965;
        //    }
        //    set
        //    {
        //        this._dba965 = value;
        //    }
        //}
        
        // 自定数字1
        //public decimal DBA980
        //{
        //    get
        //    {
        //        return this._dba980;
        //    }
        //    set
        //    {
        //        this._dba980 = value;
        //    }
        //}
        
        // 自定数字2
        //public decimal DBA981
        //{
        //    get
        //    {
        //        return this._dba981;
        //    }
        //    set
        //    {
        //        this._dba981 = value;
        //    }
        //}
        
        // 自定数字3
        //public decimal DBA982
        //{
        //    get
        //    {
        //        return this._dba982;
        //    }
        //    set
        //    {
        //        this._dba982 = value;
        //    }
        //}
        
        // 自定数字4
        //public decimal DBA983
        //{
        //    get
        //    {
        //        return this._dba983;
        //    }
        //    set
        //    {
        //        this._dba983 = value;
        //    }
        //}
        
        // 自定数字5
        //public decimal DBA984
        //{
        //    get
        //    {
        //        return this._dba984;
        //    }
        //    set
        //    {
        //        this._dba984 = value;
        //    }
        //}
        
        // 自定数字6
        //public decimal DBA985
        //{
        //    get
        //    {
        //        return this._dba985;
        //    }
        //    set
        //    {
        //        this._dba985 = value;
        //    }
        //}
        
        // 录入者编号
        //public string DBA901
        //{
        //    get
        //    {
        //        return this._dba901;
        //    }
        //    set
        //    {
        //        this._dba901 = value;
        //    }
        //}
        
        // 录入时间
        //public string DBA902
        //{
        //    get
        //    {
        //        return this._dba902;
        //    }
        //    set
        //    {
        //        this._dba902 = value;
        //    }
        //}
        
        // 更改者编号
        //public string DBA903
        //{
        //    get
        //    {
        //        return this._dba903;
        //    }
        //    set
        //    {
        //        this._dba903 = value;
        //    }
        //}
        
        // 更改时间
        //public string DBA904
        //{
        //    get
        //    {
        //        return this._dba904;
        //    }
        //    set
        //    {
        //        this._dba904 = value;
        //    }
        //}
        
        // 更新标记
        //public int DBA905
        //{
        //    get
        //    {
        //        return this._dba905;
        //    }
        //    set
        //    {
        //        this._dba905 = value;
        //    }
        //}
    }
}
