//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class WarehouseReceiptWAREntity
    {
        
        private int _idx;
        
        private string _war001;
        
        private DateTime _war002;
        
        private string _war003;
        
        private string _war004;
        
        private string _war005;
        
        private decimal _war006;
        
        private string _war007;
        
        private decimal _war008;
        
        private decimal _war009;
        
        private string _war010;
        
        private string _war011;
        
        private string _war012;
        
        private string _war013;
        
        private string _war014;
        
        private string _war015;
        
        private string _war016;
        
        private string _war017;
        
        private string _war018;
        
        private string _war019;
        
        private string _war020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 物料类别
        /// </summary>

        public string WAR001
        {
            get
            {
                return this._war001;
            }
            set
            {
                this._war001 = value;
            }
        }

        /// <summary>
        /// 入库日期
        /// </summary>

        public DateTime WAR002
        {
            get
            {
                return this._war002;
            }
            set
            {
                this._war002 = value;
            }
        }

        /// <summary>
        /// 申购人
        /// </summary>

        public string WAR003
        {
            get
            {
                return this._war003;
            }
            set
            {
                this._war003 = value;
            }
        }

        /// <summary>
        /// 物料名称
        /// </summary>

        public string WAR004
        {
            get
            {
                return this._war004;
            }
            set
            {
                this._war004 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string WAR005
        {
            get
            {
                return this._war005;
            }
            set
            {
                this._war005 = value;
            }
        }

        /// <summary>
        /// 入库数量
        /// </summary>

        public decimal WAR006
        {
            get
            {
                return this._war006;
            }
            set
            {
                this._war006 = value;
            }
        }

        /// <summary>
        /// 单位
        /// </summary>

        public string WAR007
        {
            get
            {
                return this._war007;
            }
            set
            {
                this._war007 = value;
            }
        }

        /// <summary>
        /// 原单价
        /// </summary>

        public decimal WAR008
        {
            get
            {
                return this._war008;
            }
            set
            {
                this._war008 = value;
            }
        }

        /// <summary>
        /// 现单价
        /// </summary>

        public decimal WAR009
        {
            get
            {
                return this._war009;
            }
            set
            {
                this._war009 = value;
            }
        }

        /// <summary>
        /// 供应商编号
        /// </summary>

        public string WAR010
        {
            get
            {
                return this._war010;
            }
            set
            {
                this._war010 = value;
            }
        }

        /// <summary>
        /// 采购人
        /// </summary>

        public string WAR011
        {
            get
            {
                return this._war011;
            }
            set
            {
                this._war011 = value;
            }
        }

        /// <summary>
        /// 用途
        /// </summary>

        public string WAR012
        {
            get
            {
                return this._war012;
            }
            set
            {
                this._war012 = value;
            }
        }
        
        // 
        public string WAR013
        {
            get
            {
                return this._war013;
            }
            set
            {
                this._war013 = value;
            }
        }
        
        // 
        public string WAR014
        {
            get
            {
                return this._war014;
            }
            set
            {
                this._war014 = value;
            }
        }
        
        // 
        public string WAR015
        {
            get
            {
                return this._war015;
            }
            set
            {
                this._war015 = value;
            }
        }
        
        // 
        public string WAR016
        {
            get
            {
                return this._war016;
            }
            set
            {
                this._war016 = value;
            }
        }
        
        // 
        public string WAR017
        {
            get
            {
                return this._war017;
            }
            set
            {
                this._war017 = value;
            }
        }
        
        // 
        public string WAR018
        {
            get
            {
                return this._war018;
            }
            set
            {
                this._war018 = value;
            }
        }
        
        // 
        public string WAR019
        {
            get
            {
                return this._war019;
            }
            set
            {
                this._war019 = value;
            }
        }
        
        // 
        public string WAR020
        {
            get
            {
                return this._war020;
            }
            set
            {
                this._war020 = value;
            }
        }
    }
}
