//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class WarehouseReceiptWASEntity
    {
        
        private int _idx;
        
        private string _was001;
        
        private DateTime _was002;
        
        private string _was003;
        
        private string _was004;
        
        private string _was005;
        
        private decimal _was006;
        
        private decimal _was007;
        
        private decimal _was008;
        
        private string _was009;
        
        private string _was010;
        
        private string _was011;
        
        private int _was012;
        
        private string _was013;
        
        private string _was014;
        
        private string _was015;
        
        private string _was016;
        
        private string _was017;
        
        private string _was018;
        
        private string _was019;
        
        private string _was020;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 物料类别
        /// </summary>

        public string WAS001
        {
            get
            {
                return this._was001;
            }
            set
            {
                this._was001 = value;
            }
        }

        /// <summary>
        /// 领用日期
        /// </summary>

        public DateTime WAS002
        {
            get
            {
                return this._was002;
            }
            set
            {
                this._was002 = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>

        public string WAS003
        {
            get
            {
                return this._was003;
            }
            set
            {
                this._was003 = value;
            }
        }

        /// <summary>
        /// 物料名称
        /// </summary>

        public string WAS004
        {
            get
            {
                return this._was004;
            }
            set
            {
                this._was004 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string WAS005
        {
            get
            {
                return this._was005;
            }
            set
            {
                this._was005 = value;
            }
        }

        /// <summary>
        /// 领用数量
        /// </summary>

        public decimal WAS006
        {
            get
            {
                return this._was006;
            }
            set
            {
                this._was006 = value;
            }
        }

        /// <summary>
        /// 原单价
        /// </summary>

        public decimal WAS007
        {
            get
            {
                return this._was007;
            }
            set
            {
                this._was007 = value;
            }
        }

        /// <summary>
        /// 现单价
        /// </summary>

        public decimal WAS008
        {
            get
            {
                return this._was008;
            }
            set
            {
                this._was008 = value;
            }
        }

        /// <summary>
        /// 领用人
        /// </summary>

        public string WAS009
        {
            get
            {
                return this._was009;
            }
            set
            {
                this._was009 = value;
            }
        }

        /// <summary>
        /// 用途
        /// </summary>

        public string WAS010
        {
            get
            {
                return this._was010;
            }
            set
            {
                this._was010 = value;
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
                 
        public string WAS011
        {
            get
            {
                return this._was011;
            }
            set
            {
                this._was011 = value;
            }
        }
        
        /// <summary>
        /// 入库单idx
        /// </summary>
                 
        public int WAS012
        {
            get
            {
                return this._was012;
            }
            set
            {
                this._was012 = value;
            }
        }
        
        /// <summary>
        /// 部门
        /// </summary>
                 
        public string WAS013
        {
            get
            {
                return this._was013;
            }
            set
            {
                this._was013 = value;
            }
        }
        
        // 
        public string WAS014
        {
            get
            {
                return this._was014;
            }
            set
            {
                this._was014 = value;
            }
        }
        
        // 
        public string WAS015
        {
            get
            {
                return this._was015;
            }
            set
            {
                this._was015 = value;
            }
        }
        
        // 
        public string WAS016
        {
            get
            {
                return this._was016;
            }
            set
            {
                this._was016 = value;
            }
        }
        
        // 
        public string WAS017
        {
            get
            {
                return this._was017;
            }
            set
            {
                this._was017 = value;
            }
        }
        
        // 
        public string WAS018
        {
            get
            {
                return this._was018;
            }
            set
            {
                this._was018 = value;
            }
        }
        
        // 
        public string WAS019
        {
            get
            {
                return this._was019;
            }
            set
            {
                this._was019 = value;
            }
        }
        
        // 
        public string WAS020
        {
            get
            {
                return this._was020;
            }
            set
            {
                this._was020 = value;
            }
        }
    }
}
