//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class yanpinchangqiancehuaLibrary
    {
        
        private int _idx;
        
        private string _cq01;
        
        private string _cq02;
        
        private string _cq03;
        
        private string _cq04;
        
        private string _cq05;
        
        private DateTime _cq06;
        
        private DateTime _cq07;
        
        private string _cq08;
        
        private string _cq09;
        
        private string _cq10;
        
        private string _cq11;
        
        private string _cq12;
        
        private string _cq13;
        
        private int _cq14;
        
        private string _cq15;
        
        private string _cq16;
        
        private string _cq17;
        
        private string _cq18;
        
        private string _cq19;
        
        private string _cq20;
        
        private string _cq21;
        
        private string _cq22;
        
        private string _cq23;
        
        private string _cq24;
        
        private string _cq25;
        
        private string _cq26;
        
        private string _cq27;
        
        private string _cq28;
        
        private string _cq29;
        
        private string _cq30;
        
        private string _cq31;
        
        private string _cq32;
        
        private string _cq33;

        private byte[] _cq34 = new byte[0];

        private string _cq35;
        
        private string _cq36;
        
        private string _cq37;
        
        private string _cq38;
        
        private string _cq39;
        
        private string _cq40;
        
        private string _cq41;
        
        private string _cq42;
        
        private string _cq43;
        
        private string _cq44;
        
        private string _cq45;
        
        private int _cq46;
        
        private int _cq47;
        
        private int _cq48;
        
        private int _cq49;
        
        private int _cq50;
        
        private int _cq51;
        
        private int _cq52;
        
        private int _cq53;
        
        private int _cq54;
        
        private int _cq55;
        
        private int _cq56;
        
        private DateTime _cq57;
        
        private DateTime _cq58;
        
        private DateTime _cq59;
        
        private DateTime _cq60;
        
        private DateTime _cq61;
        
        private DateTime _cq62;
        
        private DateTime _cq63;
        
        private DateTime _cq64;
        
        private DateTime _cq65;
        
        private DateTime _cq66;
        
        private DateTime _cq67;
        
        private DateTime _cq68;
        
        private DateTime _cq69;
        
        private DateTime _cq70;
        
        private DateTime _cq71;
        
        private DateTime _cq72;
        
        private DateTime _cq73;
        
        private DateTime _cq74;
        
        private DateTime _cq75;
        
        private DateTime _cq76;
        
        private DateTime _cq77;
        
        private DateTime _cq78;
        
        private string _cq79;
        
        private string _cq80;
        
        private string _cq81;
        
        private string _cq82;
        
        private string _cq83;
        
        private string _cq84;
        
        private string _cq85;
        
        private string _cq86;
        
        private string _cq87;
        
        private string _cq88;
        
        private string _cq89;
        
        private string _cq90;
        
        private string _cq91;
        
        private string _cq92;
        
        private string _cq93;
        
        private string _cq94;
        
        private string _cq95;
        
        private DateTime _cq96;
        
        private string _cq97;
        
        private string _cq98;
        
        private string _cq99;
        
        private string _cq100;
        
        private string _cq101;
        
        private int _cq102;
        
        private decimal _cq103;
        
        private string _cq104;
        
        private decimal _cq105;
        
        private DateTime _cq106;
        
        private DateTime _cq107;
        
        private string _cq108;
        
        private string _cq109;
        
        private string _cq110;
        
        private string _cq111;
        
        private string _cq112;
        
        private DateTime _cq113;
        
        private string _cq114;
        
        private string _cq115;
        
        private string _cq116;
        
        private string _cq117;
        
        private string _cq118;
        
        private string _cq119;
        
        private string _cq120;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }

        /// <summary>
        /// 单号
        /// </summary>

        public string CQ01
        {
            get
            {
                return this._cq01;
            }
            set
            {
                this._cq01 = value;
            }
        }

        /// <summary>
        /// 客户
        /// </summary>
        public string CQ02
        {
            get
            {
                return this._cq02;
            }
            set
            {
                this._cq02 = value;
            }
        }

        /// <summary>
        /// 货号
        /// </summary>
        public string CQ03
        {
            get
            {
                return this._cq03;
            }
            set
            {
                this._cq03 = value;
            }
        }

        /// <summary>
        /// 样品产品名称
        /// </summary>
        public string CQ04
        {
            get
            {
                return this._cq04;
            }
            set
            {
                this._cq04 = value;
            }
        }

        /// <summary>
        /// 样品单号
        /// </summary>

        public string CQ05
        {
            get
            {
                return this._cq05;
            }
            set
            {
                this._cq05 = value;
            }
        }

        /// <summary>
        /// 开单日期
        /// </summary>

        public DateTime CQ06
        {
            get
            {
                return this._cq06;
            }
            set
            {
                this._cq06 = value;
            }
        }

        /// <summary>
        /// 寄样日期
        /// </summary>

        public DateTime CQ07
        {
            get
            {
                return this._cq07;
            }
            set
            {
                this._cq07 = value;
            }
        }

        /// <summary>
        /// 打样部门(一部)
        /// </summary>

        public string CQ08
        {
            get
            {
                return this._cq08;
            }
            set
            {
                this._cq08 = value;
            }
        }

        /// <summary>
        /// 打样部门(二部)
        /// </summary>

        public string CQ09
        {
            get
            {
                return this._cq09;
            }
            set
            {
                this._cq09 = value;
            }
        }

        /// <summary>
        /// 打样部门(三部)
        /// </summary>

        public string CQ10
        {
            get
            {
                return this._cq10;
            }
            set
            {
                this._cq10 = value;
            }
        }

        /// <summary>
        /// 打样部门(打样间)
        /// </summary>

        public string CQ11
        {
            get
            {
                return this._cq11;
            }
            set
            {
                this._cq11 = value;
            }
        }

        /// <summary>
        /// 进口目的国
        /// </summary>

        public string CQ12
        {
            get
            {
                return this._cq12;
            }
            set
            {
                this._cq12 = value;
            }
        }

        /// <summary>
        /// 年龄段
        /// </summary>

        public string CQ13
        {
            get
            {
                return this._cq13;
            }
            set
            {
                this._cq13 = value;
            }
        }

        /// <summary>
        /// 样品数量(套)
        /// </summary>

        public int CQ14
        {
            get
            {
                return this._cq14;
            }
            set
            {
                this._cq14 = value;
            }
        }

        /// <summary>
        /// 测试要求(ASTM-F963)
        /// </summary>

        public string CQ15
        {
            get
            {
                return this._cq15;
            }
            set
            {
                this._cq15 = value;
            }
        }

        /// <summary>
        /// 测试要求(EN71)
        /// </summary>

        public string CQ16
        {
            get
            {
                return this._cq16;
            }
            set
            {
                this._cq16 = value;
            }
        }

        /// <summary>
        /// 测试要求(澳大利亚)
        /// </summary>

        public string CQ17
        {
            get
            {
                return this._cq17;
            }
            set
            {
                this._cq17 = value;
            }
        }

        /// <summary>
        /// 测试要求(日本)
        /// </summary>

        public string CQ18
        {
            get
            {
                return this._cq18;
            }
            set
            {
                this._cq18 = value;
            }
        }

        /// <summary>
        /// 测试要求(其它)
        /// </summary>

        public string CQ19
        {
            get
            {
                return this._cq19;
            }
            set
            {
                this._cq19 = value;
            }
        }

        /// <summary>
        /// 测试要求(其它)
        /// </summary>

        public string CQ20
        {
            get
            {
                return this._cq20;
            }
            set
            {
                this._cq20 = value;
            }
        }

        /// <summary>
        /// 测试方法、标准及规程的提供
        /// </summary>

        public string CQ21
        {
            get
            {
                return this._cq21;
            }
            set
            {
                this._cq21 = value;
            }
        }

        /// <summary>
        /// 样品用途(确认样(初样))
        /// </summary>

        public string CQ22
        {
            get
            {
                return this._cq22;
            }
            set
            {
                this._cq22 = value;
            }
        }

        /// <summary>
        /// 样品用途(外观照样)
        /// </summary>

        public string CQ23
        {
            get
            {
                return this._cq23;
            }
            set
            {
                this._cq23 = value;
            }
        }

        /// <summary>
        /// 样品用途(测试样)
        /// </summary>

        public string CQ24
        {
            get
            {
                return this._cq24;
            }
            set
            {
                this._cq24 = value;
            }
        }

        /// <summary>
        /// 样品用途(大货样)
        /// </summary>

        public string CQ25
        {
            get
            {
                return this._cq25;
            }
            set
            {
                this._cq25 = value;
            }
        }

        /// <summary>
        /// 样品用途(参展样)
        /// </summary>

        public string CQ26
        {
            get
            {
                return this._cq26;
            }
            set
            {
                this._cq26 = value;
            }
        }

        /// <summary>
        /// 样品用途(其它)
        /// </summary>

        public string CQ27
        {
            get
            {
                return this._cq27;
            }
            set
            {
                this._cq27 = value;
            }
        }

        /// <summary>
        /// 样品用途(其它)
        /// </summary>

        public string CQ28
        {
            get
            {
                return this._cq28;
            }
            set
            {
                this._cq28 = value;
            }
        }

        /// <summary>
        /// 样品资料(参考样品)
        /// </summary>

        public string CQ29
        {
            get
            {
                return this._cq29;
            }
            set
            {
                this._cq29 = value;
            }
        }

        /// <summary>
        /// 样品资料(设计图)
        /// </summary>

        public string CQ30
        {
            get
            {
                return this._cq30;
            }
            set
            {
                this._cq30 = value;
            }
        }

        /// <summary>
        /// 样品资料(工程图)
        /// </summary>

        public string CQ31
        {
            get
            {
                return this._cq31;
            }
            set
            {
                this._cq31 = value;
            }
        }

        /// <summary>
        /// 样品资料(其它)
        /// </summary>

        public string CQ32
        {
            get
            {
                return this._cq32;
            }
            set
            {
                this._cq32 = value;
            }
        }

        /// <summary>
        /// 样品资料(其它)
        /// </summary>

        public string CQ33
        {
            get
            {
                return this._cq33;
            }
            set
            {
                this._cq33 = value;
            }
        }

        /// <summary>
        /// 产品图片
        /// </summary>
        public byte[] CQ34
        {
            get
            {
                return _cq34;
            }
            set
            {
                _cq34 = value;
            }
        }

        /// <summary>
        /// 监督人(雕刻)
        /// </summary>

        public string CQ35
        {
            get
            {
                return this._cq35;
            }
            set
            {
                this._cq35 = value;
            }
        }

        /// <summary>
        /// 样品间(木工)
        /// </summary>
        public string CQ36
        {
            get
            {
                return this._cq36;
            }
            set
            {
                this._cq36 = value;
            }
        }

        /// <summary>
        /// 样品间(组装)
        /// </summary>

        public string CQ37
        {
            get
            {
                return this._cq37;
            }
            set
            {
                this._cq37 = value;
            }
        }

        /// <summary>
        /// 生产部(喷漆)
        /// </summary>

        public string CQ38
        {
            get
            {
                return this._cq38;
            }
            set
            {
                this._cq38 = value;
            }
        }

        /// <summary>
        /// 生产部(印刷)
        /// </summary>

        public string CQ39
        {
            get
            {
                return this._cq39;
            }
            set
            {
                this._cq39 = value;
            }
        }

        /// <summary>
        /// 质检部(油漆)
        /// </summary>

        public string CQ40
        {
            get
            {
                return this._cq40;
            }
            set
            {
                this._cq40 = value;
            }
        }

        /// <summary>
        /// 质检部(样品测试)
        /// </summary>

        public string CQ41
        {
            get
            {
                return this._cq41;
            }
            set
            {
                this._cq41 = value;
            }
        }

        /// <summary>
        /// 采购部(原材料)
        /// </summary>

        public string CQ42
        {
            get
            {
                return this._cq42;
            }
            set
            {
                this._cq42 = value;
            }
        }

        /// <summary>
        /// 采购部(辅料)
        /// </summary>

        public string CQ43
        {
            get
            {
                return this._cq43;
            }
            set
            {
                this._cq43 = value;
            }
        }

        /// <summary>
        /// 业务部(报价)
        /// </summary>

        public string CQ44
        {
            get
            {
                return this._cq44;
            }
            set
            {
                this._cq44 = value;
            }
        }

        /// <summary>
        /// 业务部(资料提供)
        /// </summary>

        public string CQ45
        {
            get
            {
                return this._cq45;
            }
            set
            {
                this._cq45 = value;
            }
        }

        /// <summary>
        /// 雕刻数量
        /// </summary>

        public int CQ46
        {
            get
            {
                return this._cq46;
            }
            set
            {
                this._cq46 = value;
            }
        }

        /// <summary>
        /// 木工数量
        /// </summary>

        public int CQ47
        {
            get
            {
                return this._cq47;
            }
            set
            {
                this._cq47 = value;
            }
        }

        /// <summary>
        /// 组装数量
        /// </summary>

        public int CQ48
        {
            get
            {
                return this._cq48;
            }
            set
            {
                this._cq48 = value;
            }
        }

        /// <summary>
        /// 喷漆数量
        /// </summary>

        public int CQ49
        {
            get
            {
                return this._cq49;
            }
            set
            {
                this._cq49 = value;
            }
        }

        /// <summary>
        /// 印刷数量
        /// </summary>

        public int CQ50
        {
            get
            {
                return this._cq50;
            }
            set
            {
                this._cq50 = value;
            }
        }

        /// <summary>
        /// 油漆数量
        /// </summary>

        public int CQ51
        {
            get
            {
                return this._cq51;
            }
            set
            {
                this._cq51 = value;
            }
        }

        /// <summary>
        /// 样品测试数量
        /// </summary>

        public int CQ52
        {
            get
            {
                return this._cq52;
            }
            set
            {
                this._cq52 = value;
            }
        }

        /// <summary>
        /// 原材料数量
        /// </summary>

        public int CQ53
        {
            get
            {
                return this._cq53;
            }
            set
            {
                this._cq53 = value;
            }
        }

        /// <summary>
        /// 辅料数量
        /// </summary>

        public int CQ54
        {
            get
            {
                return this._cq54;
            }
            set
            {
                this._cq54 = value;
            }
        }

        /// <summary>
        /// 报价数量
        /// </summary>

        public int CQ55
        {
            get
            {
                return this._cq55;
            }
            set
            {
                this._cq55 = value;
            }
        }

        /// <summary>
        /// 资料提供数量
        /// </summary>

        public int CQ56
        {
            get
            {
                return this._cq56;
            }
            set
            {
                this._cq56 = value;
            }
        }

        /// <summary>
        /// 雕刻计划完成时间
        /// </summary>

        public DateTime CQ57
        {
            get
            {
                return this._cq57;
            }
            set
            {
                this._cq57 = value;
            }
        }

        /// <summary>
        /// 木工计划完成时间
        /// </summary>

        public DateTime CQ58
        {
            get
            {
                return this._cq58;
            }
            set
            {
                this._cq58 = value;
            }
        }

        /// <summary>
        /// 组装计划完成时间
        /// </summary>

        public DateTime CQ59
        {
            get
            {
                return this._cq59;
            }
            set
            {
                this._cq59 = value;
            }
        }

        /// <summary>
        /// 喷漆计划完成时间
        /// </summary>

        public DateTime CQ60
        {
            get
            {
                return this._cq60;
            }
            set
            {
                this._cq60 = value;
            }
        }

        /// <summary>
        /// 印刷计划完成时间
        /// </summary>

        public DateTime CQ61
        {
            get
            {
                return this._cq61;
            }
            set
            {
                this._cq61 = value;
            }
        }

        /// <summary>
        /// 油漆计划完成时间
        /// </summary>

        public DateTime CQ62
        {
            get
            {
                return this._cq62;
            }
            set
            {
                this._cq62 = value;
            }
        }

        /// <summary>
        /// 样品测试计划完成时间
        /// </summary>

        public DateTime CQ63
        {
            get
            {
                return this._cq63;
            }
            set
            {
                this._cq63 = value;
            }
        }

        /// <summary>
        /// 原材料计划完成时间
        /// </summary>

        public DateTime CQ64
        {
            get
            {
                return this._cq64;
            }
            set
            {
                this._cq64 = value;
            }
        }

        /// <summary>
        /// 辅料计划完成时间
        /// </summary>

        public DateTime CQ65
        {
            get
            {
                return this._cq65;
            }
            set
            {
                this._cq65 = value;
            }
        }

        /// <summary>
        /// 报价计划完成时间
        /// </summary>

        public DateTime CQ66
        {
            get
            {
                return this._cq66;
            }
            set
            {
                this._cq66 = value;
            }
        }

        /// <summary>
        /// 资料提供计划完成时间
        /// </summary>

        public DateTime CQ67
        {
            get
            {
                return this._cq67;
            }
            set
            {
                this._cq67 = value;
            }
        }

        /// <summary>
        /// 雕刻实际完成时间
        /// </summary>

        public DateTime CQ68
        {
            get
            {
                return this._cq68;
            }
            set
            {
                this._cq68 = value;
            }
        }

        /// <summary>
        /// 木工实际完成时间
        /// </summary>

        public DateTime CQ69
        {
            get
            {
                return this._cq69;
            }
            set
            {
                this._cq69 = value;
            }
        }

        /// <summary>
        /// 组装实际完成时间
        /// </summary>

        public DateTime CQ70
        {
            get
            {
                return this._cq70;
            }
            set
            {
                this._cq70 = value;
            }
        }

        /// <summary>
        /// 喷漆实际完成时间
        /// </summary>
        public DateTime CQ71
        {
            get
            {
                return this._cq71;
            }
            set
            {
                this._cq71 = value;
            }
        }

        /// <summary>
        /// 印刷实际完成时间
        /// </summary>

        public DateTime CQ72
        {
            get
            {
                return this._cq72;
            }
            set
            {
                this._cq72 = value;
            }
        }

        /// <summary>
        /// 油漆实际完成时间
        /// </summary>

        public DateTime CQ73
        {
            get
            {
                return this._cq73;
            }
            set
            {
                this._cq73 = value;
            }
        }

        /// <summary>
        /// 样品测试实际完成时间
        /// </summary>

        public DateTime CQ74
        {
            get
            {
                return this._cq74;
            }
            set
            {
                this._cq74 = value;
            }
        }

        /// <summary>
        /// 原材料实际完成时间
        /// </summary>

        public DateTime CQ75
        {
            get
            {
                return this._cq75;
            }
            set
            {
                this._cq75 = value;
            }
        }

        /// <summary>
        /// 辅料实际完成时间
        /// </summary>

        public DateTime CQ76
        {
            get
            {
                return this._cq76;
            }
            set
            {
                this._cq76 = value;
            }
        }

        /// <summary>
        /// 报价实际完成时间
        /// </summary>

        public DateTime CQ77
        {
            get
            {
                return this._cq77;
            }
            set
            {
                this._cq77 = value;
            }
        }

        /// <summary>
        /// 资料提供实际完成时间
        /// </summary>

        public DateTime CQ78
        {
            get
            {
                return this._cq78;
            }
            set
            {
                this._cq78 = value;
            }
        }

        /// <summary>
        /// 材种(业务员及策划确定)--MDF
        /// </summary>

        public string CQ79
        {
            get
            {
                return this._cq79;
            }
            set
            {
                this._cq79 = value;
            }
        }

        /// <summary>
        /// 材种(业务员及策划确定)--夹板
        /// </summary>

        public string CQ80
        {
            get
            {
                return this._cq80;
            }
            set
            {
                this._cq80 = value;
            }
        }

        /// <summary>
        /// 材种(业务员及策划确定)--榉木
        /// </summary>

        public string CQ81
        {
            get
            {
                return this._cq81;
            }
            set
            {
                this._cq81 = value;
            }
        }

        /// <summary>
        /// 材种(业务员及策划确定)--荷木
        /// </summary>

        public string CQ82
        {
            get
            {
                return this._cq82;
            }
            set
            {
                this._cq82 = value;
            }
        }

        /// <summary>
        /// 材种(业务员及策划确定)--新西兰松
        /// </summary>

        public string CQ83
        {
            get
            {
                return this._cq83;
            }
            set
            {
                this._cq83 = value;
            }
        }

        /// <summary>
        /// 材种(业务员及策划确定)--橡胶木
        /// </summary>

        public string CQ84
        {
            get
            {
                return this._cq84;
            }
            set
            {
                this._cq84 = value;
            }
        }

        /// <summary>
        /// 材种(业务员及策划确定)--桦木
        /// </summary>

        public string CQ85
        {
            get
            {
                return this._cq85;
            }
            set
            {
                this._cq85 = value;
            }
        }

        /// <summary>
        /// 材种(业务员及策划确定)--椴木
        /// </summary>

        public string CQ86
        {
            get
            {
                return this._cq86;
            }
            set
            {
                this._cq86 = value;
            }
        }

        /// <summary>
        /// 产品及部件功能提示(业务员)
        /// </summary>

        public string CQ87
        {
            get
            {
                return this._cq87;
            }
            set
            {
                this._cq87 = value;
            }
        }

        /// <summary>
        /// 生产工艺要点提示(策划确定)
        /// </summary>

        public string CQ88
        {
            get
            {
                return this._cq88;
            }
            set
            {
                this._cq88 = value;
            }
        }

        /// <summary>
        /// 生产部.样品间(签收人)
        /// </summary>

        public string CQ89
        {
            get
            {
                return this._cq89;
            }
            set
            {
                this._cq89 = value;
            }
        }

        /// <summary>
        /// 质检部(签收人)
        /// </summary>

        public string CQ90
        {
            get
            {
                return this._cq90;
            }
            set
            {
                this._cq90 = value;
            }
        }

        /// <summary>
        /// 采购部(签收人)
        /// </summary>

        public string CQ91
        {
            get
            {
                return this._cq91;
            }
            set
            {
                this._cq91 = value;
            }
        }

        /// <summary>
        /// 其它部门(签收人)
        /// </summary>

        public string CQ92
        {
            get
            {
                return this._cq92;
            }
            set
            {
                this._cq92 = value;
            }
        }

        /// <summary>
        /// 注(签收人)
        /// </summary>

        public string CQ93
        {
            get
            {
                return this._cq93;
            }
            set
            {
                this._cq93 = value;
            }
        }

        /// <summary>
        /// 申请人
        /// </summary>

        public string CQ94
        {
            get
            {
                return this._cq94;
            }
            set
            {
                this._cq94 = value;
            }
        }

        /// <summary>
        /// 审批人
        /// </summary>

        public string CQ95
        {
            get
            {
                return this._cq95;
            }
            set
            {
                this._cq95 = value;
            }
        }

        /// <summary>
        /// 填表日期
        /// </summary>

        public DateTime CQ96
        {
            get
            {
                return this._cq96;
            }
            set
            {
                this._cq96 = value;
            }
        }

        /// <summary>
        /// 维护记录
        /// </summary>

        public string CQ97
        {
            get
            {
                return this._cq97;
            }
            set
            {
                this._cq97 = value;
            }
        }

        /// <summary>
        /// 维护意见
        /// </summary>

        public string CQ98
        {
            get
            {
                return this._cq98;
            }
            set
            {
                this._cq98 = value;
            }
        }

        /// <summary>
        /// 物料或部件名称
        /// </summary>

        public string CQ99
        {
            get
            {
                return this._cq99;
            }
            set
            {
                this._cq99 = value;
            }
        }

        /// <summary>
        /// 规格
        /// </summary>

        public string CQ100
        {
            get
            {
                return this._cq100;
            }
            set
            {
                this._cq100 = value;
            }
        }

        /// <summary>
        /// 品牌型号
        /// </summary>

        public string CQ101
        {
            get
            {
                return this._cq101;
            }
            set
            {
                this._cq101 = value;
            }
        }

        /// <summary>
        /// 样品数量
        /// </summary>

        public int CQ102
        {
            get
            {
                return this._cq102;
            }
            set
            {
                this._cq102 = value;
            }
        }

        /// <summary>
        /// 每套用量
        /// </summary>

        public decimal CQ103
        {
            get
            {
                return this._cq103;
            }
            set
            {
                this._cq103 = value;
            }
        }

        /// <summary>
        /// 单位
        /// </summary>
        public string CQ104
        {
            get
            {
                return this._cq104;
            }
            set
            {
                this._cq104 = value;
            }
        }

        /// <summary>
        /// 单价
        /// </summary>

        public decimal CQ105
        {
            get
            {
                return this._cq105;
            }
            set
            {
                this._cq105 = value;
            }
        }

        /// <summary>
        /// 到货时限
        /// </summary>

        public DateTime CQ106
        {
            get
            {
                return this._cq106;
            }
            set
            {
                this._cq106 = value;
            }
        }

        /// <summary>
        /// 实到时间
        /// </summary>

        public DateTime CQ107
        {
            get
            {
                return this._cq107;
            }
            set
            {
                this._cq107 = value;
            }
        }

        /// <summary>
        /// 材质要求说明(策划确定)
        /// </summary>

        public string CQ108
        {
            get
            {
                return this._cq108;
            }
            set
            {
                this._cq108 = value;
            }
        }

        /// <summary>
        /// NC漆
        /// </summary>

        public string CQ109
        {
            get
            {
                return this._cq109;
            }
            set
            {
                this._cq109 = value;
            }
        }

        /// <summary>
        /// 水性漆(国产)
        /// </summary>

        public string CQ110
        {
            get
            {
                return this._cq110;
            }
            set
            {
                this._cq110 = value;
            }
        }

        /// <summary>
        /// 水性漆(进口)
        /// </summary>

        public string CQ111
        {
            get
            {
                return this._cq111;
            }
            set
            {
                this._cq111 = value;
            }
        }
        
        /// <summary>
        /// 状态
        /// </summary>
                 
        public string CQ112
        {
            get
            {
                return this._cq112;
            }
            set
            {
                this._cq112 = value;
            }
        }
        
        /// <summary>
        /// 日期
        /// </summary>
                 
        public DateTime CQ113
        {
            get
            {
                return this._cq113;
            }
            set
            {
                this._cq113 = value;
            }
        }
        
        /// <summary>
        /// 供应商
        /// </summary>
                 
        public string CQ114
        {
            get
            {
                return this._cq114;
            }
            set
            {
                this._cq114 = value;
            }
        }
        
        // 
        public string CQ115
        {
            get
            {
                return this._cq115;
            }
            set
            {
                this._cq115 = value;
            }
        }
        
        // 
        public string CQ116
        {
            get
            {
                return this._cq116;
            }
            set
            {
                this._cq116 = value;
            }
        }
        
        // 
        public string CQ117
        {
            get
            {
                return this._cq117;
            }
            set
            {
                this._cq117 = value;
            }
        }
        
        // 
        public string CQ118
        {
            get
            {
                return this._cq118;
            }
            set
            {
                this._cq118 = value;
            }
        }
        
        // 
        public string CQ119
        {
            get
            {
                return this._cq119;
            }
            set
            {
                this._cq119 = value;
            }
        }
        
        // 
        public string CQ120
        {
            get
            {
                return this._cq120;
            }
            set
            {
                this._cq120 = value;
            }
        }
    }
}
