//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class ZuZhangGongZiKaoHeOneEntity
    {
        
        private int _idx;
        
        private string _ay001;
        
        private decimal _ay002;
        
        private decimal _ay003;
        
        private decimal _ay004;
        
        private decimal _ay005;
        
        private decimal _ay006;
        
        private decimal _ay007;
        
        private decimal _ay008;
        
        private decimal _ay009;
        
        private decimal _ay010;
        
        private decimal _ay011;
        
        private decimal _ay012;
        
        private decimal _ay013;
        
        private decimal _ay014;
        
        private decimal _ay015;
        
        private decimal _ay016;
        
        private decimal _ay017;
        
        private decimal _ay018;
        
        private decimal _ay019;
        
        private decimal _ay020;
        
        private decimal _ay021;
        
        private decimal _ay022;
        
        private decimal _ay023;
        
        private decimal _ay024;
        
        private decimal _ay025;
        
        private decimal _ay026;
        
        private decimal _ay027;
        
        private decimal _ay028;
        
        private decimal _ay029;
        
        private decimal _ay030;
        
        // 
        public int idx
        {
            get
            {
                return this._idx;
            }
            set
            {
                this._idx = value;
            }
        }
        
        // 
        public string AY001
        {
            get
            {
                return this._ay001;
            }
            set
            {
                this._ay001 = value;
            }
        }
        
        // 
        public decimal AY002
        {
            get
            {
                return this._ay002;
            }
            set
            {
                this._ay002 = value;
            }
        }
        
        // 
        public decimal AY003
        {
            get
            {
                return this._ay003;
            }
            set
            {
                this._ay003 = value;
            }
        }
        
        // 
        public decimal AY004
        {
            get
            {
                return this._ay004;
            }
            set
            {
                this._ay004 = value;
            }
        }
        
        // 
        public decimal AY005
        {
            get
            {
                return this._ay005;
            }
            set
            {
                this._ay005 = value;
            }
        }
        
        // 
        public decimal AY006
        {
            get
            {
                return this._ay006;
            }
            set
            {
                this._ay006 = value;
            }
        }
        
        // 
        public decimal AY007
        {
            get
            {
                return this._ay007;
            }
            set
            {
                this._ay007 = value;
            }
        }
        
        // 
        public decimal AY008
        {
            get
            {
                return this._ay008;
            }
            set
            {
                this._ay008 = value;
            }
        }
        
        // 
        public decimal AY009
        {
            get
            {
                return this._ay009;
            }
            set
            {
                this._ay009 = value;
            }
        }
        
        // 
        public decimal AY010
        {
            get
            {
                return this._ay010;
            }
            set
            {
                this._ay010 = value;
            }
        }
        
        // 
        public decimal AY011
        {
            get
            {
                return this._ay011;
            }
            set
            {
                this._ay011 = value;
            }
        }
        
        // 
        public decimal AY012
        {
            get
            {
                return this._ay012;
            }
            set
            {
                this._ay012 = value;
            }
        }
        
        // 
        public decimal AY013
        {
            get
            {
                return this._ay013;
            }
            set
            {
                this._ay013 = value;
            }
        }
        
        // 
        public decimal AY014
        {
            get
            {
                return this._ay014;
            }
            set
            {
                this._ay014 = value;
            }
        }
        
        // 
        public decimal AY015
        {
            get
            {
                return this._ay015;
            }
            set
            {
                this._ay015 = value;
            }
        }
        
        // 
        public decimal AY016
        {
            get
            {
                return this._ay016;
            }
            set
            {
                this._ay016 = value;
            }
        }
        
        // 
        public decimal AY017
        {
            get
            {
                return this._ay017;
            }
            set
            {
                this._ay017 = value;
            }
        }
        
        // 
        public decimal AY018
        {
            get
            {
                return this._ay018;
            }
            set
            {
                this._ay018 = value;
            }
        }
        
        // 
        public decimal AY019
        {
            get
            {
                return this._ay019;
            }
            set
            {
                this._ay019 = value;
            }
        }
        
        // 
        public decimal AY020
        {
            get
            {
                return this._ay020;
            }
            set
            {
                this._ay020 = value;
            }
        }
        
        // 
        public decimal AY021
        {
            get
            {
                return this._ay021;
            }
            set
            {
                this._ay021 = value;
            }
        }
        
        // 
        public decimal AY022
        {
            get
            {
                return this._ay022;
            }
            set
            {
                this._ay022 = value;
            }
        }
        
        // 
        public decimal AY023
        {
            get
            {
                return this._ay023;
            }
            set
            {
                this._ay023 = value;
            }
        }
        
        // 
        public decimal AY024
        {
            get
            {
                return this._ay024;
            }
            set
            {
                this._ay024 = value;
            }
        }
        
        // 
        public decimal AY025
        {
            get
            {
                return this._ay025;
            }
            set
            {
                this._ay025 = value;
            }
        }
        
        // 
        public decimal AY026
        {
            get
            {
                return this._ay026;
            }
            set
            {
                this._ay026 = value;
            }
        }
        
        // 
        public decimal AY027
        {
            get
            {
                return this._ay027;
            }
            set
            {
                this._ay027 = value;
            }
        }
        
        // 
        public decimal AY028
        {
            get
            {
                return this._ay028;
            }
            set
            {
                this._ay028 = value;
            }
        }
        
        // 
        public decimal AY029
        {
            get
            {
                return this._ay029;
            }
            set
            {
                this._ay029 = value;
            }
        }
        
        // 
        public decimal AY030
        {
            get
            {
                return this._ay030;
            }
            set
            {
                this._ay030 = value;
            }
        }
    }
}
